### ISSUE TITLE
after everything done device not turned on [deep sleep in dfu]

### ISSUE THREAD

**Issue by SuginGv30** [palera1n/palera1n#100]
Hello, iPhone10,3 on 15.5!
[*] Switching device into recovery mode...
Telling device with udid 1e3b6f049dcc520a99a6d0d02925f6b31033a3b1 to enter recovery mode.
Device is successfully switching to recovery mode.
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Pwning device
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[*] Booting device

Done!
The device should now boot to iOS
If you already have ran palera1n, click Do All in the tools section of Pogo
If not, Pogo should be installed to Tips
ubuntu@ubuntu:~/Downloads/palera1n$

**Comment by SuginGv30** [comment]
![image](https://user-images.githubusercontent.com/112756329/194150237-98b6b672-6d85-4d53-8dad-13ff47f3d241.jpeg)

**Comment by SuginGv30** [comment]
But the device is not turned on

When i exit from dfu mode manually i tried to open tips but app crashing

Device iphone x ios 15.5 already restored no password 

![image](https://user-images.githubusercontent.com/112756329/194150701-750ec35f-be9f-47a6-9ced-62c051922471.jpeg)

**Comment by itsnebulalol** [comment]
`./palera1n.sh clean`
