### ISSUE TITLE
Stuck on Waiting for the ramdisk to finish booting

### ISSUE THREAD

**Issue by oliverlinux** [palera1n/palera1n#102]
I am using rootless. The iPad says that the service is running from the SSH RamDisk, but palera1n doesn't see it

**Comment by oliverlinux** [comment]
I am using the iPad 7,1 (A10X, iOS 15.7)

**Comment by oliverlinux** [comment]
Happens on both Ubuntu and Fedora Live USB, tried Ubuntu on 2 computers

**Comment by oliverlinux** [comment]
Fixed with https://github.com/palera1n/palera1n/issues/95 but now my device won't do the second reboot or even charge from my PC

**Comment by oliverlinux** [comment]
Tried killing usbmuxd and relaunch, and retried, but now im stuck on [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:0C ECID:000E701818FAE03A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:0C ECID:000E701818FAE03A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:0C ECID:000E701818FAE03

**Comment by itsnebulalol** [comment]
It's an issue with usbmuxd. Try compiling and installing usbmuxd2
