### ISSUE TITLE
Issues with Pogo

### ISSUE THREAD

**Issue by Shaneee** [palera1n/palera1n#104]
**Describe the bug**
After a lot of tweaking I got it to run successfully on my 1st gen iPad Pro now running iOS 15.7. Once booted I opened the Tips app to be greeted with Pogo. However when I touch Tools the app crashes. If I touch install it goes through installing bootstrap, installing Sileo etc but nothing really seems to happen.

**Info (please complete the following information):**
- iDevice's version: [e.g. iOS 15.2, iOS 15.1] 15.7
- Computer OS and version: [e.g. macOS 13.0b3, Ubuntu 22.04] macOS 13.0 b10
- The command you ran: [e.g. `./palera1n.sh --dfu 15.1`] ./palera1n --dfu 15.7

**Comment by callejasaldx** [comment]
the same thing happens to me but I'm sure it's a problem bc of the ios version. the only thing that comes to mind is to do a downgrade, although. idk how people run with 15.7 and works

**Comment by Shaneee** [comment]
Installed TrollStore and installed Pogo that way. Seemed to work doing this.

**Comment by Uckermark** [comment]
This is fixed in the latest version of Pogo
