### ISSUE TITLE
blobs invalid

### ISSUE THREAD

**Issue by pwnd2e** [palera1n/palera1n#105]
[*] Booting ramdisk
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:0002095A20EBA02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Device should now show text on screen
[*] Waiting for the ramdisk to finish booting
[*] Dumping blobs and installing Pogo
16285+99 records in
16377+1 records out
4192538 bytes transferred in 0.258077 secs (16245299 bytes/sec)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
Found IM4R extracting generator: ok
Saved IM4M to blobs/iPhone10,3-15.1.shsh2
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-63899/6CAB53E5-5411-4140-BA83-0E37B1397558/iPhone10,3,iPhone10,6_15.1_19B74_Restore.ipsw
init done
getting: BuildManifest.plist
  0% [                                                                          100% [==========================================================================  5% [====>                                                                      10% [=========>                                                                 15% [==============>                                                            21% [====================>                                                      26% [=========================>                                                 31% [==============================>                                            37% [====================================>                                      42% [=========================================>                                 47% [==============================================>                            53% [====================================================>                      58% [=========================================================>                 63% [==============================================================>            69% [====================================================================>      74% [=========================================================================> 79% [========================================================================== 84% [========================================================================== 90% [========================================================================== 95% [==========================================================================100% [===================================================================================================>]
download succeeded
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: https://updates.cdn-apple.com/2021FallFCS/patches/071-63947/088D55EB-03D9-49F1-8390-59CB45EE36CE/com_apple_MobileAsset_SoftwareUpdate/9cdf7aad66f2d1e7b92d33db0ced0dde5a9753cb.zip
init done
getting: AssetData/boot/BuildManifest.plist
  0% [                                                                          100% [========================================================================== 57% [========================================================>                 100% [===================================================================================================>]
download succeeded
[*] Validating dumped blobs...
[*] Dumped blobs are NOT valid! Trying again...
16270+114 records in
16375+1 records out
4192152 bytes transferred in 0.239081 secs (17534442 bytes/sec)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
Found IM4R extracting generator: ok
Saved IM4M to blobs/iPhone10,3-15.1.shsh2
[*] Blobs are still invalid... once your device reboots, retry
./palera1n.sh: line 121: 52328 Terminated: 15          "$dir"/iproxy 2222 22
pwnd2e@2es-custom-services-MacBook-Air palera1n %

**Comment by HiPriv228** [comment]
Disable flag "--debug" and retry

**Comment by aditya11110** [comment]
same issue friend

**Comment by itsnebulalol** [comment]
Please retry on the latest commit
