### ISSUE TITLE
Downloading BuildManifest crash 

### ISSUE THREAD

**Issue by Anderew-ch** [palera1n/palera1n#106]
Second iPhone reboot and palera1n crashes on Downloading BuildManifest

**Info**
- iDevice's version: [iOS 15.7]
- Computer OS and version: [MacOS 12.5]
- Command: [./palera1n.sh]
- Device info: [iPhone X iPhone10,6 d221ap]

**log**

[*] Device entered DFU!
[*] Pwning device
[*] Converting blob
[*] Downloading BuildManifest
enderman@Endermans-Mac-Pro palera1n %

```

**Comment by pwnd2e** [comment]
Same

**Comment by EchoSkill** [comment]
what MacOs Version are you using?, pzb binary is not working properly and is causing this...

**Comment by itsnebulalol** [comment]
Fixed in latest commit
