### ISSUE TITLE
blobs are still invalid

### ISSUE THREAD

**Issue by SuginGv30** [palera1n/palera1n#110]
download succeeded
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 15 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x180030ad0 : 000080d2
applying patch=0x180030b18 : 000080d2
applying patch=0x18003289c : 200080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 15 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1  ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x180030ad0 : 000080d2
applying patch=0x180030b18 : 000080d2
applying patch=0x18001df64 : 000080d2c0035fd6
applying patch=0x18001dfbc : 000080d2c0035fd6
applying patch=0x180063144 : 000080d2c0035fd6
applying patch=0x18003289c : 200080d2
applying patch=0x180033e14 : 78b80c10
applying patch=0x18004d520 : 72643d6d64302064656275673d30783230313465202d76207764743d2d31202000
applying patch=0x1800389bc : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-8020 inputted
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x39c685
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x12ca924
get_amfi_out_of_my_way_patch: Patching AMFI at 0x12c7160
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
none
none
[*] Booting ramdisk
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Device should now show text on screen
[*] Waiting for the ramdisk to finish booting
Creating listening port 2222 for device port 22
[*] Dumping blobs and installing Pogo
waiting for connection
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
Requesting connecion to USB device handle 13 (serial: ramdisk tool Sep 18 2022 20:14:43), port 22
New connection for 2222->22, fd = 5
waiting for connectiondd: warning: partial read (238 bytes); suggest iflag=fullblock
16347+37 records in
16347+37 records out
4192054 bytes (4.2 MB, 4.0 MiB) copied, 0.206409 s, 20.3 MB/s
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
Found IM4R extracting generator: ok
Saved IM4M to blobs/iPhone10,3-15.5.shsh2
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022SpringFCS/fullrestores/012-08019/9B77837B-6568-45E6-8C0F-3BC5B952371B/iPhone10,3,iPhone10,6_15.5_19F77_Restore.ipsw
init done
getting: BuildManifest.plist
  0% [                                                                          100% [========================================================================== 64% [===============================================================>          100% [===================================================================================================>]
download succeeded
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022SpringFCS/patches/012-07314/745F1C14-9CF2-4DB0-9223-A38B46C3D233/com_apple_MobileAsset_SoftwareUpdate/4b6c9584f31fcb0fea63521d70221e79a8b4d230.zip
init done
getting: AssetData/boot/BuildManifest.plist
  0% [                                                                         100% [========================================================================= 57% [========================================================>                100% [===================================================================================================>]
download succeeded
[*] Validating dumped blobs...
[*] Dumped blobs are NOT valid! Trying again...
dd: warning: partial read (238 bytes); suggest iflag=fullblock
16351+33 records in
16351+33 records out
4192009 bytes (4.2 MB, 4.0 MiB) copied, 0.215378 s, 19.5 MB/s
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
Found IM4R extracting generator: ok
Saved IM4M to blobs/iPhone10,3-15.5.shsh2
[*] Blobs are still invalid... once your device reboots, retry
ubuntu@ubuntu:~/Downloads/palera1n$

**Comment by itsnebulalol** [comment]
Please use the latest commit
