### ISSUE TITLE
ios15.3.1 iphone8 10.1 erroe

### ISSUE THREAD

**Issue by rainbowjjjny** [palera1n/palera1n#111]
download succeeded
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:000D31993030002E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:000D31993030002E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 15 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800309b8 : 000080d2
applying patch=0x180030a00 : 000080d2
applying patch=0x1800325d4 : 200080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 15 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1  ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800309b8 : 000080d2
applying patch=0x180030a00 : 000080d2
applying patch=0x18001df90 : 000080d2c0035fd6
applying patch=0x18001dfe8 : 000080d2c0035fd6
applying patch=0x180061d98 : 000080d2c0035fd6
applying patch=0x1800325d4 : 200080d2
applying patch=0x180033c3c : 18470c10
applying patch=0x18004c51c : 72643d6d64302064656275673d30783230313465202d76207764743d2d31202000
applying patch=0x1800386bc : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-8019 inputted
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x3ffee6
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x1326424
get_amfi_out_of_my_way_patch: Patching AMFI at 0x1322c18
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
/dev/disk4          	                               	/private/tmp/SSHRD
Darwin/gtar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'

**Comment by itsnebulalol** [comment]
That is not an error.
