### ISSUE TITLE
blobs error

### ISSUE THREAD

**Issue by VR-HoangLong** [palera1n/palera1n#113]
my device is 6s 15.4
![image](https://user-images.githubusercontent.com/106237833/194300779-13f44a35-c7d0-4445-9d33-18f4d5950f98.png)

**Comment by VR-HoangLong** [comment]
it's solved now but it stucked at ramdisk boot
is 15.4 compatible ?

**Comment by itsnebulalol** [comment]
Please use the latest commit

**Comment by Halo-Michael** [comment]
@itsnebulalol Because he is using gnu-sed not apple's sed. So patch boot roms will also not work, that's why he can't boot.

**Comment by VR-HoangLong** [comment]
> 

can you explain more

**Comment by VR-HoangLong** [comment]
> @itsnebulalol Because he is using gnu-sed not apple's sed. So patch boot roms will also not work, that's why he can't boot.

can you explain more

**Comment by Halo-Michael** [comment]
> > @itsnebulalol Because he is using gnu-sed not apple's sed. So patch boot roms will also not work, that's why he can't boot.
> 
> can you explain more

use `which sed` to check:
![CA8A133D-0F72-48FD-AF42-D14979C4A7F9](https://user-images.githubusercontent.com/45062120/194325335-c50cd455-3da2-4e21-8658-cedda9afac78.png)

**Comment by VR-HoangLong** [comment]
> > > @itsnebulalol Because he is using gnu-sed not apple's sed. So patch boot roms will also not work, that's why he can't boot.
> > 
> > 
> > can you explain more
> 
> use `which sed` to check: ![CA8A133D-0F72-48FD-AF42-D14979C4A7F9](https://user-images.githubusercontent.com/45062120/194325335-c50cd455-3da2-4e21-8658-cedda9afac78.png)

![image](https://user-images.githubusercontent.com/106237833/194325823-427cf52c-b465-4c50-9c0f-6cfede5f1b55.png)
i see ibss and ibec downloaded as n71.DEVELOPMENT
it's not compatible with 15.4, right

**Comment by Halo-Michael** [comment]
> > > > @itsnebulalol Because he is using gnu-sed not apple's sed. So patch boot roms will also not work, that's why he can't boot.
> > > 
> > > 
> > > can you explain more
> > 
> > 
> > use `which sed` to check: ![CA8A133D-0F72-48FD-AF42-D14979C4A7F9](https://user-images.githubusercontent.com/45062120/194325335-c50cd455-3da2-4e21-8658-cedda9afac78.png)
> 
> ![image](https://user-images.githubusercontent.com/106237833/194325823-427cf52c-b465-4c50-9c0f-6cfede5f1b55.png) i see ibss and ibec downloaded as n71.DEVELOPMENT it's not compatible with 15.4, right

Well, you just need rootless branche.
