### ISSUE TITLE
Error: file AssetData/boot/BuildManifest.plist does not exist, or is a directory

### ISSUE THREAD

**Issue by SuginGv30** [palera1n/palera1n#114]
palera1n | Version 1.1.0-db0af33
Written by Nebula and Mineek | Some code and ramdisk from Nathan | Loader app by Amy

Hello, iPhone10,3 on 15.5!
[*] Switching device into recovery mode...
Telling device with udid 1e3b6f049dcc520a99a6d0d02925f6b31033a3b1 to enter recovery mode.
Device is successfully switching to recovery mode.
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Pwning device
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[*] Converting blob
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
Saved IM4M to work/IM4M
[*] Downloading BuildManifest
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022SpringFCS/fullrestores/012-08019/9B77837B-6568-45E6-8C0F-3BC5B952371B/iPhone10,3,iPhone10,6_15.5_19F77_Restore.ipsw
init done
Error: file AssetData/boot/BuildManifest.plist does not exist, or is a directory
ubuntu@ubuntu:~/Downloads/palera1n$

**Comment by EchoSkill** [comment]
what MacOs Version are you using?, pzb binary is not working properly and is causing this...

**Comment by itsnebulalol** [comment]
Fixed in latest commit

**Comment by SuginGv30** [comment]
> what MacOs Version are you using?, pzb binary is not working properly and is causing this... 

Not mac im using ubuntu 22.04

**Comment by AmadeusPro** [comment]
Did you solve it? I have the same problem.
