### ISSUE TITLE
iphone x ios 15.5 kernal panic

### ISSUE THREAD

**Issue by SuginGv30** [palera1n/palera1n#115]
[*] Booting ramdisk
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Device should now show text on screen
[*] Waiting for the ramdisk to finish booting
Creating listening port 2222 for device port 22
[*] Dumping blobs and installing Pogo
waiting for connection
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
Requesting connecion to USB device handle 7 (serial: ramdisk tool Sep 18 2022 20:14:43), port 22
New connection for 2222->22, fd = 5
waiting for connection
Requesting connecion to USB device handle 7 (serial: ramdisk tool Sep 18 2022 20:14:43), port dd: warning: partial read (247 bytes); suggest iflag=fullblock
16351+33 records in
16351+33 records out
4192000 bytes (4.2 MB, 4.0 MiB) copied, 0.211931 s, 19.8 MB/s
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
Found IM4R extracting generator: ok
Saved IM4M to blobs/iPhone10,3-15.5.shsh2
seputil: Gigalocker file (/mnt7/61C8CF1D-2D04-50BF-95EB-A4A52BD38B7D.gl) exists
seputil: Gigalocker initialization completed
sepi digest (48 bytes): e363d326e71901cacac08ad79dc38f7683f0a865325e9f0ce7242d5547d894b1d49415a51f82a96c8e5006326767fc92
sepi nonce (20 bytes): 12da24f65072ed838d0cb23e5416d8562dc0298a
rsep digest (48 bytes): bfe25db32d29333613d33973d51787566f817f51f93d055bfa1fb16bcc68bd1ca8223b66253d250215552a47e8407292
rsep nonce (20 bytes): 12da24f65072ed838d0cb23e5416d8562dc0298a
./palera1n.sh: line 415: [: =: unary operator expected
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory

**Comment by SuginGv30** [comment]
![image](https://user-images.githubusercontent.com/112756329/194305577-b4f036c2-b4b0-4b02-b0f0-b7c4302d9b12.jpeg)

**Comment by SuginGv30** [comment]
Got struck in this

**Comment by itsnebulalol** [comment]
You can reboot and run again, make sure to `git pull` first.
