### ISSUE TITLE
iPhone 8 15.2 Wifi Grey Out

### ISSUE THREAD

**Issue by lnguyen234** [palera1n/palera1n#116]
iPhone 8 15.2 wifi grey out after jailbroken with tweaks branch. Does anyone have this issue?
Thanks

**Comment by gabrielrocco** [comment]
Iphone X 15.3.1 having the same problem

**Comment by itsnebulalol** [comment]
This will be fixed when we switch to RELEASE kernels. You can manually replace wifi firmware if you want, but no help will be provided from me.

**Comment by lnguyen234** [comment]
Do you have an idea of when you switch to the release kernels? Thanks

**Comment by AmadeusPro** [comment]
> This will be fixed when we switch to RELEASE kernels. You can manually replace wifi firmware if you want, but no help will be provided from me.

Why are apps downloaded from the store flashed back?

**Comment by itsnebulalol** [comment]
> Do you have an idea of when you switch to the release kernels? Thanks

No, no eta

> Why are apps downloaded from the store flashed back?

Same issue, also it says this in the readme
