### ISSUE TITLE
creating socket for listen port 2222: Address in use (Im on ArchLinux)

### ISSUE THREAD

**Issue by ezitounioussama** [palera1n/palera1n#117]
main: Starting...
main: Detected fat macho kernel
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-8019 inputted
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x99e99c
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x1119c7c
get_amfi_out_of_my_way_patch: Patching AMFI at 0x11152d8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
none
none
[*] Booting ramdisk
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:0C ECID:000C515620F01526 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Device should now show text on screen
[*] Waiting for the ramdisk to finish booting
Creating listening port 2222 for device port 22
bind(): Address in use
Error creating socket for listen port 2222: Address in use

**Comment by grunkyb** [comment]
Try
`sudo lsof -i :2222`
Then kill the process identified. (I'm not sure if this is the same on ArchLinux as my flavor.)

**Comment by ezitounioussama** [comment]
@grunkyb It works thank you
