### ISSUE TITLE
Tips app is broken

### ISSUE THREAD

**Issue by danni551** [palera1n/palera1n#119]
Every time I run the script for tweaks it boots up but System Apps such as Settings are crashing, and now the Tips app is broken and can't be deleted I already tried to delete the tips folder with Filza but it didn't delete, I think AMfi patch messed system apps up.I am using an iPhone 7 GSM on iOS 15.0.2

**Comment by limneos** [comment]
Had the same issue, tried to delete Tips.app as well but wasn't getting deleted nor offloaded. 

I eventually fixed it by creating an empty tips.app (com.apple.tips) in Xcode, compiled it, grabbed the .app from DerivedData, edited Info.plist to make sure it's "Tips" and not "tips" , installing it as an IPA with TrollStore, and then deleting it from TrollStore. I could then re-download Tips.app from the App Store.
