### ISSUE TITLE
[Feature request] Make palera1n semi-tethered

### ISSUE THREAD

**Issue by Halo-Michael** [palera1n/palera1n#120]
Okey, as the title, but basically I'm here to give ways, not just suggest
There are some steps to make palera1n semi-tethered:
1. Create a partition: `newfs_apfs -A -v System -e /dev/disk0s1`, that will be disk0s1s8
2. Copy root file system to disk0s1s8
3. add rd=disk0s1s8 to boot-args

So, when I'm not boot with palera1n, my rootfs normal and sealed so I can boot as unjailbroken. And when I boot with palera1n, iBoot will read my boot-args and mount disk0s1s8 as rootfs, so it's jailbroken.
https://twitter.com/halo_michael/status/1578068162691883008?s=20&t=s_nl94WiFwpGdS1krl7-EQ
The only problem is that on my iPhone 7 this will cause TouchID not work.
Have fun!

**Comment by Shaneee** [comment]
Seems like a good idea. How would you go about copying the root fs to the new partition though?

**Comment by edwin170** [comment]
with ssh with ramdisk and you can have access to root and after you can create a second partition which you cp root to second

**Comment by edwin170** [comment]
> Okey, as the title, but basically I'm here to give ways, not just suggest There are some steps to make palera1n semi-tethered:
> 
> 1. Create a partition: `newfs_apfs -A -v System -e /dev/disk0s1`, that will be disk0s1s8
> 2. Copy root file system to disk0s1s8
> 3. add rd=disk0s1s8 to boot-args
> 
> So, when I'm not boot with palera1n, my rootfs normal and sealed so I can boot as unjailbroken. And when I boot with palera1n, iBoot will read my boot-args and mount disk0s1s8 as rootfs, so it's jailbroken. https://twitter.com/halo_michael/status/1578068162691883008?s=20&t=s_nl94WiFwpGdS1krl7-EQ The only problem is that on my iPhone 7 this will cause TouchID not work. Have fun!

hey my bro, it is a good idea and I try to dualboot my phone ios 15.7 with a second os 14.2. for me is very good because if you want ios 14 you can boot your second os also jailbreak. i tried now but i am stuck when I booted my second os say that 
![stuckDualboot](https://user-images.githubusercontent.com/85508740/194778866-2bc0963f-8091-49ea-9474-a563b860e8b9.png)

failed to load kernel prng seed 

if you know what can be the problem please tell me

**Comment by HoangLong-Lumi** [comment]
same idea with dora2ios
and he uses it for his jb

**Comment by itsnebulalol** [comment]
> Seems like a good idea. How would you go about copying the root fs to the new partition though?

In a ramdisk, `cp -Rp /mnt1 /mnt8`, replace /mnt8 with the path of the mounted disk
