### ISSUE TITLE
BuildManifest.Error: file AssetData/boot/BuildManifest.plist does not exist, or is a directory

### ISSUE THREAD

**Issue by pwnd2e** [palera1n/palera1n#121]
[*] Downloading BuildManifest
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-63899/6CAB53E5-5411-4140-BA83-0E37B1397558/iPhone10,3,iPhone10,6_15.1_19B74_Restore.ipsw
init done
Error: file AssetData/boot/BuildManifest.plist does not exist, or is a directory

**Comment by EchoSkill** [comment]
what MacOs Version are you using?, pzb binary is not working properly and is causing this...

**Comment by Mrubeh** [comment]
i have the same problem
iphone 6s plus
ios 15.7
kali linux

**Comment by pwnd2e** [comment]
Figured it out

**Comment by ezitounioussama** [comment]
you try ./palera1n.sh clean ?

**Comment by itsnebulalol** [comment]
Fixed in latest commit
