### ISSUE TITLE
Error init failed  

### ISSUE THREAD

**Issue by xz1c** [palera1n/palera1n#122]
Error init failed

**Info (please complete the following information):**
- iphoneSE iOS 15.4.1
- Bigsur11.6
- ./palera1n.sh --tweaks 15.4.1

**Additional context**
Found the USB handle.
Now you can boot untrusted images.
[*] Converting blob
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
Saved IM4M to work/IM4M
[*] Downloading BuildManifest
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: 
Error init failed
[13:25:14-2022-10-07-Darwin-20.6.0.log](https://github.com/palera1n/palera1n/files/9730932/13.25.14-2022-10-07-Darwin-20.6.0.log)

**Comment by EchoSkill** [comment]
what MacOs Version are you using?, pzb binary is not working properly and is causing this...

**Comment by itsnebulalol** [comment]
> what MacOs Version are you using?, pzb binary is not working properly and is causing this...

That's not the issue. First of all, they put their version, second, it's working fine.

Anyway, @xz1c, if you read the readme, tweaks don't work on 15.4.1 yet.
