### ISSUE TITLE
after "Creating ramdisk", nothing happens and my phone reboots.

### ISSUE THREAD

**Issue by siwoo1107** [palera1n/palera1n#123]
<img width="682" alt="스크린샷 2022-10-07 오후 4 30 27" src="https://user-images.githubusercontent.com/46241716/194498181-035b10e4-f407-4c3a-a1ed-b3e11eb5c007.png">
**Describe the bug**

I ran the command "cd palera1n" - phone in DFU mode - "./palera1n.sh --tweaks 15.1 --debug",
and my phone just reboots. I did the cloning. I do not know why this problem happens. I saw people with same problems, but I cannot find the solution.. Help please.

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
- iDevice's version: iOS 15.1, iPhone 7 Plus
- Computer OS and version: [macOS 12.5.1]
- The command you ran: [`./palera1n.sh --tweaks 15.1 --debug`]

**Comment by itsnebulalol** [comment]
`git pull` and try again, without the --debug

**Comment by siwoo1107** [comment]
<img width="682" alt="스크린샷 2022-10-09 오후 8 10 42" src="https://user-images.githubusercontent.com/46241716/194753794-eab53e87-3836-4a01-aaec-23d7c2965a7d.png">

still not working TT
