### ISSUE TITLE
 WASTING TIME AFTER BOOTING RAMDISK

### ISSUE THREAD

**Issue by aditya11110** [palera1n/palera1n#124]
YESTERDAY I OPENED ERROR OF BLOB VALIDATION,TODAY AFTER BOOTING RAMDISK IT STUCKS ,PLEASE BRING THE OLD VERSION OF PALERA1N BACK OR MAKE IT SEMI TETHERED 

BEFORE CLOSING MY CASE GIVE A REASON

**Comment by itsnebulalol** [comment]
Jesus christ, run `git pull` lmao

**Comment by aditya11110** [comment]
What to do of error tips is not installed
