### ISSUE TITLE
iPhone 6s plus stuck before installing Pogo

### ISSUE THREAD

**Issue by grunkyb** [palera1n/palera1n#125]
**Describe the bug**
Script is not proceeding after the `if` block and before the `while` block. Console reads `Error connecting to device: No such file or directory` repeatedly and does not proceed. Phone boots into non-JB OS.
```
    if ! ("$dir"/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no -p2222 root@localhost "echo connected" &> /dev/null); then
        echo "[*] Waiting for the ramdisk to finish booting"
    fi

    while ! ("$dir"/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no -p2222 root@localhost "echo connected" &> /dev/null); do
        sleep 1
    done
```

**Expected behavior**
Expected to see `echo "[*] Dumping blobs and installing Pogo"` in console and for script to continue.

**Info:**
- iDevice's version: iOS 15.1
- Computer OS and version: macOS 12.6
- The command you ran: `sudo ./palera1n.sh --tweaks 15.1 --debug`

**Additional context**
The "I'm here" in the log is a line I added to see where the script stopped working.

**Debug log**

[18:13:29-2022-10-06-Darwin-21.6.0.log](https://github.com/palera1n/palera1n/files/9733653/18.13.29-2022-10-06-Darwin-21.6.0.log)

**Comment by sirik92** [comment]
same issue ip6s+ 15.3.1 catalina 10.15.7

./palera1n.sh --dfu 15.3.1

??
