### ISSUE TITLE
repos not work

### ISSUE THREAD

**Issue by KRIEZIEY** [palera1n/palera1n#126]
In the mid step when i need to install openssh, newterm2 etc  repos not work they gves error:https/apt.procurus.us/dists/iphoneos-arm64-rootless/1800/Release returned status 404. and error coud not find release file for https/apt.procurus.us/dists/iphoneos-arm64-rootless/1800/

P.S. any repos not work not only this and i dont have problems with internet conection

**Comment by itsnebulalol** [comment]
What step are you on exactly? It says the repo to add if you’re on the wget curl and openssh step

**Comment by KRIEZIEY** [comment]
Yes on this step

**Comment by RABIEIO** [comment]
Try adding from Zebra Package Manager, because sileo only supports packages made for Arm64 devices only, let me know if you encounter an error with this

**Comment by itsnebulalol** [comment]
> Try adding from Zebra Package Manager, because sileo only supports packages made for Arm64 devices only, let me know if you encounter an error with this

What? This is completely unrelated and not true

> Yes on this step

Please add the repo mineek.github.io/repo
