### ISSUE TITLE
Nothing Showing Up

### ISSUE THREAD

**Issue by hawk603** [palera1n/palera1n#127]
Im on a 6s Plus running 15.5b4. don't know what's going on. It looked like everything worked fine, though, the tips app is still just the tips app with no pogo installed. Btw I'm not as skilled with some of the jailbreaking stuff as you all might be. This is just a secondary phone and I like messing around with jailbeaks and such. So if i don't know something simple that's why lol. Here is what was shown when I tried. ~ Thanks

hcndrxx@lildemon palera1n % ./palera1n.sh --debug
palera1n | Version 1.0.0-d8540c6
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

Hello, iPhone8,2 on 15.5!
[*] Switching device into recovery mode...
Telling device with udid 5890927222729868e34ce6b6f0831137c553a31c to enter recovery mode.
Device is successfully switching to recovery mode.
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Pwning device
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8003 CPRV:01 CPFM:03 SCEP:01 BDID:06 ECID:001925681050EC26 IBFL:1C SRTG:[iBoot-2234.0.0.2.22]
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8003 CPRV:01 CPFM:03 SCEP:01 BDID:06 ECID:001925681050EC26 IBFL:1C SRTG:[iBoot-2234.0.0.2.22]
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8003 CPRV:01 CPFM:03 SCEP:01 BDID:06 ECID:001925681050EC26 IBFL:1C SRTG:[iBoot-2234.0.0.2.22]
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8003 CPRV:01 CPFM:03 SCEP:01 BDID:06 ECID:001925681050EC26 IBFL:1C SRTG:[iBoot-2234.0.0.2.22] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[*] Booting device
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%

Done!
The device should now boot to iOS
If you already have ran palera1n, click Do All in the tools section of Pogo
If not, Pogo should be installed to Tips

**Comment by MissThee** [comment]
same. iphone8,4  15.7
