### ISSUE TITLE
Sileo Not Installed After Jailbreak...!

### ISSUE THREAD

**Issue by dharmeshbaskaran** [palera1n/palera1n#128]
[*] Patching and signing iBSS/iBEC
main: Starting...
iOS 15 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c3324 : 000080d2
applying patch=0x1800c3374 : 000080d2
applying patch=0x1800c4f38 : 200080d2
main: Writing out patched file to iBSS.patched...
main: Quitting...
main: Starting...
iOS 15 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c3324 : 000080d2
applying patch=0x1800c3374 : 000080d2
applying patch=0x1800c4f38 : 200080d2
main: Writing out patched file to iBEC.patched...
main: Quitting...
none
none
[*] Patching and signing kernelcache
krnl
[*] Signing DeviceTree
dtre
[*] Patching and signing trustcache
trst
none
[*] Booting device
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Tweaks enabled, running postinstall.
[!] Please install OpenSSH, curl, and wget from Sileo (repo is mineek.github.io/repo). Then, press any key to continue

As you can you see above, jailbreak is done completely. But I don't see Sileo pre installed in the device. I need help, what should be done further in order to see sileo or cydia in the device?

**Comment by Evoal** [comment]
Did u check Tips app?

**Comment by dharmeshbaskaran** [comment]
@Evoal I didn't get you, Sileo will be found inside Tips app?

**Comment by RABIEIO** [comment]
Just open the tips app and install sileo, if it doesn't show anything, install pogo From IPA File then try to install sileo

**Comment by Evoal** [comment]
> @Evoal I didn't get you, Sileo will be found inside Tips app?

![11B6E5BA-F104-4B54-A8A4-F11E77AC270C](https://user-images.githubusercontent.com/78671036/194717717-15c3ad75-beb4-432a-b44a-595b9a0be15c.png)

**Comment by dharmeshbaskaran** [comment]
Thanks for the help. When I tapped on Tips app I didn't see any pogo app. So I downloaded IPA separately from nightly link site. I signed the app and installed in iOS 15.1. When I tap Tools>Do All nothing works, and also I tapped install it says "Error installing Bootstrap -1"

**Comment by ezitounioussama** [comment]
how you install sileo ? the same error happends to me (when I open tips nothings shows up to me just the tips of ios !!)

**Comment by ezitounioussama** [comment]
same error any fixes ?????????

**Comment by edwin170** [comment]
try to use [sshrd](https://github.com/verygenericname/SSHRD_Script) and use that command ./sshrd.sh $(yourversionIOS) TrollStore TV after that you use palera1n to install pogo and boot, after that open TV and install ldid and trollstore when trollstore is installed you need to download pogo ipa https://nightly.link/elihwyma/Pogo/workflows/build/main/Pogo.zip and install it with trollstore

**Comment by dharmeshbaskaran** [comment]
Hey @edwin170 Thanks for the suggestion. I tried your method. I used SSHRD trying to install TrollStore TV, still nothing I can see and also I tried same process of palera1n, still no luck. 

![IMG_0001](https://user-images.githubusercontent.com/32505380/194772922-f9cb8858-5d55-4488-98b7-ff96644136bf.jpg)

**Comment by dharmeshbaskaran** [comment]
Hey @edwin170 thanks for the solution. I fixed it and working fine now. It's not because of trollstore, I had to reinstall palera1n again.

**Comment by ezitounioussama** [comment]
> Hey @edwin170 thanks for the solution. I fixed it and working fine now. It's not because of trollstore, I had to reinstall palera1n again.

Sileo works ?
