### ISSUE TITLE
Ramdisk issue?

### ISSUE THREAD

**Issue by manopachona** [palera1n/palera1n#129]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
- iDevice's version: [e.g. iOS 15.2, iOS 15.1]
- Computer OS and version: [e.g. macOS 13.0b3, Ubuntu 22.04]
- The command you ran: [e.g. `./palera1n.sh --dfu 15.1`]

**Additional context**

**Debug log**
Please run the script using `--debug` and send a log **inside** the backticks below.
```

```

**Comment by guacaplushy** [comment]
try sudo 
and actually fill the issue template out instead of making the title an abomination

**Comment by itsnebulalol** [comment]
> Palera1n issue: as I’m going through the process to jailbreak my iPad Pro 1st generation 9.7 inch  using Ubuntu  palera1n has trouble reading  my shsh files from the RAM disk. how can I overcome this issue and jailbreak my device.  I can’t install troll store because of this issue. Please help. I want to have palera1n work with my  iPad  my iPad is on iOS 15.2 the command I used ./palera1n.sh —tweaks 15.2

The title says this, I cannot even understand what this means.
