### ISSUE TITLE
SSHRD issue

### ISSUE THREAD

**Issue by manopachona** [palera1n/palera1n#130]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
- iDevice's version: [e.g. iOS 15.2, iOS 15.1]
- Computer OS and version: [e.g. macOS 13.0b3, Ubuntu 22.04]
- The command you ran: [e.g. `./palera1n.sh --dfu 15.1`]

**Additional context**

**Debug log**
Please run the script using `--debug` and send a log **inside** the backticks below.
```

```

**Comment by guacaplushy** [comment]
wrong repo
