### ISSUE TITLE
SILEO ERRORS !!!!!!

### ISSUE THREAD

**Issue by ezitounioussama** [palera1n/palera1n#132]
I installed sileo with pogo from TrollStore after jailbreak 

![A82B8EBF-45DA-40DC-809E-F1A513C64648](https://user-images.githubusercontent.com/81237441/194728870-f4c5631e-4bdf-4587-ab2b-1f9ffd1943d8.png)

**Comment by RavanGami** [comment]
![image](https://user-images.githubusercontent.com/114746710/194776883-4c27c552-006a-4653-807a-cf7e5e16b41d.png)

**Comment by RavanGami** [comment]
help

**Comment by RavanGami** [comment]
iphone 8 plus

**Comment by ezitounioussama** [comment]
Bro i installed trollstore from here https://github.com/opa334/TrollStore

**Comment by ezitounioussama** [comment]
You need a mac or linux

**Comment by ezitounioussama** [comment]
Or you can just download the ipa and signed with AltStore form windows or mac and it will work

**Comment by mreser99** [comment]
> I installed sileo with pogo from TrollStore after jailbreak
> 
> ![A82B8EBF-45DA-40DC-809E-F1A513C64648](https://user-images.githubusercontent.com/81237441/194728870-f4c5631e-4bdf-4587-ab2b-1f9ffd1943d8.png)

How did you make wifi work? I couldn't make it.
