### ISSUE TITLE
ERROR: Unable to connect to device [-] An error occurred

### ISSUE THREAD

**Issue by neizvedaniydag** [palera1n/palera1n#134]
[10:28:46-2022-10-09-Darwin-21.6.0.log](https://github.com/palera1n/palera1n/files/9740983/10.28.46-2022-10-09-Darwin-21.6.0.log)

**Comment by neizvedaniydag** [comment]
download succeeded
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:0A ECID:000651DE38F38F26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:0A ECID:000651DE38F38F26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 15 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c0d7c : 000080d2
applying patch=0x1800c0dc4 : 000080d2
applying patch=0x1800c29b4 : 200080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 15 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1  ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c0d7c : 000080d2
applying patch=0x1800c0dc4 : 000080d2
applying patch=0x1800b1f88 : 000080d2c0035fd6
applying patch=0x1800b1fe0 : 000080d2c0035fd6
applying patch=0x1800ee5a8 : 000080d2c0035fd6
applying patch=0x1800c29b4 : 200080d2
applying patch=0x1800c3fc8 : 58330b50
applying patch=0x1800da632 : 72643d6d64302064656275673d30783230313465202d76207764743d2d31202000
applying patch=0x1800c832c : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
main: Detected fat macho kernel
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-8020 inputted
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x9ab13a
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x10a4c64
get_amfi_out_of_my_way_patch: Patching AMFI at 0x10a02a8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
/dev/disk4          	                               	/private/tmp/SSHRD
"disk4" ejected.
none
none
[*] Booting ramdisk
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:0A ECID:000651DE38F38F26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.

[=                                                 ] 0.4%
[=                                                 ] 0.7%
[=                                                 ] 1.1%
[=                                                 ] 1.5%
[=                                                 ] 1.8%
[==                                                ] 2.2%
[==                                                ] 2.6%
[==                                                ] 3.0%
[==                                                ] 3.3%
[==                                                ] 3.7%
[===                                               ] 4.1%
[===                                               ] 4.4%
[===                                               ] 4.8%
[===                                               ] 5.2%
[===                                               ] 5.5%
[===                                               ] 5.9%
[====                                              ] 6.3%
[====                                              ] 6.6%
[====                                              ] 7.0%
[====                                              ] 7.4%
[====                                              ] 7.8%
[=====                                             ] 8.1%
[=====                                             ] 8.5%
[=====                                             ] 8.9%
[=====                                             ] 9.2%
[=====                                             ] 9.6%
[=====                                             ] 10.0%
[======                                            ] 10.3%
[======                                            ] 10.7%
[======                                            ] 11.1%
[======                                            ] 11.4%
[======                                            ] 11.8%
[=======                                           ] 12.2%
[=======                                           ] 12.6%
[=======                                           ] 12.9%
[=======                                           ] 13.3%
[=======                                           ] 13.7%
[========                                          ] 14.0%
[========                                          ] 14.4%
[========                                          ] 14.8%
[========                                          ] 15.1%
[========                                          ] 15.5%
[========                                          ] 15.9%
[=========                                         ] 16.2%
[=========                                         ] 16.6%
[=========                                         ] 17.0%
[=========                                         ] 17.4%
[=========                                         ] 17.7%
[==========                                        ] 18.1%
[==========                                        ] 18.5%
[==========                                        ] 18.8%
[==========                                        ] 19.2%
[==========                                        ] 19.6%
[==========                                        ] 19.9%
[===========                                       ] 20.3%
[===========                                       ] 20.7%
[===========                                       ] 21.0%
[===========                                       ] 21.4%
[===========                                       ] 21.8%
[============                                      ] 22.2%
[============                                      ] 22.5%
[============                                      ] 22.9%
[============                                      ] 23.3%
[============                                      ] 23.6%
[=============                                     ] 24.0%
[=============                                     ] 24.4%
[=============                                     ] 24.7%
[=============                                     ] 25.1%
[=============                                     ] 25.5%
[=============                                     ] 25.8%
[==============                                    ] 26.2%
[==============                                    ] 26.6%
[==============                                    ] 27.0%
[==============                                    ] 27.3%
[==============                                    ] 27.7%
[===============                                   ] 28.1%
[===============                                   ] 28.4%
[===============                                   ] 28.8%
[===============                                   ] 29.2%
[===============                                   ] 29.5%
[===============                                   ] 29.9%
[================                                  ] 30.3%
[================                                  ] 30.6%
[================                                  ] 31.0%
[================                                  ] 31.4%
[================                                  ] 31.8%
[=================                                 ] 32.1%
[=================                                 ] 32.5%
[=================                                 ] 32.9%
[=================                                 ] 33.2%
[=================                                 ] 33.6%
[=================                                 ] 34.0%
[==================                                ] 34.3%
[==================                                ] 34.7%
[==================                                ] 35.1%
[==================                                ] 35.4%
[==================                                ] 35.8%
[===================                               ] 36.2%
[===================                               ] 36.6%
[===================                               ] 36.9%
[===================                               ] 37.3%
[===================                               ] 37.7%
[====================                              ] 38.0%
[====================                              ] 38.4%
[====================                              ] 38.8%
[====================                              ] 39.1%
[====================                              ] 39.5%
[====================                              ] 39.9%
[=====================                             ] 40.2%
[=====================                             ] 40.6%
[=====================                             ] 41.0%
[=====================                             ] 41.4%
[=====================                             ] 41.7%
[======================                            ] 42.1%
[======================                            ] 42.5%
[======================                            ] 42.8%
[======================                            ] 43.2%
[======================                            ] 43.6%
[======================                            ] 43.9%
[=======================                           ] 44.3%
[=======================                           ] 44.7%
[=======================                           ] 45.0%
[=======================                           ] 45.4%
[=======================                           ] 45.8%
[========================                          ] 46.2%
[========================                          ] 46.5%
[========================                          ] 46.9%
[========================                          ] 47.3%
[========================                          ] 47.6%
[=========================                         ] 48.0%
[=========================                         ] 48.4%
[=========================                         ] 48.7%
[=========================                         ] 49.1%
[=========================                         ] 49.5%
[=========================                         ] 49.9%
[==========================                        ] 50.2%
[==========================                        ] 50.6%
[==========================                        ] 51.0%
[==========================                        ] 51.3%
[==========================                        ] 51.7%
[===========================                       ] 52.1%
[===========================                       ] 52.4%
[===========================                       ] 52.8%
[===========================                       ] 53.2%
[===========================                       ] 53.5%
[===========================                       ] 53.9%
[============================                      ] 54.3%
[============================                      ] 54.7%
[============================                      ] 55.0%
[============================                      ] 55.4%
[============================                      ] 55.8%
[=============================                     ] 56.1%
[=============================                     ] 56.5%
[=============================                     ] 56.9%
[=============================                     ] 57.2%
[=============================                     ] 57.6%
[=============================                     ] 58.0%
[==============================                    ] 58.3%
[==============================                    ] 58.7%
[==============================                    ] 59.1%
[==============================                    ] 59.5%
[==============================                    ] 59.8%
[===============================                   ] 60.2%
[===============================                   ] 60.6%
[===============================                   ] 60.9%
[===============================                   ] 61.3%
[===============================                   ] 61.7%
[================================                  ] 62.0%
[================================                  ] 62.4%
[================================                  ] 62.8%
[================================                  ] 63.1%
[================================                  ] 63.5%
[================================                  ] 63.9%
[=================================                 ] 64.3%
[=================================                 ] 64.6%
[=================================                 ] 65.0%
[=================================                 ] 65.4%
[=================================                 ] 65.7%
[==================================                ] 66.1%
[==================================                ] 66.5%
[==================================                ] 66.8%
[==================================                ] 67.2%
[==================================                ] 67.6%
[==================================                ] 67.9%
[===================================               ] 68.3%
[===================================               ] 68.7%
[===================================               ] 69.1%
[===================================               ] 69.4%
[===================================               ] 69.8%
[====================================              ] 70.2%
[====================================              ] 70.5%
[====================================              ] 70.9%
[====================================              ] 71.3%
[====================================              ] 71.6%
[=====================================             ] 72.0%
[=====================================             ] 72.4%
[=====================================             ] 72.7%
[=====================================             ] 73.1%
[=====================================             ] 73.5%
[=====================================             ] 73.9%
[======================================            ] 74.2%
[======================================            ] 74.6%
[======================================            ] 75.0%
[======================================            ] 75.3%
[======================================            ] 75.7%
[=======================================           ] 76.1%
[=======================================           ] 76.4%
[=======================================           ] 76.8%
[=======================================           ] 77.2%
[=======================================           ] 77.5%
[=======================================           ] 77.9%
[========================================          ] 78.3%
[========================================          ] 78.7%
[========================================          ] 79.0%
[========================================          ] 79.4%
[========================================          ] 79.8%
[=========================================         ] 80.1%
[=========================================         ] 80.5%
[=========================================         ] 80.9%
[=========================================         ] 81.2%
[=========================================         ] 81.6%
[=========================================         ] 82.0%
[==========================================        ] 82.3%
[==========================================        ] 82.7%
[==========================================        ] 83.1%
[==========================================        ] 83.5%
[==========================================        ] 83.8%
[===========================================       ] 84.2%
[===========================================       ] 84.6%
[===========================================       ] 84.9%
[===========================================       ] 85.3%
[===========================================       ] 85.7%
[============================================      ] 86.0%
[============================================      ] 86.4%
[============================================      ] 86.8%
[============================================      ] 87.1%
[============================================      ] 87.5%
[============================================      ] 87.9%
[=============================================     ] 88.3%
[=============================================     ] 88.6%
[=============================================     ] 89.0%
[=============================================     ] 89.4%
[=============================================     ] 89.7%
[==============================================    ] 90.1%
[==============================================    ] 90.5%
[==============================================    ] 90.8%
[==============================================    ] 91.2%
[==============================================    ] 91.6%
[==============================================    ] 91.9%
[===============================================   ] 92.3%
[===============================================   ] 92.7%
[===============================================   ] 93.1%
[===============================================   ] 93.4%
[===============================================   ] 93.8%
[================================================  ] 94.2%
[================================================  ] 94.5%
[================================================  ] 94.9%
[================================================  ] 95.3%
[================================================  ] 95.6%
[================================================= ] 96.0%
[================================================= ] 96.4%
[================================================= ] 96.7%
[================================================= ] 97.1%
[================================================= ] 97.5%
[================================================= ] 97.9%
[==================================================] 98.2%
[==================================================] 98.6%
[==================================================] 99.0%
[==================================================] 99.3%
[==================================================] 99.7%
[==================================================] 100.0%
[-] An error occurred

**Comment by tw1nkl3** [comment]
same

**Comment by RavanGami** [comment]
Unable to connect to device [-] An error occurred

**Comment by itsnebulalol** [comment]
If on linux, use sudo

**Comment by neizvedaniydag** [comment]
Doesn’t work 

> If on linux, use sudo
