### ISSUE TITLE
Stuck on Getting device info.. This may take a second

### ISSUE THREAD

**Issue by masckmaster2007** [palera1n/palera1n#136]
sudo bash ./palera1n.sh --dfu --debug '/path/to/blob.shsh2' 15.7
Ubuntu 22.04
iOS 15.7 iPhone 7 GSM
Using the rootless branch

**Comment by masckmaster2007** [comment]
Now i get a sEgmENtaTIOn FauLT
`palera1n | Version 1.0.0-d8540c6
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
ERROR: Unable to connect to device
[*] Creating ramdisk
[*] Getting device info... this may take a second
Segmentation fault (core dumped)
[-] An error occurred
`

**Comment by neizvedaniydag** [comment]
have you solved this problem?

**Comment by masckmaster2007** [comment]
no?
