### ISSUE TITLE
first stuck on "Successfully complited" then on "Creating ramdisk"

### ISSUE THREAD

**Issue by tw1nkl3** [palera1n/palera1n#138]
**Describe the bug**
Everythong was ok, but after some complited actions it stuck on "Successfully complited", then my iphone turned on and thats all. When I try again, stuck on "Creating ramdisk" and phone turns on.

**Info (please complete the following information):**
- iDevice's version: iOS 15.2
- Computer OS and version: Ubuntu 22.04
- The command you ran: sudo bash ./palera1n.sh --tweaks 15.2

**Comment by tw1nkl3** [comment]
If i delete repo from my pc and "reclone" it: now it goes though "Creating ramdisk" and stuck on "inflating gaster" and my phone turns on

**Comment by demhademha** [comment]
What was the solution, as I am encountering the same issue (iPadOS 15.3.1 iPad 7th gen
