### ISSUE TITLE
[FIXED] iPhone 8 | 15.1 | Bug

### ISSUE THREAD

**Issue by KhaledCP** [palera1n/palera1n#140]
**Describe the bug**
When the device is idle or in sleep mode the device panics.

**Expected behavior**
I expected for the jailbreak to work instead the device panics.

**Screenshots**
No screenshots.

**Info:**
- iDevice's version: 15.1
- Computer OS and version: macOS 12.5.1
- Command ran: ./palera1n.sh --tweaks 15.1

**Additional context**
None.

**Debug log**
No logs are needed because the device is already jailbroken.

**Comment by KhaledCP** [comment]
# **I updated to 1.1.1 palera1n now the issue is fixed!**

**Comment by RavanGami** [comment]
unbale to conect device

**Comment by RavanGami** [comment]
![Uploading 194777246...]

**Comment by RavanGami** [comment]
![image](https://user-images.githubusercontent.com/114746710/194777281-99618c39-ef72-450e-8bea-c26983052c9e.jpeg)

**Comment by RavanGami** [comment]
![image](https://user-images.githubusercontent.com/114746710/194777380-579a8259-2735-4a31-b7d5-ccad45b74194.jpeg)

**Comment by mineLdiver** [comment]
> unbale to conect device

This is NOT a palera1n issue + create your own one instead of commenting under other ones

**Comment by verygenericname** [comment]
please bro, make this issue under MY REPO

**Comment by KhaledCP** [comment]
# **Just install iNoSleep tweak then the issue should be fixed.**
