### ISSUE TITLE
SSH Default Password - alpine is not working

### ISSUE THREAD

**Issue by dharmeshbaskaran** [palera1n/palera1n#141]
Device Info: iPhone 7 - iOS 15.1

When I tried to connect my iPhone via SSH, the default password "alpine" is not working. So I couldn't able to connect my device via SSH.

Here is the SC:

<img width="460" alt="alpinepassword" src="https://user-images.githubusercontent.com/32505380/194778635-b591793e-9e7e-439b-8dce-7fed8fde01a5.png">

**Comment by edwin170** [comment]
jajajja my friend root not work so you need to put ssh mobile@192.168.1.15

**Comment by dharmeshbaskaran** [comment]
WOW!! Thanks @edwin170 it worked finally hahaha..! Can you able to add any other repos or only mineek repo works here?

**Comment by edwin170** [comment]
i think only mineek for now

**Comment by edwin170** [comment]
and only repo rootless

**Comment by edwin170** [comment]
hey, have you ever tested dual boot on iPhone ?

**Comment by Foxtrod89** [comment]
where is _sshd_config_ located?
