### ISSUE TITLE
Stuck on creating ramdisk.

### ISSUE THREAD

**Issue by DeveloLongScript** [palera1n/palera1n#150]
So basically its stuck on the creating ramdisk step, and then after a while the device boots back up.

Heres a screenshot of my terminal:
![Screen Shot 2022-10-11 at 7 46 27 PM](https://user-images.githubusercontent.com/52332868/195223811-d20111fb-1931-4a3e-86a2-7ac224a45911.png)

The only reason I quit out of it is because its doing that same step for infinity.

I am using MacOS Monterey (version 12.4)
My device is running iPadOS 15.1
My device is a iPad 6th generation.

**Comment by kristenlc** [comment]
I am genuinely confused as to why there is no debug on your screen when [b96cea7d4](https://github.com/palera1n/palera1n/commit/c5b949ed394f4a924139e9395404e14b96cea7d4) made debug happen at all time. I can only wager that it is because of all the >/dev/null lines in the script.

Either way, your issue is caused by an error that can not be seen on your terminal because it is hidden. You need to check to make sure python3 is installed, pyimg4 module is installed, your device is in dfu mode, you have a working internet connection, and restart your computer and try again.

**Comment by kristenlc** [comment]
I need you to also run git pull in the terminal from within the directory that contains the script file to make sure you are using the latest version, they recently did some patches for some ipads

**Comment by DeveloLongScript** [comment]
okay well look
![Screen Shot 2022-10-14 at 6 13 36 PM](https://user-images.githubusercontent.com/52332868/195956447-8d369a26-9ee1-450f-9db7-8e9927c04862.png)
it says the device entered dfu mode

but at this point i dont know
![Screen Shot 2022-10-14 at 6 17 20 PM](https://user-images.githubusercontent.com/52332868/195956683-dd4d5aeb-1f19-4650-953d-28bc68488ef7.png)

**Comment by DeveloLongScript** [comment]
although hold on let me git pull real quick

**Comment by kristenlc** [comment]
> okay well look ![Screen Shot 2022-10-14 at 6 13 36 PM](https://user-images.githubusercontent.com/52332868/195956447-8d369a26-9ee1-450f-9db7-8e9927c04862.png) it says the device entered dfu mode

So the command it is stuck on is a `tee` command, you can tell by the window title

**Comment by kristenlc** [comment]
Do you have a log file in the directory `logs`

**Comment by DeveloLongScript** [comment]
[logs.zip](https://github.com/palera1n/palera1n/files/9790746/logs.zip)
yes i do, and here it is, also this is a screenshot after git pull
![Screen Shot 2022-10-14 at 6 50 22 PM](https://user-images.githubusercontent.com/52332868/195958680-e020374c-cecb-4e90-b6e5-50af597f0fd8.png)

**Comment by DeveloLongScript** [comment]
no new progress
:(

**Comment by kristenlc** [comment]
is your ipad the wifi only or cellular+wifi varient

**Comment by kristenlc** [comment]
https://github.com/palera1n/ramdisk/blob/5f43f7856978f0c1081173f416280ea8b9788617/sshrd.sh#L47
change this line in `sshrd.sh` in the `ramdisk` directory to be
`ipswurl=https://updates.cdn-apple.com/2022FallFCS/fullrestores/012-38966/80B885FC-7186-4C64-9E7F-4DA8F1A7E12C/iPad_64bit_TouchID_ASTC_15.7_19H12_Restore.ipsw`

**Comment by kristenlc** [comment]
https://github.com/palera1n/palera1n/blob/tweaks/palera1n.sh#L13
change this line in `palera1n.sh` in the main directory to be
`ipsw="https://updates.cdn-apple.com/2022FallFCS/fullrestores/012-38966/80B885FC-7186-4C64-9E7F-4DA8F1A7E12C/iPad_64bit_TouchID_ASTC_15.7_19H12_Restore.ipsw"`

**Comment by kristenlc** [comment]
the creating ramdisk step can take up to 10 minutes with a slow wifi connection, give it time and follow the above steps and try again

**Comment by DeveloLongScript** [comment]
my ipad is wifi varient, i have waited for 4 hours+ on ethernet i will try your soulitions after i shower :)

**Comment by DeveloLongScript** [comment]
![Screen Shot 2022-10-16 at 10 43 09 AM](https://user-images.githubusercontent.com/52332868/196044564-7f2e6697-f7b2-46a8-bffc-e8cf729a84aa.png)
![Screen Shot 2022-10-16 at 10 43 37 AM](https://user-images.githubusercontent.com/52332868/196044601-ef614718-dc81-4083-8b69-fac77baa32eb.png)

waited 8+ minutes

**Comment by itsnebulalol** [comment]
It’s gaster failing to run. Please pwn manually with `binaries/Darwin/gaster pwn` and send the output

**Comment by DeveloLongScript** [comment]
![Screen Shot 2022-10-18 at 4 33 20 PM](https://user-images.githubusercontent.com/52332868/196549113-75cef842-532a-43b0-8016-f412622c6af0.png)

**Comment by demhademha** [comment]
After getting the device info, the program begins to create the ram disk. At this point, the device will either reboot to normal mode or recovery mode. 
Manually forcing the device back to DFU causes it to enter the patch phase (it seems that the device immediately leaves DFU as soon as the ram disk is being created).
Device: iPad7 Wi-Fi 15.3.1

**Comment by DeveloLongScript** [comment]
so how to fix this?
