### ISSUE TITLE
Libhooker…

### ISSUE THREAD

**Issue by KingStoners** [palera1n/palera1n#153]
iPhone 7 15.1 Tried installing libhooker like a idiot… device seems to work ok after forcing it out of recovery however…. Upon trying the install script again (on Linux) it boots the device but after the verbose screen it give off a load of errors and boots into a jailbroken state but you can’t install anything and the install script   doesn’t install substitute on the device.

**Comment by KingStoners** [comment]
It gets to the point where you add the repo to get open ssh/wget/curl but the terminal on Linux gives error messages. Substitute isn’t installed.

**Comment by RealKGB** [comment]
unrename snapshot to undo all changes, then re jailbreak and install substitute.

**Comment by KingStoners** [comment]
how do I “unrename” the snapshot?

**Comment by RealKGB** [comment]
I don't remember the process exactly but follow the steps to remove the palera1n tether - so you can go back to stock iOS. palera1n discord can help you out
