### ISSUE TITLE
iPhone7 15.2 bug

### ISSUE THREAD

**Issue by LiuZeyu1119** [palera1n/palera1n#158]
My iPhone 7 used futurestore, downgraded from 15.5 to 15.2
As the video, it black screen in the boot state after jailbreak

https://user-images.githubusercontent.com/30873854/196039328-34e74cb3-e8aa-41e3-8ba4-3033801f8b04.mov

**Comment by kristenlc** [comment]
did you downgrade with blobs, or without blobs. cause if you downgraded without blobs then the iphone requires patching the bootchain in order to boot the new ios version cause it is not allowed by default and i do not know if palera1n does those patches for you

**Comment by kristenlc** [comment]
are you even able to boot ios 15.2 in the first place without palera1n cause i do not even know if ios 15.7 is still signed and i do not think ios 16 sep is compatible with ios 15.2 for downgrade

**Comment by LiuZeyu1119** [comment]
I downgraded with blobs

**Comment by LiuZeyu1119** [comment]
I don't know much English. Do you mean that I can start without palera1n?After a forced restart, it can be started normally, but the Tips will crash.

**Comment by asdfugil** [comment]
you must start with palera1n

**Comment by zenos3000** [comment]
How?

**Comment by kristenlc** [comment]
turn off your passcode and then try palera1n, you can not have your passcode set when you are using palera1n

**Comment by LiuZeyu1119** [comment]
Thank you. The problem is solved. I didn't turn off my passcode.
