### ISSUE TITLE
curl error on Pogo.zip & Pogo.zip only has an .IPA file in it

### ISSUE THREAD

**Issue by smitben59** [palera1n/palera1n#159]
**Describe the bug**
Script is looking for Pogo.app which doesn't exist in the zip file and the curl command doesn't work without saying no URL specified.

**Expected behavior**
Downloads and uses files in Pogo.zip

**Screenshots**

**Info (please complete the following information):**
- iDevice's version: 15.7
- Computer OS and version: MacOS 12.6
- The command you ran: palera1n.sh --tweaks 15.7 (I KNOW IT'S NOT SUPPORTED BUT I'VE ALMOST GOT IT WORKING)

**Additional context**
I think it's trying to extract the .ipa file but I'm not sure.

**Debug log**
Please run the script using `--debug` and send a log **inside** the backticks below.
after manually placing file:
```
cp: work/Pogo/Payload/Pogo.app: No such file or directory
```

**Comment by mineek** [comment]
```git pull```

**Comment by smitben59** [comment]
> @smitben59 you have lost your mind sir , you got nothing almost it wont work until mineek finishes the patch finder

I have a patchfinder, so either you can stop insulting me or I can pull a coolstar and y'all can wait xD

Anyway testing the fix now!

**Comment by smitben59** [comment]
> git pull

It worked, thanks!
Now all I gotta do is fix the get-task-allow then I'll boot!

**Comment by mineek** [comment]
@smitben59, if u want to, can u add me on Discord to discuss about the patchfinder?

Mineek#6323
