### ISSUE TITLE
Pogo issue

### ISSUE THREAD

**Issue by datsrt02** [palera1n/palera1n#161]
I Install Pogo success and Sileo too, but when i turn on passcode ( i turn off before for run palra1n) , i got black screen and must hard reset to reboot again, when reboot done, Pogo( Tips app ) crashed and Sileo too. I cant open it or do anything, i try again 2-3 times still got it.
Phone: 7 Plus GSM (9,4) , IOS 15.6 RC

**Comment by asdfugil** [comment]
passcode must not be enabled when booted from DFU mode

**Comment by datsrt02** [comment]
> passcode must not be enabled when booted from DFU mode, and it must stay that way until the device is rebooted

ok i got it, but i start from normal mode, not DFU

**Comment by asdfugil** [comment]
palera1n boots the device from DFU mode so you did boot from DFU mode

**Comment by datsrt02** [comment]
> palera1n boots the device from DFU mode so you did boot from DFU mode

yes, i try start from DFU mode, still got same issue, when i turn on passcode, bc i want to lock my phone , got black screen.

**Comment by asdfugil** [comment]
to lock your phone, reboot first

**Comment by datsrt02** [comment]
> to lock your phone, reboot first then do not jailbreak

:)

**Comment by datsrt02** [comment]
> to lock your phone, reboot first then do not jailbreak

so anytime if i turn back on passcode, rootless will gone right and i cant use pogo or trollstore right ?

**Comment by asdfugil** [comment]
yes
