### ISSUE TITLE
iphone x 15.5 tips app crash 

### ISSUE THREAD

**Issue by SuginGv30** [palera1n/palera1n#165]
buntu@ubuntu:~/Downloads/palera1n$ sudo bash ./palera1n.sh --debug
palera1n | Version 1.0.0-9219d27
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

Hello, iPhone10,3 on 15.5!
[*] Switching device into recovery mode...
Telling device with udid 1e3b6f049dcc520a99a6d0d02925f6b31033a3b1 to enter recovery mode.
Device is successfully switching to recovery mode.
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Pwning device
usb_timeout: 10
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8015
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8015
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8015
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8015
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8015
Found the USB handle.
Now you can boot untrusted images.
[*] Converting blob
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
Saved IM4M to work/IM4M
[*] Downloading BuildManifest
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022SpringFCS/fullrestores/012-08019/9B77837B-6568-45E6-8C0F-3BC5B952371B/iPhone10,3,iPhone10,6_15.5_19F77_Restore.ipsw
init done
getting: BuildManifest.plist
100% [===================================================================================================>]
download succeeded
[*] Downloading and decrypting iBSS
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022SpringFCS/fullrestores/012-08019/9B77837B-6568-45E6-8C0F-3BC5B952371B/iPhone10,3,iPhone10,6_15.5_19F77_Restore.ipsw
init done
getting: Firmware/dfu/iBSS.d22.RELEASE.im4p
100% [===================================================================================================>]
download succeeded
usb_timeout: 10
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8015
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[*] Downloading and decrypting iBEC
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022SpringFCS/fullrestores/012-08019/9B77837B-6568-45E6-8C0F-3BC5B952371B/iPhone10,3,iPhone10,6_15.5_19F77_Restore.ipsw
init done
getting: Firmware/dfu/iBEC.d22.RELEASE.im4p
100% [===================================================================================================>]
download succeeded
usb_timeout: 10
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8015
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[*] Downloading DeviceTree
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022SpringFCS/fullrestores/012-08019/9B77837B-6568-45E6-8C0F-3BC5B952371B/iPhone10,3,iPhone10,6_15.5_19F77_Restore.ipsw
init done
getting: Firmware/all_flash/DeviceTree.d22ap.im4p
100% [===================================================================================================>]
download succeeded
[*] Downloading AOP
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022SpringFCS/fullrestores/012-08019/9B77837B-6568-45E6-8C0F-3BC5B952371B/iPhone10,3,iPhone10,6_15.5_19F77_Restore.ipsw
init done
getting: Firmware/AOP/aopfw-iphone10baop.im4p
100% [===================================================================================================>]
download succeeded
[*] Downloading trustcache
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022SpringFCS/fullrestores/012-08019/9B77837B-6568-45E6-8C0F-3BC5B952371B/iPhone10,3,iPhone10,6_15.5_19F77_Restore.ipsw
init done
getting: Firmware/078-12315-101.dmg.trustcache
100% [===================================================================================================>]
download succeeded
[*] Downloading kernelcache
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022SpringFCS/fullrestores/012-08019/9B77837B-6568-45E6-8C0F-3BC5B952371B/iPhone10,3,iPhone10,6_15.5_19F77_Restore.ipsw
init done
getting: kernelcache.release.iphone10b
100% [===================================================================================================>]
download succeeded
[*] Patching and signing iBSS/iBEC
main: Starting...
iOS 15 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x180030ad0 : 000080d2
applying patch=0x180030b18 : 000080d2
applying patch=0x18003289c : 200080d2
main: Writing out patched file to iBSS.patched...
main: Quitting...
main: Starting...
iOS 15 iBoot detected!
getting get_boot_arg_patch(-v keepsyms=1 debug=0xfffffffe panic-wait-forever=1 wdt=-1) patch
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x180030ad0 : 000080d2
applying patch=0x180030b18 : 000080d2
applying patch=0x18003289c : 200080d2
applying patch=0x180033e14 : 78b80c10
applying patch=0x18004d520 : 2d76206b65657073796d733d312064656275673d307866666666666666652070616e69632d776169742d666f72657665723d31207764743d2d3100
main: Writing out patched file to iBEC.patched...
main: Quitting...
none
none
[*] Patching and signing kernelcache
Reading work/kernelcache.release.iphone10b...
[NOTE] Image4 payload data is LZFSE compressed, decompressing...
Extracted Image4 payload data to: work/kcache.raw
main: Starting...
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-8020 inputted
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x39c685
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x12ca924
get_amfi_out_of_my_way_patch: Patching AMFI at 0x12c7160
Kernel: Adding could_not_authenticate_personalized_root_hash patch...
get_could_not_authenticate_personalized_root_hash_patch: Entering ...
get_could_not_authenticate_personalized_root_hash_patch: Found "successfully validated on-disk root hash" str loc at 0x52474d
get_could_not_authenticate_personalized_root_hash_patch: Found "successfully validated on-disk root hash" xref at 0x1db4428
get_could_not_authenticate_personalized_root_hash_patch: Found previous cbz at 0x1db4404
get_could_not_authenticate_personalized_root_hash_patch: Found "could not authenticate personalized root hash!" str loc at 0x5246a2
get_could_not_authenticate_personalized_root_hash_patch: Found "could not authenticate personalized root hash!" xref at 0x1db4974
get_could_not_authenticate_personalized_root_hash_patch: Found cbz target at 0x1db4954
get_could_not_authenticate_personalized_root_hash_patch: Patching root hash check at 0x1db4954
main: Writing out patched file to work/kcache.patched...
main: Quitting...
Reading work/kcache.patched...
Compressing payload using LZSS...
IM4P outputted to: work/krnlboot.im4p
Reading work/krnlboot.im4p...
Reading work/IM4M...
Creating Image4...
Image4 file outputted to: boot-iPhone10,3/kernelcache.img4
[*] Signing DeviceTree
dtre
[*] Signing AOP
aopf
[*] Patching and signing trustcache
trst
none
[*] Booting device
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%

Done!
The device should now boot to iOS
If you already have ran palera1n, click Do All in the tools section of Pogo
If not, Pogo should be installed to Tips
ubuntu@ubuntu:~/Downloads/palera1n$

**Comment by SuginGv30** [comment]
after this when i open tips app it crashes

**Comment by Silentely** [comment]
> after this when i open tips app it crashes

Yes, I have the same problem as you.

**Comment by zenos3000** [comment]
Same

**Comment by figueroavictor** [comment]
iPhone 7+ 15.2 here, same problem. sh told me to install the "Tips" app from the app store and try again. never installed pogo and it broke the tips app.

**Comment by luckystar2000** [comment]
same, how to solve this?

**Comment by danni551** [comment]
maybe if u download my tips ipa on my profile and then install it with troll store and then delete it the Tips app will work
