### ISSUE TITLE
[-] Device didn't go in DFU mode, please rerun the script and try again

### ISSUE THREAD

**Issue by ZachariahMoreno** [palera1n/palera1n#166]
I put my iPad 6th Generation running IOS 15.1 (A10 Chip) into DFU mode and when I run the command  

./palera1n.sh --tweaks 15.1 

It give me this message 

[-] Device didn't go in DFU mode, please rerun the script and try again

I tried this several times it is not working. 

I installed the Tips App and disabled my passcode

**Comment by RealKGB** [comment]
Try again until you get it in DFU mode. This isn't GitHub Issues worthy.

**Comment by ZachariahMoreno** [comment]
> Try again until you get it in DFU mode. This isn't GitHub Issues worthy.

Who else am I gonna ask about this?

**Comment by ZachariahMoreno** [comment]
I solved the issue. It turns out a USB type A to lightning cable is required to enter DFU mode. This was not mentioned in the directions.
