### ISSUE TITLE
ERROR: Unable to connect to device [-] An error occurred

### ISSUE THREAD

**Issue by ZachariahMoreno** [palera1n/palera1n#167]
When I use the command ./palera1n.sh --tweaks 15.1 on my iPad 6th Generation running 15.1. It runs this long list of code and at the very end it says: "ERROR: Unable to connect to device [-] An error occurred"

**Comment by b0kch01** [comment]
Using a USB-A cable instead of a USB-C cable worked for me. You can use a dongle if needed.
