### ISSUE TITLE
palera1n installation stops at  ./palera1n.sh

### ISSUE THREAD

**Issue by 160255** [palera1n/palera1n#174]
installation of  palera1n code on A9 15.4.1 device stops at  ./palera1n.sh  (see below)

l-3:Downloads l$ git clone -b rootless --recursive https://github.com/palera1n/palera1n && cd palera1n
Cloning into 'palera1n'...
remote: Enumerating objects: 716, done.
remote: Counting objects: 100% (142/142), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 716 (delta 89), reused 96 (delta 59), pack-reused 574
Receiving objects: 100% (716/716), 78.82 MiB | 2.11 MiB/s, done.
Resolving deltas: 100% (402/402), done.
Submodule 'ramdisk' (https://github.com/palera1n/ramdisk) registered for path 'ramdisk'
Cloning into '/Users/l/Downloads/palera1n/ramdisk'...
remote: Enumerating objects: 1195, done.        
remote: Counting objects: 100% (79/79), done.        
remote: Compressing objects: 100% (35/35), done.        
remote: Total 1195 (delta 54), reused 60 (delta 44), pack-reused 1116        
Receiving objects: 100% (1195/1195), 249.18 MiB | 3.89 MiB/s, done.
Resolving deltas: 100% (657/657), done.
Submodule path 'ramdisk': checked out '0f8e30baec2bb66edb4733238232c7eebb705975'
l-3:palera1n l$ ./palera1n.sh

Nothing happens at this point, any suggestions ?

Thank you

**Comment by danni551** [comment]
You have to add --tweaks and your iOS Version e.g ./palera1n.sh --tweaks 15.3.1

**Comment by 160255** [comment]
Thanks, tried every conceivable combination, including dfu and non-dfu,  ./palera1n.sh --tweaks 15.4.1 
Interesting though, Trollstore and TrollHelper are installed, Pogo installed and when the Pogo "install" is pressed, "error bootstrap - 1" is idicated...
At this point I've given up and decided to wait for a possible stable jailbreak.

**Comment by itsnebulalol** [comment]
... tweaks don't work with 15.4.1. Please read the readme next time.

**Comment by 160255** [comment]
Yes, I'm aware of that, I was responding to the previous response
