### ISSUE TITLE
Iphone x 15.2 palera1in stop on text screen

### ISSUE THREAD

**Issue by ahmadsoran** [palera1n/palera1n#178]
[*] Device should now show text on screen
Creating listening port 2222 for device port 22
[*] Waiting for the ramdisk to finish booting
waiting for connection
New connection for 2222->22, fd = 5
waiting for connection
Connecting to usbmuxd failed, terminating.
New connection for 2222->22, fd = 5
waiting for connection

**Comment by gamono23** [comment]
Sudo pkill usbmuxd && sudo usbmuxd -p -f

**Comment by ahmadsoran** [comment]
> Sudo pkill usbmuxd && sudo usbmuxd -p -f

[*] Booting ramdisk
Version: 4350277321ccae0c194b5da3e2ac4e10dfda4afa-1
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8015
Found the USB handle.
Now you can boot untrusted images.
Version: 4350277321ccae0c194b5da3e2ac4e10dfda4afa-1
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Device should now show text on screen
Creating listening port 2222 for device port 22
bind(): Address in use
Error creating socket for listen port 2222: Address in use
[*] Waiting for the ramdisk to finish booting

**Comment by ahmadsoran** [comment]
thanks everything works now
