### ISSUE TITLE
Getting device info... ERROR: Unable to connect to device

### ISSUE THREAD

**Issue by DuJardinRene** [palera1n/palera1n#179]
./palera1n.sh --tweaks 15.2 --debug
[*] Command ran: ./palera1n.sh --tweaks 15.2 --debug
palera1n | Version 1.2.0-tweaks-3815451
Written by Nebula and Mineek | Some code and ramdisk from Nathan | Loader app by Amy

!!! WARNING WARNING WARNING !!!
This flag will add tweak support BUT WILL BE TETHERED.
THIS ALSO MEANS THAT YOU'LL NEED A PC EVERY TIME TO BOOT.
THIS ONLY WORKS ON 15.0-15.3.1
DO NOT GET ANGRY AT US IF UR DEVICE IS BORKED, IT'S YOUR OWN FAULT AND WE WARNED YOU
DO YOU UNDERSTAND? TYPE 'Yes, do as I say' TO CONTINUE
yes
[*] Disabling tweaks
[*] Getting device info...
ERROR: Unable to connect to device
ERROR: Unable to connect to device
ERROR: Unable to connect to device
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9

i tried put sudo before command but still dont work
idk how resolve this probleme if anyone can help me

**Comment by gamono23** [comment]
1: you could just check other issues with this error, and there was answers. 2: open new tab in terminal and do: sudo pkill usbmuxd && sudo usbmuxd -p -f

**Comment by DuJardinRene** [comment]
> 1: you could just check other issues with this error, and there was answers. 2: open new tab in terminal and do: sudo pkill usbmuxd && sudo usbmuxd -p -f

still doesn't work

**Comment by gamono23** [comment]
And what's the error?

**Comment by DuJardinRene** [comment]
ERROR: Unable to connect to device
ERROR: Unable to connect to device
ERROR: Unable to connect to device
jq: error (at :1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9

**Comment by gukandrew** [comment]
same here... ipad 5, ios 15.5
Tried recovery mode then switched DFU... 
```
[*] Command ran: ./palera1n.sh --dfu 15.6 --debug
palera1n | Version 1.2.0-tweaks-3815451
Written by Nebula and Mineek | Some code and ramdisk from Nathan | Loader app by Amy

[*] Getting device info...
ERROR: Unable to connect to device
ERROR: Unable to connect to device
ERROR: Unable to connect to device
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9
```
