### ISSUE TITLE
Apps installed from the App Store crash on launch in jailbroken state

### ISSUE THREAD

**Issue by alnoisegit** [palera1n/palera1n#182]
**Describe the bug**
I’m a jailbroken state, whenever trying to open an app that was installed through the app store the app immediately crashes. This is fixed by rebooting. 

**Expected behavior**
The app is supposed to open. 

**Info (please complete the following information):**
- iDevice's version: iOS 15.3.1
- Computer OS and version: iPhone X
- The command you ran: ’sudo bash ./palera1n.sh --tweaks 15.3.1’

**Additional context**
No tweaks installed, it was a fresh install of Palera1n.

**Comment by itsnebulalol** [comment]
Please learn how to read, it says this is an issue in the readme. No ETA on fix.
