### ISSUE TITLE
need a lot of help !!! Plese Help Me!!!!!!!!!

### ISSUE THREAD

**Issue by LoSei2** [palera1n/palera1n#184]
need a lot of help  I misunderstood the passcode, because ubuntu I couldn't run the ramdisk from checkm8, so I failed to boot so I didn't get jailbreak.  So I understand that my iphone is normal.  So I went to activate the passcode.  But it made me unable to use it or turn it off.  Do you have any way to fix it for me?

**Comment by Pearl-Codes** [comment]
you could try restoring the phone to factory settings? to be honest it just sounds like your bootlooping, not sure.

**Comment by LoSei2** [comment]
I can't remove passcode and now my iphone disable 1hr.

**Comment by Pearl-Codes** [comment]
you just said you couldnt boot and now your saying you cant remove the passcode? if you forgot the passcode reset your phone through icloud, whats the issue?

**Comment by LoSei2** [comment]
I haven't forgotten my passcode. I never change it but when i install palera1n have to turn off passcode until boot patch ramdisk got error so i exit dfu mode and use normal phone Realized that the passcode was off. So go in and open it as usual. but when i lock screen i put the passcode but iphone says the password is invalid.
