### ISSUE TITLE
what is a problem?

### ISSUE THREAD

**Issue by christ30870** [palera1n/palera1n#185]
**Describe the bug**
![Capture d’écran du 2022-10-30 10-50-35](https://user-images.githubusercontent.com/117001465/198873013-bba2ca1b-3f73-42b0-b145-4c4a06e65cb3.png)

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
- iDevice's version: [e.g. iOS 15.2, iOS 15.1]
- Computer OS and version: [e.g. macOS 13.0b3, Ubuntu 22.04]
- The command you ran: [e.g. `./palera1n.sh --dfu 15.1`]

**Additional context**

**Debug log**
Please run the script using `--debug` and send a log **inside** the backticks below.
```

```

**Comment by christ30870** [comment]
my iphone 6s does not reconnect with the computer at the end of the treatment. What should I do?

**Comment by Pearl-Codes** [comment]
you are supposed to fill out the template btw ;P

**Comment by Pearl-Codes** [comment]
did you run these commands in another terminal?
```
sudo systemctl stop usbmuxd
sudo usbmuxd -f -p
```

**Comment by christ30870** [comment]
i will try now

**Comment by Pearl-Codes** [comment]
yeah your supposed to if on linux, usbmuxd messes with stuff for some reason ;P

**Comment by christ30870** [comment]
well that seems to have worked, but my iphone 6s is still stuck on icloud...

**Comment by Pearl-Codes** [comment]
yeah sorry I'm not going to support unlocking iCloud, since that phone could very easily be stolen. (I'm not accusing you, I'm just covering my ass lmao)

**Comment by christ30870** [comment]
how to know if the jailbreak went well

**Comment by Pearl-Codes** [comment]
well you would be able to open the tips app and install from there, but if your phone is icloud locked you won't be able to access the homescreen

**Comment by christ30870** [comment]
thank you for your precious help.

**Comment by Pearl-Codes** [comment]
if your problem is solved please close :)

**Comment by Beast9265** [comment]
ok
