### ISSUE TITLE
Iphone7s

### ISSUE THREAD

**Issue by zixipurple** [palera1n/palera1n#186]
Always stuck in Creating ramdisk

The phone automatically restarts

一直卡在Creating ramdisk
手机自动重启了

*] Command ran: ./palera1n.sh --tweaks 15.1
palera1n | Version 1.2.0-tweaks-3815451
Written by Nebula and Mineek | Some code and ramdisk from Nathan | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk

**Comment by zixipurple** [comment]
ERROR: Unable to connect to device
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9

**Comment by zixipurple** [comment]
ubuntu

**Comment by danni551** [comment]
i also had this issue i fixed it by upgrading to iOS 15.3.1

**Comment by zixipurple** [comment]
> 我也有这个问题，我通过升级到iOS 15.3.1修复了它

但是不是只能升级到15.7了吗

**Comment by zixipurple** [comment]
> i also had this issue i fixed it by upgrading to iOS 15.3.1

But isn't it only possible to upgrade to 15.7?

**Comment by danni551** [comment]
if u have shsh blobs you can upgrade to 15.3.1 unsigned with futurerestore

**Comment by zixipurple** [comment]
> if u have shsh blobs you can upgrade to 15.3.1 unsigned with futurerestore

I only have 15.1 shsh

**Comment by danni551** [comment]
he already is on 15.1
