### ISSUE TITLE
iPhone 7 iOS 15.0.2 doesn't boot up after script is Done

### ISSUE THREAD

**Issue by danni551** [palera1n/palera1n#20]
My logs:danielshackintosh@daniels-Mini palera1n % ./palera1n.sh dumped.shsh
palera1n | Version 1.0.0
Written by Nebula | Some code by Nathan | Patching commands and ramdisk by Mineek | Loader app by Amy

Hello, iPhone9,3 on 15.0.2!
[*] Switching device into recovery mode...
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Pwning device
[*] Booting device
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%

Done!
The device should now boot to iOS
If you already have installed Pogo, click uicache and remount preboot in the tools section
If not, get an IPA from the latest action build of Pogo and install with TrollStore
Add the repo mineek.github.io/repo for Procursus

**Comment by itsnebulalol** [comment]
run `./palera1n.sh clean` and then run the script again, but add `--debug` and send me the log.
