### ISSUE TITLE
Ramdisk Branch - Failed to read shsh

### ISSUE THREAD

**Issue by bthedorff** [palera1n/palera1n#22]
Mac OS 12.5.1
iPhone 8 Global 
iOS 15.6

I know your ramdisk branch and support for iOS 15 outside of the CT bug is still new and unstable but I wanted to give it a shot on my device and providing a log in case it helps. 

Command ran, `./palera1n.sh --debug`

```
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:001129EE08D3A02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:001129EE08D3A02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:001129EE08D3A02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[*] Downloading BuildManifest
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: https://updates.cdn-apple.com/2022SummerFCS/fullrestores/012-41763/0BC321DF-1A4E-473B-9EE0-BF126CB1CDA8/iPhone_4.7_P3_15.6_19G71_Restore.ipsw
init done
getting: BuildManifest.plist
  0% [
100% [==========================================================================
  3% [==>
  6% [=====>
  9% [========>
 13% [============>
 16% [===============>
 19% [==================>
 22% [=====================>
 26% [=========================>
 29% [============================>
 32% [===============================>
 35% [==================================>
 39% [======================================>
 42% [=========================================>
 45% [============================================>
 48% [===============================================>
 52% [===================================================>
 55% [======================================================>
 58% [=========================================================>
 61% [============================================================>
 65% [================================================================>
 68% [===================================================================>
 70% [=====================================================================>
 73% [========================================================================>
 76% [==========================================================================
 80% [==========================================================================
 83% [==========================================================================
 86% [==========================================================================
 89% [==========================================================================
 93% [==========================================================================
 96% [==========================================================================
 99% [==========================================================================
100% [===================================================================================================>]
download succeeded
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
img4tool: failed with exception:
[exception]:
what=Failed to read shshFile
code=19529736
line=298
file=main.cpp
commit count=197:
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f:
[-] An error occurred
```

It is attempting to read an shsh file, do we need to specify this file? I saw a different open issue where they specified the shsh file but neither of the branch's readme's specifies this. Is this an unintended error or an error due to being in the early stages?

**Comment by itsnebulalol** [comment]
I can fix this now, give me a second

**Comment by itsnebulalol** [comment]
`git pull` and try again please

**Comment by kristenlc** [comment]
> `git pull` and try again please

I have compiled ideviceinfo and ideviceenterrecovery for Darwin static build on my repo, feel free to copy it to your repo and remove the requirement for libimobiledevice from Darwin systems on your readme. 

I have also finished my own working and reliable alternative to your ramdisk branch which is now ready for general use on my repo. You just run `./palera1n.sh --dfu < your iOS version here >` and it will automatically create a ramdisk, boot the RAM disk; install trollstore automatically and spit out an ascii text of palera1n on the phone and on the computer it says to press enter once you see the palera1n ascii text on the phone and then the script will dump the blobs automatically and then prompt the user to put the phone back in dfu mode.... it will then create the boot files for amfi bypass and boot the iPhone with palera1n. Works 100% no issues whatsoever. Took me forever cause I kept getting errors, spent a good 14 hours straight of nonstop work to get that done

**Comment by itsnebulalol** [comment]
I’ll look into it, thanks

Feel free to add my discord, nebula#5555, instead of sending stuff like this in an issue unrelated

**Comment by bthedorff** [comment]
> `git pull` and try again please

I did a new git clone and tried again but I got the same thing. Below is the full log

```
Already up to date.
brandon@Brandons-MacBook-Pro palera1n % ./palera1n.sh 15.6 --debug
palera1n | Version 1.0.0
Written by Nebula | Some code by Nathan | Patching commands and ramdisk by Mineek | Loader app by Amy

Hello, iPhone10,1 on 15.6!
[*] Switching device into recovery mode...
Telling device with udid fd9701cf841ea5466ec01a5edbe31bdb2301e520 to enter recovery mode.
Failed to enter recovery mode.
Device is successfully switching to recovery mode.
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0)
Hold volume down + side button (0)
Keep holding (0)
Release side button, but keep holding volume down (0)
[*] Device entered DFU!
[*] Pwning device
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:001129EE08D3A02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:001129EE08D3A02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SPRAY
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:001129EE08D3A02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:001129EE08D3A02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:001129EE08D3A02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[*] Downloading BuildManifest
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: https://updates.cdn-apple.com/2022SummerFCS/fullrestores/012-41763/0BC321DF-1A4E-473B-9EE0-BF126CB1CDA8/iPhone_4.7_P3_15.6_19G71_Restore.ipsw
init done
getting: BuildManifest.plist
  0% [
100% [==========================================================================
  3% [==>
  6% [=====>
  9% [========>
 13% [============>
 16% [===============>
 19% [==================>
 22% [=====================>
 26% [=========================>
 29% [============================>
 32% [===============================>
 35% [==================================>
 39% [======================================>
 42% [=========================================>
 45% [============================================>
 48% [===============================================>
 52% [===================================================>
 55% [======================================================>
 58% [=========================================================>
 61% [============================================================>
 65% [================================================================>
 68% [===================================================================>
 70% [=====================================================================>
 73% [========================================================================>
 76% [==========================================================================
 80% [==========================================================================
 83% [==========================================================================
 86% [==========================================================================
 89% [==========================================================================
 93% [==========================================================================
 96% [==========================================================================
 99% [==========================================================================
100% [===================================================================================================>]
download succeeded
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
img4tool: failed with exception:
[exception]:
what=Failed to read shshFile
code=19529736
line=298
file=main.cpp
commit count=197:
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f:
[-] An error occurred
```

**Comment by bthedorff** [comment]
```
Archive:  gaster-Darwin.zip
  inflating: gaster
Submodule 'ramdisk' (https://github.com/palera1n/ramdisk) registered for path 'ramdisk'
Cloning into '/Users/brandon/iPhone-Programs/palera1n/ramdisk'...
Submodule path 'ramdisk': checked out '48404147cfed60e82b3697cddc083a6e87ce2f36'
option -x not recognized

usage: xattr [-slz] file [file ...]
       xattr -p [-slz] attr_name file [file ...]
       xattr -w [-sz] attr_name attr_value file [file ...]
       xattr -d [-s] attr_name file [file ...]
       xattr -c [-s] file [file ...]

The first form lists the names of all xattrs on the given file(s).
The second form (-p) prints the value of the xattr attr_name.
The third form (-w) sets the value of the xattr attr_name to attr_value.
The fourth form (-d) deletes the xattr attr_name.
The fifth form (-c) deletes (clears) all xattrs.

options:
  -h: print this help
  -s: act on symbolic links themselves rather than their targets
  -l: print long format (attr_name: attr_value)
  -z: compress or decompress (if compressed) attribute value in zip format
```

Now I get this

**Comment by itsnebulalol** [comment]
`git pull` and try again, make sure to `./palera1n.sh clean` before you try again.

**Comment by bthedorff** [comment]
> `git pull` and try again, make sure to `./palera1n.sh clean` before you try again.

Same thing e3xcept option -r 

```
option -r not recognized

usage: xattr [-slz] file [file ...]
       xattr -p [-slz] attr_name file [file ...]
       xattr -w [-sz] attr_name attr_value file [file ...]
       xattr -d [-s] attr_name file [file ...]
       xattr -c [-s] file [file ...]
```

**Comment by itsnebulalol** [comment]
uhh, that’s weird

for now you can just remove the line in the script using a text editor

**Comment by bthedorff** [comment]
Removed that line and got further but now get an error making the ramdisk. When I got this previous on the official version of SSHRD i couldn't figure out the fix but recloning fixed it. 

```
/dev/disk2          	                               	/private/tmp/SSHRD
Darwin/gtar: ramdisk.tar.gz: Cannot open: No such file or directory
Darwin/gtar: Error is not recoverable: exiting now
```

Have you gotten this to work on any device not using the CT bug? If not, it may be above my tweaking abilities lol

**Comment by itsnebulalol** [comment]
`git pull` and try again. Could possibly fix it

**Comment by bthedorff** [comment]
> `git pull` and try again. Could possibly fix it

xattr still has to be commented out and I still get the same gtar issue as above

**Comment by itsnebulalol** [comment]
Stupid question, is the ramdisk.tar.gz in the ramdisk folder?

If so, can you add `echo $(pwd)` on line 141 of sshrd.sh, then show me the path?

**Comment by bthedorff** [comment]
Yes but it does not have the .gz extension.  Only .tar, I even tried adding the .gz and gzip gave an unsupported error. Below is the output assume I add it to sshrd.sh 

```
dtre
rtsc
rdsk
/Users/brandon/iPhone-Programs/palera1n/ramdisk
/dev/disk2          	                               	/private/tmp/SSHRD
Darwin/gtar: ramdisk.tar.gz: Cannot open: No such file or directory
Darwin/gtar: Error is not recoverable: exiting now
[-] An error occurred
```

**Comment by itsnebulalol** [comment]
ah, i forgot to update the submodule. `git pull` again please

**Comment by bthedorff** [comment]
> ah, i forgot to update the submodule. `git pull` again please

That fixed that error! I got into SSHRD ramdisk but stops there. From here is it just installing pogo per the code then rebooting? If so I should be able to do it manually but if not, I may need to comment out code until the reboot and start it up again

**Comment by itsnebulalol** [comment]
Do you know what SSH commands are executing?

**Comment by bthedorff** [comment]
Yes, it stops at line 254. I manually mounted the filesystem for the first time. I did use the official SSHRD to dump my blobs then I renamed it `iPhone10,1-15.6.shsh` to see if I could get farther into the program or a different error. Could that be causing the stop?

**Comment by itsnebulalol** [comment]
If the blob is named that, it should skip the ramdisk: `if [ ! -f blobs/"$deviceid"-"$version".shsh2 ]; then`. Does it do that? I'll work out the issues with the ramdisk.

**Comment by bthedorff** [comment]
I think the issue is once you are in the ramdisk through the terminal you don't need `"$dir"/sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no -p2222 root@localhost "mount_filesystems" > "$out"`, instead you would just use `mount_filesystem`. I believe the rest is for "one time code" into the ramdisk.  Pretty sure but I haven't tested it yet.

It did not attempt to dump blobs. It ended after the iproxy connection

**Comment by bthedorff** [comment]
> > Finally, to mount the filesystems, run `mount_filesystems`
> 
> The command should be right, you need to mount it to replace tips for Pogo

Yeah that command is right but I am wrong, you can't just use `mount_filesysystem` in the code.

**Comment by bthedorff** [comment]
> > Finally, to mount the filesystems, run `mount_filesystems`
> 
> The command should be right, you need to mount it to replace tips for Pogo

Is it coded to replace tips with pogo already? or am I missing something? I don't see it sending any files to replace the tips.app or any files in palera1n referencing pogo

**Comment by itsnebulalol** [comment]
Line 260 to line 270. Pogo is already in the ramdisk.tar.gz (which is /usr/local/bin/loader.app in the ramdisk)

**Comment by bthedorff** [comment]
> If the blob is named that, it should skip the ramdisk: `if [ ! -f blobs/"$deviceid"-"$version".shsh2 ]; then`. Does it do that? I'll work out the issues with the ramdisk.


After a clean git clone, it still stops at line 254 of palera1n.sh without any blobs saved. idk if that helps you lol

**Comment by bthedorff** [comment]
I manually did all the ramdisk requirements then rebooted. I commented out the code for the ramdisk and reran it and failed to read the ssh file (using the one I pulled from SSHRD then renamed. I renamed it to "iPhone10,1-15.6.shsh"

```
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[*] Converting blob
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
img4tool: failed with exception:
[exception]:
what=Failed to read shshFile
code=19529736
line=298
file=main.cpp
commit count=197:
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f:
```

**Comment by itsnebulalol** [comment]
Should be shsh2

**Comment by bthedorff** [comment]
> Should be shsh2

Odd, I didn't think they could be .shsh2 files. Always thought they had to be .shsh. But I got the shsh2 file using the in code command instead of what SSHRD uses. Now it fails to boot. Does this give you any idea where it's failing by chance? 

```
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[*] Booting device
[==================================================] 100.0%
[==================================================] 100.0%

Done!
The device should now boot to iOS
If you already have ran palera1n, click Do All in the tools section of Pogo
If not, Pogo should be installed to Tips
```

**Comment by itsnebulalol** [comment]
you should `./palera1n.sh clean` then try again

**Comment by bthedorff** [comment]
> you should `./palera1n.sh clean` then try again

tried that and that didn't work but then again I've kinda hacked this together lol. But I did a clean git clone and ran it once so it built the needed folders. Put my .shsh2 blob in the blobs folder and did a `./palera1n clean` but that didn't work either

**Comment by bthedorff** [comment]
> you should `./palera1n.sh clean` then try again

Nevermind, a clean git clone and placing the shsh2 blob in blobs did work. But doesn't work starting in dfu. You have to start in normal mode it looks like for right now

**Comment by itsnebulalol** [comment]
that might be because pogo is running from tips. pogo would open without amfi patches.

by the way, the ramdisk should be fixed so it should dump blobs now

**Comment by bthedorff** [comment]
> that might be because pogo is running from tips. pogo would open without amfi patches.
> 
> by the way, the ramdisk should be fixed so it should dump blobs now

Thanks! I'll give it another try. Any ideas how to fix that? I open Tips and it brings up Pogo but when I click install, I get that error

**Comment by bthedorff** [comment]
If it helps, after the error popup, under the menu on the pogo screen it say "Failed to prepare bootstrap-1"

**Comment by bthedorff** [comment]
> that might be because pogo is running from tips. pogo would open without amfi patches.
> 
> by the way, the ramdisk should be fixed so it should dump blobs now

It dumps blobs then the script crashes after the phone reboots. Getting extremely close though!

```
[*] Dumping blobs and installing Pogo
16382+2 records in
16383+1 records out
4194127 bytes transferred in 0.313751 secs (13367693 bytes/sec)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
Found IM4R extracting generator: ok
Saved IM4M to blobs/iPhone10,1-15.6.shsh2
seputil: Gigalocker file (/mnt7/BF6BD375-7AB4-5B73-884A-9FE2E37998E2.gl) exists
seputil: Gigalocker initialization completed
[*] Switching device into recovery mode...
ERROR: No device found!
ERROR: No UDID specified
Usage: ideviceenterrecovery [OPTIONS] UDID
```

**Comment by itsnebulalol** [comment]
it's hit or miss, sometimes that happens. i can add a bit more delay maybe

**Comment by bthedorff** [comment]
> > that might be because pogo is running from tips. pogo would open without amfi patches.
> > by the way, the ramdisk should be fixed so it should dump blobs now
> 
> Thanks! I'll give it another try. Any ideas how to fix that? I open Tips and it brings up Pogo but when I click install, I get that error

After booting again a few times, Now Tips.app is gone and Pogo has an icon that won't load. When I try to open Pogo, it says "Pogo needs to be updated; The developer of this app needs to update it to work with this version of iOS".

I never did get the install to work. Any ideas?

**Comment by itsnebulalol** [comment]
I've never seen that happen, TIps shouldn't be gone...

**Comment by bthedorff** [comment]
> I've never seen that happen, TIps shouldn't be gone...

Hmmm strange. Should I make an issue on Pogo's github then?

**Comment by itsnebulalol** [comment]
No, not yet

**Comment by bthedorff** [comment]
> No, not yet

Okay, I can do an Erase all Content and Settings if you want, then give a shot on a clean install

**Comment by bthedorff** [comment]
> it's hit or miss, sometimes that happens. i can add a bit more delay maybe

If you added a delay, it may have caused an issue with waiting to boot the ramdisk

```
[==================================================] 100.0%
[*] Device should now show text on screen
[*] Waiting for the ramdisk to finish booting
```

**Comment by itsnebulalol** [comment]
> Okay, I can do an Erase all Content and Settings if you want, then give a shot on a clean install

If you feel it’s worth it, sure. Make sure you reclone to the main branch since it was merged. Pogo isn’t going to work properly though, you’ll want to use SSHRD_Script to install TrollStore to Tips (or another app). Since palera1n patches AMFI, TrollStore will load.

Once you get TrollStore installed, install Pogo using the link in the readme.

**Comment by bthedorff** [comment]
> > Okay, I can do an Erase all Content and Settings if you want, then give a shot on a clean install
> 
> If you feel it’s worth it, sure. Make sure you reclone to the main branch since it was merged. Pogo isn’t going to work properly though, you’ll want to use SSHRD_Script to install TrollStore to Tips (or another app). Since palera1n patches AMFI, TrollStore will load.
> 
> Once you get TrollStore installed, install Pogo using the link in the readme.

Tried it and didn't work lol. Trollstore will work on 15.6 if I install it because of the patches?

**Comment by itsnebulalol** [comment]
Yes, it should

**Comment by bthedorff** [comment]
> Yes, it should

Perfect! it worked! I installed TrollStore via SSHRD then reran palera1n. Once booted I opened Tips and clicked install TrollStore and it worked! So can I do everything Trollstore can do except it doesn't carry over when i normal boot? (compared to booting using the palera1n script)

**Comment by itsnebulalol** [comment]
Yea you can install whatever with TrollStore, but it won’t persist in stock. You’ll have to rerun palera1n.
