### ISSUE TITLE
How to use these .sh files?

### ISSUE THREAD

**Issue by matdanh** [palera1n/palera1n#220]
binaries/postboot.sh
binaries/postbootnosub.sh
binaries/preptweaks.sh

May I ask, are these files used device to springboard then we shsh from device and run them right?

Can I replace substitute in preptweaks.sh with mobilesubstrate?

Many thanks to the developers!!

**Comment by itsnebulalol** [comment]
Those are actually not used anymore; they’re there for legacy purposes. What would be the point of changing Substitute to Substrate though? As far as I know, Substrate doesn’t work correctly on 15.
