### ISSUE TITLE
is it support ios 15.6.1 on iphone 6s?

### ISSUE THREAD

**Issue by mino389** [palera1n/palera1n#26]
i successfully booted but nothing changed on ios 15.6.1

**Comment by itsnebulalol** [comment]
You'll want to open the Tips app, and hit Install.

**Comment by mino389** [comment]
nothing changed in the tips app

**Comment by itsnebulalol** [comment]
Use SSHRD_Script to install TrollStore, boot palera1n, and install the Pogo IPA with TrollStore.

**Comment by mino389** [comment]
I get this error when running debug:

[*] Patching and converting kernelcache
Reading work/kernelcache.release.n71...
[NOTE] Image4 payload data is LZSS compressed, decompressing...
Extracted extra Image4 payload data: to work/kpp.bin.
Extracted Image4 payload data to: work/kcache.raw
main: Starting...
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-8020 inputted
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x973ee1
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x1076c64
get_amfi_out_of_my_way_patch: Patching AMFI at 0x10722a8
Kernel: Adding could_not_authenticate_personalized_root_hash patch...
get_could_not_authenticate_personalized_root_hash_patch: Entering ...
get_could_not_authenticate_personalized_root_hash_patch: Found "successfully validated on-disk root hash" str loc at 0xd0bc0a
get_could_not_authenticate_personalized_root_hash_patch: Found "successfully validated on-disk root hash" xref at 0x1c1c964
get_could_not_authenticate_personalized_root_hash_patch: Found previous cbz at 0x1c1c940
get_could_not_authenticate_personalized_root_hash_patch: Found "could not authenticate personalized root hash!" str loc at 0xd0bb5f
get_could_not_authenticate_personalized_root_hash_patch: Found "could not authenticate personalized root hash!" xref at 0x1c1ca3c
get_could_not_authenticate_personalized_root_hash_patch: Found cbz target at 0x1c1ca1c
get_could_not_authenticate_personalized_root_hash_patch: Patching root hash check at 0x1c1ca1c
main: Writing out patched file to work/kcache.patched...
main: Quitting...
Reading work/kcache.patched...
Reading extra: work/kpp.bin...
Compressing payload using LZSS...
IM4P outputted to: work/krnlboot.im4p
Reading work/krnlboot.im4p...
Reading work/IM4M...
Creating Image4...
Image4 file outputted to: boot-iPhone8,1/kernelcache.img4
[*] Converting DeviceTree
dtre
[*] Patching and converting trustcache
trst
none
[*] Booting device
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%

Done!
The device should now boot to iOS
If you already have ran palera1n, click Do All in the tools section of Pogo
If not, Pogo should be installed to Tips
tuannguyen@TUANNGUYENs-MacBook-Pro palera1n %
