### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by ebzrvf** [palera1n/palera1n#27]
ebzrvf@ebzrvf:~/Desktop/palera1n$ sudo ./palera1n.sh
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

./palera1n.sh: line 95: /home/ebzrvf/Desktop/palera1n/binaries/Linux/ideviceinfo: No such file or directory
./palera1n.sh: line 95: /home/ebzrvf/Desktop/palera1n/binaries/Linux/ideviceinfo: No such file or directory
./palera1n.sh: line 95: /home/ebzrvf/Desktop/palera1n/binaries/Linux/ideviceinfo: No such file or directory
Hello,  on !
[*] Switching device into recovery mode...
./palera1n.sh: line 95: /home/ebzrvf/Desktop/palera1n/binaries/Linux/ideviceinfo: No such file or directory
./palera1n.sh: line 217: /home/ebzrvf/Desktop/palera1n/binaries/Linux/ideviceenterrecovery: No such file or directory

**Comment by ebzrvf** [comment]
1 more
ebzrvf@ebzrvf:~/Desktop/palera1n$ ./palera1n.sh --dfu 15.4.1
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk
ebzrvf@ebzrvf:~/Desktop/palera1n$ 
:/

**Comment by itsnebulalol** [comment]
Run `git pull` and try again. Sorry for the late response.

**Comment by rubensalbukrk** [comment]
me too,
debug:
rubens@rubensdev:~/palera1n$ sudo ./palera1n.sh --dfu 15.4.1 --debug
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk
gzip: other/ramdisk.tar.gz: No such file or directory
[-] An error occurred
rubens@rubensdev:~/palera1n$

**Comment by ebzrvf** [comment]
> Run `git pull` and try again. Sorry for the late response.

thx

**Comment by ebzrvf** [comment]
> Run `git pull` and try again. Sorry for the late response.

it fix, but i have problem with ramdisk, creating ramdisk.. and it close automatic

**Comment by itsnebulalol** [comment]
Can you reclone the repo and try again
