### ISSUE TITLE
STUCK at Cloning into '/home/kali/Downloads/palera1n/ramdisk'...

### ISSUE THREAD

**Issue by MohamedTm7** [palera1n/palera1n#28]
Cloning into '/home/kali/Downloads/palera1n/ramdisk'...
any solution..?

**Comment by itsnebulalol** [comment]
This isn't very helpful, can you show the output? Most likely it's your internet. Also, please use something other than Kali (it probably will have other issues), thanks.

**Comment by MohamedTm7** [comment]
ERROR: No device found!
ERROR: No device found!
ERROR: No device found!
Hello,  on !
[*] Switching device into recovery mode...
ERROR: No device found!
ERROR: No UDID specified
Usage: ideviceenterrecovery [OPTIONS] UDID

Makes a device with the supplied UDID enter recovery mode immediately.

OPTIONS:
  -d, --debug           enable communication debugging
  -h, --help            prints usage information
  -v, --version         prints version information

Homepage:    <https://libimobiledevice.org>
Bug Reports: <https://github.com/libimobiledevice/libimobiledevice/issues>

**Comment by itsnebulalol** [comment]
Is your device connected in normal mode?

**Comment by MohamedTm7** [comment]
No, it's in dfu mode.

**Comment by itsnebulalol** [comment]
You should read the readme, if you want to start from DFU mode, you add `--dfu <your ios version here>` to the end of the command.

**Comment by MohamedTm7** [comment]
![image](https://user-images.githubusercontent.com/88404979/192173649-0c06e855-c99b-4c94-aed8-19a194c328ce.png)

**Comment by itsnebulalol** [comment]
Again, please read the readme. Your command should be `./palera1n.sh --dfu 15.0.2`

**Comment by MohamedTm7** [comment]
I tried it 
[*] Getting device info...
/home/kali/Downloads/palera1n/binaries/Linux/irecovery: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/kali/Downloads/palera1n/binaries/Linux/irecovery)
/home/kali/Downloads/palera1n/binaries/Linux/irecovery: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/kali/Downloads/palera1n/binaries/Linux/irecovery)
/home/kali/Downloads/palera1n/binaries/Linux/irecovery: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/kali/Downloads/palera1n/binaries/Linux/irecovery)
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9

**Comment by itsnebulalol** [comment]
Can you try and replace `binaries/Linux/irecovery` with this binary in the zip?

[irecovery.zip](https://github.com/palera1n/palera1n/files/9642523/irecovery.zip)

**Comment by MohamedTm7** [comment]
# ./palera1n.sh --dfu 15.0.2
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
/home/kali/Downloads/palera1n/binaries/Linux/irecovery: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
/home/kali/Downloads/palera1n/binaries/Linux/irecovery: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
/home/kali/Downloads/palera1n/binaries/Linux/irecovery: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9

**Comment by itsnebulalol** [comment]
Install libreadline7:
```
curl -sLO http://ftp.us.debian.org/debian/pool/main/r/readline/libreadline7_7.0-5_amd64.deb
sudo apt install ./libreadline7_7.0-5_amd64.deb
```

**Comment by MohamedTm7** [comment]
After installing libreadline7

# ./palera1n.sh --dfu 15.0.2
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk

#

**Comment by itsnebulalol** [comment]
It's... creating the ramdisk. Unless it went back to the prompt

**Comment by MohamedTm7** [comment]
it went back to the prompt

**Comment by itsnebulalol** [comment]
Can you please add `--debug` to the end of the command and show me the whole log

**Comment by MohamedTm7** [comment]
└─# ./palera1n.sh --dfu 15.0.2 --debug
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk
gzip: other/ramdisk.tar already exists; do you wish to overwrite (y or n)? n
        not overwritten
[-] An error occurred
                                                                               
┌──(root㉿kali)-[/home/kali/Downloads/palera1n]
└─# ./palera1n.sh --dfu 15.0.2 --debug
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk
gzip: other/ramdisk.tar already exists; do you wish to overwrite (y or n)? y
[*] Getting device info... this may take a second
Segmentation fault
[-] An error occurred

**Comment by itsnebulalol** [comment]
> Can you try and replace `binaries/Linux/irecovery` with this binary in the zip?
> 
> [irecovery.zip](https://github.com/palera1n/palera1n/files/9642523/irecovery.zip)

**Comment by MohamedTm7** [comment]
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk
[*] Getting device info... this may take a second
Segmentation fault
[-] An error occurred

Still not working 
Pc keep giving sound of plugged in and out four or five times.

**Comment by itsnebulalol** [comment]
Can you reclone the repo and try again

**Comment by MohamedTm7** [comment]
I'm sorry but still not working...

**Comment by itsnebulalol** [comment]
Are you on arm64..? It doesn't segfault for anyone else, maybe use Ubuntu 22.04 instead of Kali as I said before.

**Comment by masckmaster2007** [comment]
Using Ubuntu 22.04, the custom irecovery and i get this #136
