### ISSUE TITLE
Hey I tried to run Palera1n on 15.7 iphone7 GSM

### ISSUE THREAD

**Issue by DerrTijarist** [palera1n/palera1n#29]
I booted etc. and after I opened the Tips app on press on install I got a error Messages (Failed with -1, are you sure you have amfi patched) (Failed to prepare bootstrap -1) did I do something wrong? I know its still on process and I appreciate the work!

**Comment by itsnebulalol** [comment]
Use SSHRD_Script to install TrollStore, boot palera1n, and install the Pogo IPA with TrollStore.
