### ISSUE TITLE
other/ramdisk.tar.gz: No such file or directory

### ISSUE THREAD

**Issue by rubensalbukrk** [palera1n/palera1n#30]
[*] Getting device info...
[*] Creating ramdisk
gzip: other/ramdisk.tar.gz: No such file or directory
[-] An error occurred

what is ?

**Comment by itsnebulalol** [comment]
Can you please use --debug and show the error

**Comment by rubensalbukrk** [comment]
> Can you please use --debug and show the error

yes,
rubens@rubensdev:~/palera1n$ sudo ./palera1n.sh --dfu 15.4.1 --debug
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[] Getting device info...
[] Creating ramdisk
gzip: other/ramdisk.tar.gz: No such file or directory
[-] An error occurred
rubens@rubensdev:~/palera1n$

**Comment by itsnebulalol** [comment]
Is it in `ramdisk/other`? The only thing I can think of is that it doesn't like the relative path. Can you modify line 17 of `ramdisk/sshrd.sh` to be `gzip -d $(pwd)/other/ramdisk.tar.gz`. Also, throw in `echo $(pwd)` right above it. Then, show me the output.

**Comment by rubensalbukrk** [comment]
d0ne,
[*] Getting device info...
[*] Creating ramdisk
gzip: /home/rubens/palera1n/ramdisk/other/ramdisk.tar.gz: No such file or directory
[-] An error occurred

**Comment by itsnebulalol** [comment]
Can you clone the repo again? I don't see a reason why it isn't working.

**Comment by rubensalbukrk** [comment]
> Can you clone the repo again? I don't see a reason why it isn't working.

I discovered!!!
copy paste "ramdisk" inside the "other" folder

sorry me bad english

**Comment by itsnebulalol** [comment]
what? do you mean copying `ramdisk.tar.gz` into the other folder in the root directory?

**Comment by rubensalbukrk** [comment]
now:
100% [===================================================================================================>]
download succeeded
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:0C ECID:000E415818EAED26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:0C ECID:000E415818EAED26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 14 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c2d88 : 000080d2
applying patch=0x1800c2ddc : 000080d2
applying patch=0x1800c4758 : 200080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 14 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1  ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c2d88 : 000080d2
applying patch=0x1800c2ddc : 000080d2
applying patch=0x1800b38c8 : 000080d2c0035fd6
applying patch=0x1800b3918 : 000080d2c0035fd6
applying patch=0x1800f0d28 : 000080d2c0035fd6
applying patch=0x1800c4758 : 200080d2
applying patch=0x1800c5d38 : f9473430
applying patch=0x18012e635 : 72643d6d64302064656275673d30783230313465202d76207764743d2d31202000
applying patch=0x1800c8a14 : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
main: Detected fat macho kernel
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-7195 inputted
get_amfi_out_of_my_way_patch: Found entitlements too small str loc at 0x9015f7
get_amfi_out_of_my_way_patch: Found entitlements too small str ref at 0xfc6f30
get_amfi_out_of_my_way_patch: Patching AMFI at 0xfc1df8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
error: allocate
error: Success
[-] An error occurred
rubens@rubensdev:~/palera1n$

**Comment by itsnebulalol** [comment]
Yeah because you aren't supposed to move the files. Have you recloned the repo?

**Comment by rubensalbukrk** [comment]
> what? do you mean copying `ramdisk.tar.gz` into the other folder in the root directory?

no, copy the "ramdisk" folder into the "other" folder, = /palera1n/other/ramdisk/other

**Comment by itsnebulalol** [comment]
That wouldn't make sense since gzip isn't even looking for that.

**Comment by rubensalbukrk** [comment]
and now?

**Comment by itsnebulalol** [comment]
I told you to reclone the repo.

**Comment by rubensalbukrk** [comment]
OK, I deleted everything and cloned it again...
it works!!!

in the end this happens:
100% [===================================================================================================>]
download succeeded
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:0C ECID:000E415818EAED26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:0C ECID:000E415818EAED26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 14 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c2d88 : 000080d2
applying patch=0x1800c2ddc : 000080d2
applying patch=0x1800c4758 : 200080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 14 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1  ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c2d88 : 000080d2
applying patch=0x1800c2ddc : 000080d2
applying patch=0x1800b38c8 : 000080d2c0035fd6
applying patch=0x1800b3918 : 000080d2c0035fd6
applying patch=0x1800f0d28 : 000080d2c0035fd6
applying patch=0x1800c4758 : 200080d2
applying patch=0x1800c5d38 : f9473430
applying patch=0x18012e635 : 72643d6d64302064656275673d30783230313465202d76207764743d2d31202000
applying patch=0x1800c8a14 : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
main: Detected fat macho kernel
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-7195 inputted
get_amfi_out_of_my_way_patch: Found entitlements too small str loc at 0x9015f7
get_amfi_out_of_my_way_patch: Found entitlements too small str ref at 0xfc6f30
get_amfi_out_of_my_way_patch: Patching AMFI at 0xfc1df8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
error: allocate
error: Success
[-] An error occurred
rubens@rubensdev:~/palera1n$

**Comment by itsnebulalol** [comment]
What distro is this?

**Comment by rubensalbukrk** [comment]
LINUX MINT LASTED

> What distro is this?

**Comment by itsnebulalol** [comment]
can you show me the output of `ls ramdisk/other`

**Comment by rubensalbukrk** [comment]
> can you show me the output of `ls ramdisk/other`

rubens@rubensdev:~/palera1n$ ls ramdisk/other
bootlogo.im4p  ramdisk.tar
rubens@rubensdev:~/palera1n$

**Comment by itsnebulalol** [comment]
Can you reclone the repo and try again
