### ISSUE TITLE
error allocate and success ios 15.6.1

### ISSUE THREAD

**Issue by x7Sevs** [palera1n/palera1n#35]
download succeeded
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000C3090302BC02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000C3090302BC02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 14 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x180032bf0 : 000080d2
applying patch=0x180032c44 : 000080d2
applying patch=0x180034750 : 200080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 14 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1  ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x180032bf0 : 000080d2
applying patch=0x180032c44 : 000080d2
applying patch=0x18001f8a8 : 000080d2c0035fd6
applying patch=0x18001f8f8 : 000080d2c0035fd6
applying patch=0x18006be6c : 000080d2c0035fd6
applying patch=0x180034750 : 200080d2
applying patch=0x180035cac : 183e5430
applying patch=0x1800de46d : 72643d6d64302064656275673d30783230313465202d76207764743d2d31202000
applying patch=0x180039060 : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-7195 inputted
get_amfi_out_of_my_way_patch: Found entitlements too small str loc at 0x40c7ee
get_amfi_out_of_my_way_patch: Found entitlements too small str ref at 0x11ac270
get_amfi_out_of_my_way_patch: Patching AMFI at 0x11a86e8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
error: allocate
error: Success
[-] An error occurred

**Comment by rubensalbukrk** [comment]
me too,
in 7 iphone 15.4.1
nothing happens

**Comment by itsnebulalol** [comment]
Seems like an issue with hfsplus on Linux? I’ll see if there’s anything to mitigate it

**Comment by x7Sevs** [comment]
> Seems like an issue with hfsplus on Linux? I’ll see if there’s anything to mitigate it

how do i fix the problem with hfs?

**Comment by itsnebulalol** [comment]
This was fixed, please reclone the repo
