### ISSUE TITLE
Sileo doesn’t work 

### ISSUE THREAD

**Issue by xiuxianchengdi** [palera1n/palera1n#36]
I can’t fresh the source
![417D56A6-83FC-48BA-9C0A-EF99825DDE8D](https://user-images.githubusercontent.com/93297382/192317679-5564bf87-a54f-48b7-b063-17491d65cc31.jpeg)

**Comment by itsnebulalol** [comment]
This is a developer jailbreak, and there’s no tweak injection. Repos like Havoc aren’t updated for rootless either.
