### ISSUE TITLE
iPad 5 iOS 15.5 no Pogo installed

### ISSUE THREAD

**Issue by Uckermark** [palera1n/palera1n#37]
So, when i ran `./palera1n.sh --debug` i got the output:

> palera1n | Version 1.0.0
>Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy
>Hello, iPad6,11 on 15.5!
>[*] Switching device into recovery mode...
>Telling device with udid e8e891ba80ffcaab5b1a106c3a5d5a39314bb16d to enter recovery mode.
>Device is successfully switching to recovery mode.
>[*] Waiting for device to reconnect in recovery mode
>[*] Getting device info...
>[*] Press any key when ready for DFU mode
>Get ready (0) 
>Hold volume down + side button (0) 
>Keep holding (0)
>Release side button, but keep holding volume down (0)  
>[-] Device didn't go in DFU mode, please rerun the script and try again

The device is in dfu mode though. I tested with SSHRD_Script.
Then i tried starting from dfu mode, so i ran `./palera1n.sh --dfu 15.5 --debug`

output: https://pastebin.com/79yYmVWs

the device booted into iOS, but Tips was still Tips. So no Pogo installed.
I'm on 15.5 so i can't just use TrollStore.
I used usbmuxd2 by thimstar on Ubuntu 22.04.1 LTS btw

**Comment by Uckermark** [comment]
Thanks. It worked with SSHRD_Script.

lsusb is installed.

I also had problems like #35 and fixed it by dumping the blob manually and put it in the blobs/ directory. Maybe that helps you.

Should i close the issue or do you need further information regarding the dfu detection?

**Comment by itsnebulalol** [comment]
I'm thinking this is another Linux USB issue. Yes, dumping the blob manually should work since it bypasses the ramdisk.
