### ISSUE TITLE
Linux Fedora 36, iPhone SE 1st Gen IOS 15.1

### ISSUE THREAD

**Issue by Cyosai** [palera1n/palera1n#38]
[cyosai@fedora ~]$ cd palera1n
[cyosai@fedora palera1n]$ '/home/cyosai/palera1n/palera1n.sh' /home/cyosai/SSHRD_Script/shsh/
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

/home/cyosai/palera1n/binaries/Linux/ideviceinfo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
/home/cyosai/palera1n/binaries/Linux/ideviceinfo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
/home/cyosai/palera1n/binaries/Linux/ideviceinfo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Hello,  on !
[*] Switching device into recovery mode...
/home/cyosai/palera1n/binaries/Linux/ideviceinfo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
/home/cyosai/palera1n/binaries/Linux/ideviceenterrecovery: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
[cyosai@fedora palera1n]$

**Comment by itsnebulalol** [comment]
Install OpenSSL 1.1, `dnf install openssl1.1`

**Comment by Cyosai** [comment]
[cyosai@fedora ~]$ cd palera1n
bash: cd: palera1n: No such file or directory
[cyosai@fedora ~]$ git clone --recursive https://github.com/itsnebulalol/palera1n && cd palera1n
Cloning into 'palera1n'...
remote: Enumerating objects: 238, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 238 (delta 74), reused 84 (delta 62), pack-reused 136
Receiving objects: 100% (238/238), 52.75 MiB | 667.00 KiB/s, done.
Resolving deltas: 100% (121/121), done.
Submodule 'ramdisk' (https://github.com/palera1n/ramdisk) registered for path 'ramdisk'
Cloning into '/home/cyosai/palera1n/ramdisk'...
remote: Enumerating objects: 1115, done.        
remote: Counting objects: 100% (119/119), done.        
remote: Compressing objects: 100% (61/61), done.        
remote: Total 1115 (delta 53), reused 109 (delta 48), pack-reused 996        
Receiving objects: 100% (1115/1115), 167.01 MiB | 903.00 KiB/s, done.
Resolving deltas: 100% (608/608), done.
Submodule path 'ramdisk': checked out '0740191f07511f97de63a5741aa8704b933c6e8c'
[cyosai@fedora palera1n]$ '/home/cyosai/palera1n/palera1n.sh' '/home/cyosai/SSHRD_Script/shsh' 
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

Hello, iPhone8,4 on 15.1!
[*] Switching device into recovery mode...
ERROR: Unable to connect to device
[cyosai@fedora palera1n]$

**Comment by Cyosai** [comment]
![Screenshot from 2022-09-26 13-21-26](https://user-images.githubusercontent.com/114384049/192340666-28e9df44-6239-4c41-b91b-73bc648f6445.png)

**Comment by Cyosai** [comment]
![Screenshot from 2022-09-26 13-22-06](https://user-images.githubusercontent.com/114384049/192340756-4dfda977-89a5-441f-9609-f1f5d6c37ac2.png)

**Comment by Cyosai** [comment]
after im installed

**Comment by Cyosai** [comment]
I inserted the file palera1n.sh to the console and copied the location of the shsh folder
