### ISSUE TITLE
stuck at creating ramdisk

### ISSUE THREAD

**Issue by Ixolaro** [palera1n/palera1n#39]
hello, when i run the script, its stuck at creating ramdisk
my output:
****@Lenovo-Thinkpad-T440p:~/palera1n$ sudo ./palera1n.sh --dfu 15.2
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk
****@Lenovo-Thinkpad-T440p:~/palera1n$ sudo ./palera1n.sh --dfu 15.2
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk

**Comment by itsnebulalol** [comment]
can you add `--debug` to the end of the command and show me the output

**Comment by Ixolaro** [comment]
/palera1n$ sudo ./palera1n.sh --dfu 15ug --deb 
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk
[*] Getting device info... this may take a second
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
Saved IM4M to work/IM4M
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-97865/96DA3A71-1A8E-43C8-AC78-64EEFAB356B3/iPad_Pro_HFR_14.8_18H17_Restore.ipsw
init done
getting: BuildManifest.plist
  0% [                                                                      0% [                                                                                                    ]
download failed
[-] An error occurred

**Comment by Ixolaro** [comment]
and i do have internet

**Comment by itsnebulalol** [comment]
Are you able to access that link

**Comment by Ixolaro** [comment]
yep

**Comment by Ixolaro** [comment]
and now its downloading the file lol

**Comment by itsnebulalol** [comment]
Maybe it was just a temporary internet/Apple outage, it happens

**Comment by Ixolaro** [comment]
when i click the link

**Comment by itsnebulalol** [comment]
Oh, uhh

**Comment by itsnebulalol** [comment]
What happened here?

> --dfu 15ug --deb

**Comment by Ixolaro** [comment]
i dunno but it sems it has not copied the "ug"

**Comment by itsnebulalol** [comment]
Alrighty
