### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Ixolaro** [palera1n/palera1n#40]
download succeeded
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000319A4240B603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000319A4240B603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 14 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c7204 : 000080d2
applying patch=0x1800c7258 : 000080d2
applying patch=0x1800c8bd4 : 200080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 14 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1  ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c7204 : 000080d2
applying patch=0x1800c7258 : 000080d2
applying patch=0x1800b38c8 : 000080d2c0035fd6
applying patch=0x1800b3918 : 000080d2c0035fd6
applying patch=0x1800f2fa8 : 000080d2c0035fd6
applying patch=0x1800c8bd4 : 200080d2
applying patch=0x1800ca10c : b8032f10
applying patch=0x180128180 : 72643d6d64302064656275673d30783230313465202d76207764743d2d31202000
applying patch=0x1800cce48 : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
main: Detected fat macho kernel
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-7195 inputted
get_amfi_out_of_my_way_patch: Found entitlements too small str loc at 0x9015f7
get_amfi_out_of_my_way_patch: Found entitlements too small str ref at 0xfeaf30
get_amfi_out_of_my_way_patch: Patching AMFI at 0xfe5df8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
error: allocate
error: Success
[-] An error occurred

**Comment by itsnebulalol** [comment]
Reclone the repo

**Comment by Ixolaro** [comment]
git clone --recursive https://github.com/palera1n/palera1n && cd palera1n ?

**Comment by Ixolaro** [comment]
ok it worked but now its stuck on the verbose boot...

**Comment by Ixolaro** [comment]
won't reboot

**Comment by Ixolaro** [comment]
i had to force reboot but it didn't apply AMFI patch so i have to do it again...

**Comment by Ixolaro** [comment]
hey, its still stuck in verbose and not applying patches

**Comment by Ixolaro** [comment]
[*] Device should now show text on screen
[*] Waiting for the ramdisk to finish booting
[*] Dumping blobs and installing Pogo
dd: warning: partial read (247 bytes); suggest iflag=fullblock
16349+35 records in
16349+35 records out
4192831 bytes (4.2 MB, 4.0 MiB) copied, 0.647661 s, 6.5 MB/s
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
Found IM4R extracting generator: ok
Saved IM4M to blobs/iPad7,3-15.2.shsh2
seputil: Gigalocker file (/mnt7/215BB2B2-3326-5007-B057-EAD9EAF0B92B.gl) doesn't exist: No such file or directory
seputil: Gigalocker initialization completed

**Comment by Ixolaro** [comment]
this time, just booted no verbose or patches

**Comment by Ixolaro** [comment]
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
[*] Pwning device
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000319A4240B603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000319A4240B603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000319A4240B603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000319A4240B603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000319A4240B603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[*] Booting device
[==================================================] 100.0%
ERROR: Unable to connect to device

**Comment by Ixolaro** [comment]
Still stuck on verbose boot help me pls :(

**Comment by itsnebulalol** [comment]
What device is this? If it’s A11 or an iPad you’ll have to go to dfu from recovery

**Comment by Ixolaro** [comment]
A10X iPad

**Comment by Ixolaro** [comment]
iPad Pro 2017 10.5 inch

**Comment by Ixolaro** [comment]
now i get this
malo@Lenovo-Thinkpad-T440p:~/palera1n$ sudo ./palera1n.sh --dfu 15.2
[sudo] password for malo: 
malo@Lenovo-Thinkpad-T440p:~/palera1n$

**Comment by Ixolaro** [comment]
just not starting the script

**Comment by Ixolaro** [comment]
Pls help

**Comment by Ixolaro** [comment]
nvm i fixed it just had to remove set -e for bash
