### ISSUE TITLE
Kernel Panic/Freeze on boot (iPad)

### ISSUE THREAD

**Issue by GeoffSI** [palera1n/palera1n#41]
I am on an (2018) iPad 9.5 6th gen Wi-F

Here is part of my log:

![IMG_0104](https://user-images.githubusercontent.com/104477485/192398350-5513bfc1-0bd8-4447-b135-bd9cdaff547c.jpg)

**Comment by itsnebulalol** [comment]
What iOS version? The patch is failing

**Comment by ServoAtya** [comment]
I have the exact same issue with iPad12.7 ipados 15.6 RC

**Comment by ServoAtya** [comment]
Tested with 15.7, same issue

**Comment by itsnebulalol** [comment]
Yeah iPads have weird issues, no idea.

**Comment by ServoAtya** [comment]
![IMG_0355](https://user-images.githubusercontent.com/94781687/192619337-6a750aea-0d15-433d-a4d9-d6718c4828d6.jpg)
With 15.7 i get a different issue, i dont get any panic output, but the boot process is freezes totally (so basically a panic)

**Comment by itsnebulalol** [comment]
I’m thinking that one of the patches are failing, specifically the could_not_authenticate_personalized_root_hash patch

**Comment by GeoffSI** [comment]
For this has occurred on both iPadOS 15.7 and 15.5b4. What’s interesting is, since ive attempted it, TrollStore won’t install on 15.5.

**Comment by ServoAtya** [comment]
> ![IMG_0355](https://user-images.githubusercontent.com/94781687/192619337-6a750aea-0d15-433d-a4d9-d6718c4828d6.jpg)
> 
> With 15.7 i get a different issue, i dont get any panic output, but the boot process is freezes totally (so basically a panic)
> 
> 

I tested it again with the latest commits on 15.7 and i got the same kernel panic output, which is the personalized root hash one, so the kernel patch is definitely broken

**Comment by perillamint** [comment]
On rootless branch, iPad A2198, Kernel panics. DIsplay does not show anything useful except

```
wlan0.A[4] halt@5945: Issueing trap Before issuing fir in halt()
```

However, it emits kernel crash log on console attached to DCSD cable.

```
======== End of iBoot serial output. ========
Ticket spinlock[0xfffffff0185c8f80] timeout after 3022848 ticks; cticket: 0x2e, nticket: 0x30, waiting for 0x2f, current owner: 0xffffffe22b484e10 (on CPU 1), start time: 1456730593, now: 1459753441, timeout: 3000000 @lock_ticket.c:306Ticket spinlock[0xfffffff0185c8f80] timeout after 3022848 ticks; cticket: 0x2e, nticket: 0x31, waiting for 0x30, current owner: 0xffffffe22b484e10 (on CPU 1), start time: 1460234433, now: 1463257281, timeout: 3000000 @lock_ticket.c:306Ticket spinlock[0xfffffff0185c8f80] timeout after 3022848 ticks; cticket: 0x2e, nticket: 0x32, waiting for 0x31, current owner: 0xffffffe22b484e10 (on CPU 1), start time: 1463738177, now: 1466761025, timeout: 3000000 @lock_ticket.c:306Invalid kernel stack pointer (probable overflow). at pc 0xfffffff017eef624, lr 0xfffffff017fd1e48 (saved state: 0xffffffe6f6d1bcb0)
          x0:  0xfffffff0185c8f80 x1:  0x0000000000000032  x2:  0xffffffe22b7c8708  x3:  0xffffffe6f6cd0100
          x4:  0x0000000000000010 x5:  0x0000000000000001  x6:  0x00000000000000e7  x7:  0xfffffff01851b0e8
          x8:  0x00000000322e0144 x9:  0x000000000000002e  x10: 0x0000000001000000  x11: 0x00000000332e0144
          x12: 0x0000000000000000 x13: 0xfffffff018561000  x14: 0xfffffff017d53511  x15: 0x000000000000000a
          x16: 0x0000000000000000 x17: 0x0000000000000001  x18: 0xfffffff017e9d000  x19: 0x0000000000000070
          x20: 0xfffffff0185c8000 x21: 0xfffffff017fd09dc  x22: 0xfffffff017d51852  x23: 0x0000000000000000
          x24: 0xffffffe6f6cd0140 x25: 0xfffffff01853c000  x26: 0x0000000000000010  x27: 0xfffffff01855d818
          x28: 0x0000000000000020 fp:  0xffffffe6f6cd0060  lr:  0xfffffff017fd1e48  sp:  0xffffffe6f6ccfe80
          pc:  0xfffffff017eef624 cpsr: 0x804003c4         esr: 0x96000047          far: 0xffffffe6f6ccfe60
```
