### ISSUE TITLE
Problem Palera1n v2.0.0-beta.9.1 jailbreak for iBridge 5.0-8.4

### ISSUE THREAD

**Issue by thanhlapvn** [palera1n/palera1n#410]
Hello everybody!
I have a problem with the most recently updated Palera1n v2.0.0-beta.9.1 for iBridge 5.0-8.4

I tried jailbreaking iBridge 8.1 and 8.4 all log things done but can't ssh
iproxy 2222 44 or 22
ssh -p 2222 root@localhost
Cannot open port

please answer and help me fix it.
Thank everybody

**Comment by ssalggnikool** [comment]
palera1n beta 9.1 does not have proper iBridge support! iBridge support is only available via our main branches.

Please refer to a previous comment made by Nick Chan here: https://github.com/palera1n/palera1n/commit/275eaeba9623d93bf3e6dfc92e7b25ae522553e9#commitcomment-140760973

> Hi! please use binaries from https://cdn.nickchan.lol/palera1n/artifacts/c-rewrite//main/401/binaries/ and do `./palera1n -f --cli`

**Comment by thanhlapvn** [comment]
Thank you Sir replied
binaries working, but try password "alpine" not working
What password does it use, please?
https://cdn.nickchan.lol/palera1n/artifacts/c-rewrite//main/401/binaries/ and
do ./palera1n -f --cli

Last login: Tue Apr  9 10:59:16 on ttys011

***@***.*** ~ % ssh -p2222 ***@***.***

***@***.***'s password:

Permission denied, please try again.

***@***.***'s password:

Permission denied, please try again.

***@***.***'s password:

***@***.***: Permission denied (publickey,password).

***@***.*** ~ % ssh -p2222 ***@***.***

***@***.***'s password:

Permission denied, please try again.

***@***.***'s password:



Vào Th 3, 9 thg 4, 2024 vào lúc 10:46 Samara ***@***.***>
đã viết:

**Comment by asdfugil** [comment]
user root
port 44
password alpine

bridgeOS ssh does not use port 2222, so you are probably sshing into something else
