### ISSUE TITLE
Anyone having issues with Sileo GPG signature validation after yesterdays updates? 

### ISSUE THREAD

**Issue by foxnoodles** [palera1n/palera1n#411]
### Device

iPhone X

### Version

16.5

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

Yesterday there were like 28-30 lib updates from Nick Chan in Sileo. I updated them. 

- 1st issue is the Bash postist script throws error at line 7 when it calls for "add-shell" - permission is denied. 
- 2nd issue is that Sileo can't update sources and throws invalid GPG signature errors. 
- 3rd issue - I can't install - unninstall - or downgrade anything. 

What the hell? why ? 

I'm using Beta 7 on Linux (works fine all the time so I never updated my bootable usb)

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by asdfugil** [comment]
update autosign with apt by `apt install autosign=2.0.3`, then `apt reinstall gnupg`

**Comment by foxnoodles** [comment]
Didn't help. Sileo can't install or uninstall anything. Zebra does but bash.postinst still returns error and fudges things up

**Comment by asdfugil** [comment]
reinstall bash with apt

**Comment by foxnoodles** [comment]
method https died un

> reinstall bash and debianutils with apt

`method https has died unexpectedly sub-process https received signal 6`

Yeah man... I so pissed right now. So someone just randomly f-ed up my entire setup and I can't fix it. I will have to restore and rejailbreak my main device. great.!
