### ISSUE TITLE
installing sileo/zebra

### ISSUE THREAD

**Issue by TryhardPickles** [palera1n/palera1n#412]
### Device

iPad 7th Gen

### Version

iOS 17.2

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

i booted into jailbreak, i got the app, now i can't install sileo because of
`Unable to fetch file`

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by TryhardPickles** [comment]
i checked it again for more detail, the code is -1200. any answers?
thanks.

**Comment by ssalggnikool** [comment]
Would you mind sharing what palera1n version you're currently using?

**Comment by ssalggnikool** [comment]
Right, can you try once again and show a screenshot of what exactly you're getting? Usually it provides more details than what the person usually describes it as

**Comment by ssalggnikool** [comment]
Any updates?

**Comment by TryhardPickles** [comment]
Hi. I thought I commented through my alt?

**Comment by khcrysalis** [comment]
Not entirely sure what you mean, but still can you provide a screenshot...?

This issue has been opened for a month now with no further responses.

**Comment by Ch0pin** [comment]
I am getting the same error for both sileo and zebra

**Comment by Ch0pin** [comment]
<img width="464" alt="Screenshot 2024-05-30 at 14 19 08" src="https://github.com/palera1n/palera1n/assets/4659186/71205e9e-775c-4443-9c12-787e28fe1020">
@khcrysalis

**Comment by Ch0pin** [comment]
works now

**Comment by khcrysalis** [comment]
> works now

Was there anything you changed to make it the result be different?

**Comment by Ch0pin** [comment]
No, it is probably an issue with the static.palera.in server, seems not to responding. After trying a couple of times it did.

**Comment by TryhardPickles** [comment]
I realized it was a problem with the school’s cybersecurity thing. Sorry if I wasted your time
