### ISSUE TITLE
cant go into DFU mode , try 100 times 

### ISSUE THREAD

**Issue by usaama13** [palera1n/palera1n#413]
### Device

iPhone 7 plus

### Version

IOS 15.7.9

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

can do jailbreak , try 100 time to go from
<img width="557" alt="Screenshot 2024-04-17 at 9 44 21 PM" src="https://github.com/palera1n/palera1n/assets/167349283/72c8acc8-a247-49f9-8c37-cab5861e4159">
 recovery to DFU not working 

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by ssalggnikool** [comment]
Explain in further detail on what exactly are you using to jailbreak, i.e. what mac/pc and what type of cable you're using

**Comment by usaama13** [comment]
I am using MacBook and lighting cable

**Comment by TryhardPickles** [comment]
are you letting go of the home button when it changes to hold home button?

**Comment by usaama13** [comment]
This is 7 plus , so I hold the side power and volume down , then keep hold the volume after

**Comment by ssalggnikool** [comment]
> I am using MacBook and lighting cable 

Can you show an image of your cable if possible? In palera1n's github readme, it states if you have a certain type of cable it can fail to enter DFU mode. I'm just making sure what type of cable you have in case its that problem.

**Comment by usaama13** [comment]
![IMG_0002](https://github.com/palera1n/palera1n/assets/167349283/476cff41-0467-4784-bf8e-1db46dbea1d1)

**Comment by ssalggnikool** [comment]
Yup, this is the cable I'm talking about which makes you fail to enter DFU mode, I would recommend you get another cable, preferably that looks like this ![image](https://github.com/palera1n/palera1n/assets/97859147/474d63c0-4229-41e0-9569-6c9643088fc0)

**Comment by usaama13** [comment]
thank you , Jailbreak done
