### ISSUE TITLE
Can't jailbreak - libirecovery error -3 on 

### ISSUE THREAD

**Issue by ktor-vi** [palera1n/palera1n#416]
### Device

iPhones 7/8

### Version

iOS 16

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

 - [05/15/24 08:49:11] <Warning>: Whoops, device did not enter DFU mode
 - [05/15/24 08:49:11] <Info>: Waiting for device to reconnect...
 - [05/15/24 09:03:52] <Info>: Press Enter when ready for DFU mode
 - [05/15/24 09:04:12] <Error>: libirecovery error: -3 (Unable to connect to device)
 - [05/15/24 09:04:12] <Error>: Cannot set auto-boot back to true

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by hg13bs** [comment]
If this is on Linux, check if you ran the usbmuxd commands outlined in the guide. But I'm not sure what system you are on etc.

**Comment by ktor-vi** [comment]
I solved it using a usb-A cable

**Comment by khcrysalis** [comment]
> [!NOTE] 
> Next time if you create an issue and find a solution on your own, I would recommend posting an update on your situation here so people know that you've solved it.

I'm glad you were able to find the solution you were looking for :), happy jailbreaking!
