### ISSUE TITLE
iPhoneX can not creat fakefs

### ISSUE THREAD

**Issue by cctv0x01** [palera1n/palera1n#417]
### Device

iPhoneX

### Version

iOS 16.7.8

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

I have tried it several times. After I execute `/palera1n_2.0.0-beta.9.1_universal -cf`,the phone is stuck in this page.
![image](https://github.com/palera1n/palera1n/assets/28697340/1da4edf0-1dec-472d-9168-fc0d6183b542)

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by ElliesSurviving** [comment]
fakefs creation is broken on iOS 16.x on the latest palera1n, please use rootless

**Comment by LoSei2** [comment]
I'm having the same problem but I'm using A11. I've tried using rootless and booting into pongoos and it turns on like normal. Nothing has changed or there will be any additional apps. Please give me some advice. Thank you.

**Comment by khcrysalis** [comment]
> I'm having the same problem but I'm using A11. I've tried using rootless and booting into pongoos and it turns on like normal. Nothing has changed or there will be any additional apps. Please give me some advice. Thank you.

If you're jailbroken you should be able to run this and get into the iPhone:
```
ssh root@127.0.0.1 -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -o "ProxyCommand=inetcat 44"
```

> Password: `alpine`

After getting into the phone you should be able to run this
```
uicache -fp /cores/binpack/Applications/palera1nLoader.app
```

Though if not, I would recommend sending any panic logs if possible from `Settings > Privacy > Analytics & Improvements > Analytics Data`

**Comment by LoSei2** [comment]
> > ฉันมีปัญหาเดียวกัน แต่ฉันใช้ A11 ฉันได้ลองใช้ rootless และบูตเป็น pongoos และมันก็เปิดเหมือนปกติ ไม่มีอะไรเปลี่ยนแปลงหรือจะมีแอพเพิ่มเติมใด ๆ ขอคําแนะนําหน่อยครับ ขอบคุณ
> 
> หากคุณเจลเบรคคุณควรจะสามารถเรียกใช้สิ่งนี้และเข้าสู่ iPhone:
> 
> ```
> ssh root@127.0.0.1 -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -o "ProxyCommand=inetcat 44"
> ```
> 
> > รหัสผ่าน: `alpine`
> 
> หลังจากเข้าสู่โทรศัพท์คุณควรจะสามารถเรียกใช้สิ่งนี้ได้
> 
> ```
> uicache -fp /cores/binpack/Applications/palera1nLoader.app
> ```
> 
> แม้ว่าถ้าไม่ฉันขอแนะนําให้ส่งบันทึกความตื่นตระหนกถ้าเป็นไปได้จาก `Settings > Privacy > Analytics & Improvements > Analytics Data`

Thank you for your help. I've never used linux before. Can I use those commands in the terminal on linux?

**Comment by hg13bs** [comment]
@LoSei2 first command yea, the 2nd command is after you get to the phone's shell

**Comment by LoSei2** [comment]
![Screenshot_2024-05-27_12-01-05](https://github.com/palera1n/palera1n/assets/113410478/3f15f1f4-feb3-488c-a019-2e9d3e06750e)

I'm not sure if I do this or not. Please explain this in more detail. I am a newbie

**Comment by wynwxst** [comment]
> ![Screenshot_2024-05-27_12-01-05](https://private-user-images.githubusercontent.com/113410478/333970553-3f15f1f4-feb3-488c-a019-2e9d3e06750e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTk4MzIsIm5iZiI6MTcxNjc5OTUzMiwicGF0aCI6Ii8xMTM0MTA0NzgvMzMzOTcwNTUzLTNmMTVmMWY0LWZlYjMtNDg4Yy1hMDE5LTJlOWQzZTA2NzUwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QwODQ1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTc1YmNjMzg3OWFhNmZjZjE4OTQ5YWUxNGMxODU0ZTU2ZThiYjhlYzNkZDI3MWM2MmFiMzY1OTg2YmQ0MWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SHVq-tTqcexQ36P56TLSiI2XHEJsDeAJfax6s142ORk)
> 
> I'm not sure if I do this or not. Please explain this in more detail. I am a newbie

There no need for the ip iirc you just type `ssh root@127.0.0.1 -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -o "ProxyCommand=inetcat 44"` when your device is connected in.
Source:
![image](https://github.com/palera1n/palera1n/assets/57133270/db326184-ba7b-4b15-b706-1bf1fa51e93b)
from: https://palera.in/

**Comment by khcrysalis** [comment]
> I'm not sure if I do this or not. Please explain this in more detail. I am a newbie

For linux I would recommend getting libimobiledevice from here: https://static.palera.in/tools/libimobiledevice-static-linux.tar.zst

Then doing
```
mkdir libimobiledevice && tar --use-compress-program=unzstd -xvf Downloads/libimobiledevice-static-linux.tar.zst -C libimobiledevice/
```
> This would get you the necessary files needed specifically [inetcat] for what we're doing

After that you can do this command:

```
ssh root@127.0.0.1 -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -o "ProxyCommand=libimobiledevice/inetcat 44"
```
> This would open a shell on your phone, if it does work it would mean you're jailbroken.

**Comment by khcrysalis** [comment]
Also, please do not change any of the commands I send, unless specifically told to change

**Comment by LoSei2** [comment]
rootless on palen1x I will use command Where can I get such information? So when is the command used? Is the command the same?

**Comment by LoSei2** [comment]
![Screenshot_2024-05-28_16-17-09](https://github.com/palera1n/palera1n/assets/113410478/7baae51f-2a03-4fcc-9939-a25889394d59)

it show this ...

**Comment by wynwxst** [comment]
> ![Screenshot_2024-05-28_16-17-09](https://private-user-images.githubusercontent.com/113410478/334345839-7baae51f-2a03-4fcc-9939-a25889394d59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTE4NzQsIm5iZiI6MTcxNjg5MTU3NCwicGF0aCI6Ii8xMTM0MTA0NzgvMzM0MzQ1ODM5LTdiYWFlNTFmLTJhMDMtNGZjYy05OTM5LWEyNTg4OTM5NGQ1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMDE5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDE4NWUwNjJiNjhhMjJjZGJjYWM5MmE2N2VkNGI0OTdjNmU2MWFhNzkzNTBkZDQ5ODkwNzg2MjdhM2FiZDQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.saIkmYp211VWQYnENp0xX_JGvAu94w109M0SeTj2zio)
> 
> it show this ...

You need to get libimobiledevice from the link Samara recommended, or through your own installation
Example using Samara's link:
```bash
mkdir libimobiledevice
curl https://static.palera.in/tools/libimobiledevice-static-linux.tar.zst -o libimobiledevice.tar.zst
tar --zstd -xvf ./libimobiledevice.tar.zst # you will need zstd installed for this using 'sudo apt install zstd'
cd ..
ssh root@127.0.0.1 -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -o "ProxyCommand=./libimobiledevice/inetcat 44"


```

**Comment by khcrysalis** [comment]
FYI: this is only to check if you're actually jailbroken, I don't exactly know if theres any other problems as you're not being that specific.

**Comment by khcrysalis** [comment]
I would also recommend you create a new issue as this isn't originally your issue either.

**Comment by khcrysalis** [comment]
Anyone here can test this new build? https://github.com/palera1n/palera1n/releases/tag/v2.0.0-beta.9.2 to see if rootful works

**Comment by wynwxst** [comment]
> Anyone here can test this new build? https://github.com/palera1n/palera1n/releases/tag/v2.0.0-beta.9.2 to see if rootful works

sure

**Comment by AkaShark** [comment]
> ### Device
> iPhoneX
> 
> ### Version
> iOS 16.7.8
> 
> ### Passcode?
> * [ ]  Passcode is enabled.
> 
> ### Start going into detail..
> I have tried it several times. After I execute `/palera1n_2.0.0-beta.9.1_universal -cf`,the phone is stuck in this page. ![image](https://private-user-images.githubusercontent.com/28697340/331773413-1da4edf0-1dec-472d-9168-fc0d6183b542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MDk4NjIsIm5iZiI6MTczMDkwOTU2MiwicGF0aCI6Ii8yODY5NzM0MC8zMzE3NzM0MTMtMWRhNGVkZjAtMWRlYy00NzJkLTkxNjgtZmMwZDYxODNiNTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE2MTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MTVjNmU4ODM5NWUyMDFlNWU2YjI2NGQyMjk4MDJkYmIzNzFmNGViYTEzYjlhMjc0NWZkMmUyMjBhYjNiYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ObOLzBBtwIz6gGwJZ9cLG7Q9ryAGF_WeCQrnN0Pw-YI)
> 
> ### Familiarity with palera1n
> * [x]  I am familiar with palera1n and how to use it!
> 
> ### Familiarity with CLI
> * [ ]  I am familiar with the command-line!

I encountered a similar problem, but I can't exit this page now. Can you please tell me how to exit this page on my phone?
