### ISSUE TITLE
You need to add a step to the official guide to prevent a specific error

### ISSUE THREAD

**Issue by Ender890** [palera1n/palera1n#418]
### Device

iPhone 7

### Version

ios 15.8.1

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

after the systemd usbmux step, you need to add this please:

 sudo systemctl mask fwupd-offline-update.service 
 sudo systemctl mask fwupd-refresh.service 
 sudo systemctl mask fwupd-refresh.timer 
sudo systemctl mask fwupd.service 

thanks, otherwise the iphone fails to enter download mode after exiting DFU via CLI

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by IvenPS** [comment]
Hi! This can solve the download mode error? (On mi ipad only still on black screen and dont do nothing, only appear that error)

**Comment by khcrysalis** [comment]
This seems like a more temporary solution than a proper fix dont you think?
