### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by karamzaki2020** [palera1n/palera1n#42]
main: Detected fat macho kernel
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-8020 inputted
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x9a7061
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x10b0c64
get_amfi_out_of_my_way_patch: Patching AMFI at 0x10ac2a8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
0x10ac2c4 0xfd 0xe0
0x10ac2c5 0x7b 0x3
0x10ac2c6 0xbf 0x0
0x10ac2c7 0xa9 0x32
0x10ac2c8 0xfd 0xc0
0x10ac2ca 0x0 0x5f
0x10ac2cb 0x91 0xd6
krnl
dtre
rtsc
rdsk
/dev/disk4          	                               	/private/tmp/SSHRD
hdiutil: couldn't eject "disk2" - Resource busy
[-] An error occurred

**Comment by itsnebulalol** [comment]
Go into finder and eject the ramdisk, then try again
