### ISSUE TITLE
Please release new linux distribution using 0.1337.2 (ver. 2024.05.14)

### ISSUE THREAD

**Issue by pig837** [palera1n/palera1n#420]
### Feature Description

Please release new linux distribution using 0.1337.2 (ver. 2024.05.14)

### Start going into detail..

Hi, I saw new 0.1337.2 release note.

![image](https://github.com/palera1n/palera1n/assets/10391680/276124ea-6059-4cde-82fd-2913c2f7a2e5)

Note: the linux builds were updated on 14. May 2024.
The old builds erroneously used dynamic linking, which limited them to systems that use glibc. The new builds use static linking like previous releases did. The old builds can still be accessed at:

https://assets.checkra.in/downloads/preview/0.1337.2/old/...

- https://checkra.in/1337

**Comment by khcrysalis** [comment]
We were the ones that requested directly for this to be fixed :). Nightly builds already have these builds of checkra1n 1337 included near https://github.com/palera1n/palera1n/commit/0e9cd5e1f67101616be9dbded8ac8a82ef35a939,and will be present in the next beta/release. Though, thank you for trying to point it out.
