### ISSUE TITLE
iPhone X ( ios 16.7.8 ) rootful jailbreak is not working.

### ISSUE THREAD

**Issue by kaanzapkinus** [palera1n/palera1n#422]
### Device

iPhone X

### Version

IOS 16.7.8

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

Hello,

I was using palera1n on ios 15.7 for 2 months, i had no problems.

Yesterday, I updated my iPhone X to iOS 16.7.8 (from 15.7). I am using jailbreak for GPS spoofing on the Uber driver app, which is important for me. Uber required iOS 16.2 for a recent update, so I updated. However, the problem is that iOS 16.7.8 was just released two weeks ago.

I believe this is why the recent version of Palera1n is not working on this version. I've tried to use the prior version of Palera1n. I can successfully create FakeFS, but when the phone boots with Palera1n, I have no Wi-Fi connection. Additionally, if I download my GPS spoofing app (Fake Location from the BigBoss repository), the phone resets itself after 5 minutes.

I think it's impossible to roll back my iPhone version anymore. So, is Palera1n going to release a new version for iOS 16.7.8 rootful? I've seen some similar issues where people are asking for help. I've also visited the JB Discord. People tried to help me a lot, but we couldn't make it work with my iPhone.

Note: I erased my iPhone a few times last night and tried different versions of Palera1n. Also, I had no passcode enabled; it was disabled all the time.

Thank you.

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
Can you say which pc OS you have?

**Comment by khcrysalis** [comment]
I assume palen1x correct for the windows computer?

**Comment by Mekane89** [comment]
No Because I've been trying since with my iPhone X of the same impossible
version of jailbreak


Envoyé avec Gmail Mobile

**Comment by khcrysalis** [comment]
> Yes I do have the correct palen1x, also i've tried recent version but it didnt work well. So I've used version before than the recent one. It did work but not working good.

Palen1x should have a feature to 'SSH' on the main menu
```
user:      root
port:      22
password:  alpine
```

After you get into the phone (while jailbroken with an older version), you would need to type `launchctl reboot userspace`

**Comment by khcrysalis** [comment]
Sileo doesn't give good error messages when it comes to this, so I would prefer you use a command line and see what actually is going on.

```
sudo dpkg -a --configure
sudo apt install -f
``` 
Possibly? When SSH'd into the iPhone.

**Comment by wynwxst** [comment]
> > Sileo doesn't give good error messages when it comes to this, so I would prefer you use a command line and see what actually is going on.
> > ```
> > sudo dpkg -a --configure
> > sudo apt install -f
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Possibly? When SSH'd into the iPhone.
> 
> Do i have to use these codes on ssh? I can try tomorrow And, do you think if palera1n would release a new version to fix this? And yes, how often does he/she release new updates?

Assumably, yes since you can't install tweaks you will have to use ssh. Also as far as I know, there is a refactor of palera1n arriving at a certain point.

**Comment by khcrysalis** [comment]
Unlikely that palera1n may be able to fix this as this issue is also a known issue with checkra1n, maybe if we knew the exact cause of it (which we do not) then there's no chance at this very point.

Though, this issue is very rare and only has happened to a handful of people in some occasions.

**Comment by pig837** [comment]
You can jailbreak rootful mode using palera1n v2.0.0 beta 7
- https://github.com/palera1n/palera1n/releases/tag/v2.0.0-beta.7

Please don't use from v2.0.0 beta 8: Dusk version

**Comment by khcrysalis** [comment]
> Rootful has some issue (You must use only Ellekit currently, bcz Substitute was deleted by repo maintainer)
We deleted substitute because we thought ellekit would be a good replacement for it, but I'm not sure if theres actually any *real* issues as it works fine with rootless already.

If you can report a real issue thats been happening (thats not a user issue) then it would be greatly appreciated.

**Comment by khcrysalis** [comment]
> Please don't use from v2.0.0 beta 8: Dusk version (Not working)

Can you report whats specifically not working..?

**Comment by pig837** [comment]
> w

Substitute has no issues with Frida, but Ellekit has a issue with Frida.

An App on my iPhone 8 Plus (iOS 16.7.8) may been crashed by Ellekit.

Nothing problem with Frida on Substitute.

**Comment by khcrysalis** [comment]
> Nothing problem with Frida on Substitute.

I see, I can possibly add substitute back if this can satisfy those people that use frida, I have no problem with that

**Comment by sunday-mayweather** [comment]
For those who are struggling to jailbreak rootfully iPhone X on iOS 16.7.8 with Palerain, this is how I managed to do it:
1. First Create `fakeFS` using palerain [v2.0.0-beta.7](https://github.com/palera1n/palera1n/releases/tag/v2.0.0-beta.7):
```sh
palera1n-7 -c -f
```
2. Now, if you use `beta.7` to jailbreak, tweaks won't work. Thus, you need to jailbreak using palerain [v2.0.0-beta.9.1](https://github.com/palera1n/palera1n/releases/tag/v2.0.0-beta.9.1):
```sh
palera1n-9.1 -f
```

**Comment by khcrysalis** [comment]
Anyone here can test this new build? https://github.com/palera1n/palera1n/releases/tag/v2.0.0-beta.9.2 to see if rootful works

**Comment by HerePescador** [comment]
IPhone 7 com problemas, tem instalado o dopamine junto com o GPS Master, para pesca, com o  app da Uber mas agora, apareceu mensagem de erro pedindo para atualizar e não deixa ficar online...
