### ISSUE TITLE
Jailbreak dies after restart

### ISSUE THREAD

**Issue by ajarcon** [palera1n/palera1n#426]
### Device

iphone X

### Version

IOS 16.7.8

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

After jailbreaking i had to install some apps and one needed a restart and after restarting all the apps either don't work(opens then crashes) or disappears entirely  and for some reason i cant uninstall trollstore

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by asdfugil** [comment]
This is expected behavior. Please run the tool again after restart.
