### ISSUE TITLE
The device won't boot after patching

### ISSUE THREAD

**Issue by 1-hexene** [palera1n/palera1n#43]
```
Hello, iPhone8,1 on 15.6!
[*] Switching device into recovery mode...
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Pwning device
[*] Booting device

Done!
The device should now boot to iOS
```

However, it didn't boot and remains in DFU mode after this.
The device did boot the first time jailbreaking, the logo appeared, and iOS booted in verbose mode, but it did not enter the desktop (and remains in black screen).
When I jailbreak the device next time, it simply doesn't boot.

**Comment by 1-hexene** [comment]
PS I use OSX 13 beta. Will this OS version affect the Jailbreaking process?

**Comment by itsnebulalol** [comment]
No, my main device is on Ventura too

Please run `./palera1n.sh clean` and try again

**Comment by 1-hexene** [comment]
I upgraded my device to iOS 15.7 and the system successfully booted after patching. I do not think palera1n will work on a beta version of iOS 15.

**Comment by itsnebulalol** [comment]
> I do not think palera1n will work on a beta version of iOS 15.

It should but you'd have to manually set the ipsw URL in the code
