### ISSUE TITLE
No palera1n loader

### ISSUE THREAD

**Issue by imboii** [palera1n/palera1n#434]
### Description

I have jailbroke my iPhone 8+ but couldn’t find the palera1n loader app or any kind off sign that my phone was jailbroken my iOS is 16.7.8 I would like some help

**Comment by TryhardPickles** [comment]
try it again

**Comment by imboii** [comment]
I did and it still not appeared but I fixed it

**Comment by khcrysalis** [comment]
> I did and it still not appeared but I fixed it

If you fixed it please provide a solution instead of closing the issue without any context or information on how you did to fix it.

**Comment by imboii** [comment]
I forgot to factory reset it
