### ISSUE TITLE
TV4K jailbreaking issue

### ISSUE THREAD

**Issue by kasimok** [palera1n/palera1n#435]
### Device

Apple TV 4K Gen 1

### Version

tvOS 17.4

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

With the help of DCSD cable and Golden Eye cable, I'm trying the jailbreaking on TVOS.

![IMG_8118](https://github.com/palera1n/palera1n/assets/5194603/3b20ae8c-8aaf-4463-a6c3-db87d0c6eb81)

1. Connect Apple TV's Ethernet to Golden Eye Adaptor.
2. Connect Golden Eye's Lightning port to DCSD adapter.
3. Connect DCSD cable's USB-A to macOS, you may need USB-A to USB-C adaptor.
4. Boot Apple TV, and launch palera1n.
5. Apple TV Stuck at PongoOS's sep auto stage.

![IMG_8127](https://github.com/palera1n/palera1n/assets/5194603/cb678156-317e-40d2-ba69-f489a2a12d7a)

Now there are 2 questions:

1. The DFU mode cannot detect an Apple TV Device
```
palera1n
# == palera1n-c ==
#
# Made by: Nick Chan, Ploosh, Samara, Mineek, staturnz, kok3shidoll
#
# Thanks to: pythonplayer123, llsc12, Nebula, tihmstar, nikias
# (libimobiledevice), checkra1n team (Siguza, axi0mx, littlelailo
# et al.), Procursus Team (Hayden Seay, Cameron Katri, Keto et.al)

 - [06/24/24 08:38:15] <Info>: Waiting for devices
 - [06/24/24 08:38:16] <Info>: Press Enter when ready for DFU mode

Get ready (0)
Hold home + power button (1)
 - [06/24/24 08:38:49] <Info>: Device entered DFU mode successfully
 - [06/24/24 08:38:49] <Info>: About to execute checkra1n
#
```
According to https://github.com/palera1n/palera1n/blob/a4eacb75c076365718652de69e35d315e6e3692f/src/dfuhelper.c#L39, we should prompt: `Hold menu + play button` for Apple TV.

2. The PangoOS stuck at `sep auto`

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
Judging from your palera1n log output it seems that you're using a beta version of palera1n which does not currently have tvOS support.

Could you try using the binaries located in https://cdn.nickchan.lol/palera1n/artifacts/c-rewrite/main/448/ ?

`/path/to/palera1n -f --cli`

**Comment by kasimok** [comment]
Made it, thanks for the nighty builds.

**Comment by khcrysalis** [comment]
> Made it, thanks for the nighty builds.

I assume it successfully jailbroken, if so then congratulations! If you have any feedback or requests please open a new issue as this is still extremely new!
