### ISSUE TITLE
asking for username

### ISSUE THREAD

**Issue by Isaihacksschoollaptops** [palera1n/palera1n#436]
### Description

when trying ot do sudo git clone palerainpalerain something like that correctly its asking for a passwird

**Comment by khcrysalis** [comment]
Hey, I just wanna let you know that general support on like trying to git clone a repo should be redirected to your own research online. For example, github documentation provides many examples and tips on how to clone a repository effectively without needing to jump through unnecessary hoops.

> https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository

> https://www.google.com/search?q=git+cloning+asks+for+password

> https://docs.github.com/en/get-started/getting-started-with-git/why-is-git-always-asking-for-my-password
