### ISSUE TITLE
homebrew tap

### ISSUE THREAD

**Issue by eliekh05** [palera1n/palera1n#437]
### Feature Description

i want you to create an homebrew tap for all your palera1n releases 

### Start going into detail..

i want you to create an homebrew tap for all your palera1n releases

**Comment by khcrysalis** [comment]
We *could* do this but what use case would this really serve? There's already a valid and easy method of downloading the palera1n binary through our site (which is already done automatically as it fetches the latest github release)

**Comment by eliekh05** [comment]
> We *could* do this but what use case would this really serve? There's already a valid and easy method of downloading the palera1n binary through our site (which is already done automatically as it fetches the latest github release)

most people like me use homebrew that because it can save to /usr/local/bin

**Comment by dylanmccune** [comment]
i like homebrew
