### ISSUE TITLE
Device can't connect to server or can't download packages

### ISSUE THREAD

**Issue by delmarocks** [palera1n/palera1n#438]
### Device

iPhone 7

### Version

iOS 15.8

### Passcode?

- [X] Passcode is enabled.

### Start going into detail..

Device after jailbreak can't access internet, mobile data is active though I can browse internet through iphone's hotspot, but can't use it on my device. I can download package manager like sileo but can't install packages even browsing through safari it says "can't connect to server".
![17194911174647320267730745851323](https://github.com/palera1n/palera1n/assets/31096473/e6a5574a-beea-4eb6-b347-e4f8c2168a7e)
![17194911901852912280798015406111](https://github.com/palera1n/palera1n/assets/31096473/08bc987a-10f3-48e9-a289-9f3f1265ac41)
![Uploading 17194914212818243393783753315946.jpg…]()

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
If the wifi toggle greyed out? For example not letting you toggle it on?

**Comment by delmarocks** [comment]
> If the wifi toggle greyed out? For example not letting you toggle it on?

I can toggle wifi and can connect AP's. Wifi is working properly.
