### ISSUE TITLE
Can you help me build a 1.4.2 version for mac arm64, because it can make my plugin run stably

### ISSUE THREAD

**Issue by Aibric** [palera1n/palera1n#439]
### Description

Can you help me build a 1.4.2 version for mac arm64, because it can make my plugin run stably， thanks

**Comment by Aibric** [comment]
> ### Description
> Can you help me build a 1.4.2 version for mac arm64, because it can make my plugin run stably， thanks
I accidentally deleted my previous version 1.4.2

**Comment by khcrysalis** [comment]
> ### Description
> 
> Can you help me build a 1.4.2 version for mac arm64, because it can make my plugin run stably， thanks

Palera1n version 1.X is no longer maintained. Please stick with using our beta versions.

https://github.com/palera1n/palera1n/releases/tag/v2.0.0-beta.9.2
