### ISSUE TITLE
boots without AMFI patches

### ISSUE THREAD

**Issue by Ixolaro** [palera1n/palera1n#44]
hey, after i run the script, it just shows apple logo and boots without patches

**Comment by itsnebulalol** [comment]
Please run `./palera1n.sh clean` then run the normal palera1n command but with `--debug` added. then, send me the log

**Comment by Ixolaro** [comment]
download succeeded
                                             usb_timeout: 5
                                                           [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
                                                 CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000319A4240B603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3] PWND:[gaster]
                       Found the USB handle.
                                            Now you can boot untrusted images.
    [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
     Found the USB handle.
                          usb_timeout: 5
                                        [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
                              CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000319A4240B603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3] PWND:[gaster]
    Found the USB handle.
                         Now you can boot untrusted images.
                                                           [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
                                                 Found the USB handle.
                                                                      main: Starting...
             iOS 14 iBoot detected!
                                   getting get_debug_enabled_patch() patch
           getting get_sigcheck_patch() patch
                                             applying patch=0x1800c7204 : 000080d2
        applying patch=0x1800c7258 : 000080d2
                                             applying patch=0x1800c8bd4 : 200080d2
        main: Writing out patched file to work/iBSS.patched...
                                                              main: Quitting...
                none
                    main: Starting...
                                     iOS 14 iBoot detected!
                                                           getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1  ) patch
                                                   getting get_debug_enabled_patch() patch
                getting get_unlock_nvram_patch() patch
                                                      getting get_sigcheck_patch() patch
                         applying patch=0x1800c7204 : 000080d2
                                                              applying patch=0x1800c7258 : 000080d2
                         applying patch=0x1800b38c8 : 000080d2c0035fd6
                                                                      applying patch=0x1800b3918 : 000080d2c0035fd6
                                         applying patch=0x1800f2fa8 : 000080d2c0035fd6
                       applying patch=0x1800c8bd4 : 200080d2
                                                            applying patch=0x1800ca10c : b8032f10
                       applying patch=0x180128180 : 72643d6d64302064656275673d30783230313465202d76207764743d2d31202000
                                            applying patch=0x1800cce48 : 1f2003d5
                  main: Writing out patched file to work/iBEC.patched...
                                                                        main: Quitting...
               none
                   krnl
                       main: Starting...
                                        main: Detected fat macho kernel
                                                                       Kernel: Adding AMFI_get_out_of_my_way patch...
                                           get_amfi_out_of_my_way_patch: Entering ...
                      get_amfi_out_of_my_way_patch: Kernel-7195 inputted
                                                                        get_amfi_out_of_my_way_patch: Found entitlements too small str loc at 0x9015f7
  get_amfi_out_of_my_way_patch: Found entitlements too small str ref at 0xfeaf30
                 get_amfi_out_of_my_way_patch: Patching AMFI at 0xfe5df8
                                                                        main: Writing out patched file to work/kcache.patched...
                                                      main: Quitting...
                                                                       krnl
 dtre
     rtsc
         rdsk
             none
                 none

                     [*] Cleaning up work directory
                                                   [*] Booting ramdisk
       [*] Getting device info... this may take a second
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
                                                           [*] Device should now show text on screen
                          [*] Waiting for the ramdisk to finish booting
                                                                       [*] Dumping blobs and installing Pogo
                                  dd: warning: partial read (247 bytes); suggest iflag=fullblock
                                 16346+38 records in
                                                    16346+38 records out
                                                                        4192818 bytes (4.2 MB, 4.0 MiB) copied, 0.837302 s, 5.0 MB/s
                                                          img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
                                                        Compiled with plist: YES
                 Found IM4R extracting generator: ok
                                                    Saved IM4M to blobs/iPad7,3-15.2.shsh2
                seputil: Gigalocker file (/mnt7/215BB2B2-3326-5007-B057-EAD9EAF0B92B.gl) exists
                     seputil: Gigalocker initialization completed
  seputil: can't open '/mnt6//usr/standalone/firmware/sep-firmware.img4', errno: No such file or directory(2)
                                   seputil: rejecting zero-byte firmware
                                                                        seputil: failed to load /mnt6//usr/standalone/firmware/sep-firmware.img4 in  mode

**Comment by Ixolaro** [comment]
this is the end of log but idevice does not continue

**Comment by itsnebulalol** [comment]
What iOS version is this

**Comment by Ixolaro** [comment]
stuck at verbose iPadOS 15.2

**Comment by Ixolaro** [comment]
have not futurestores recently and its A10X so i disabled passcode

**Comment by itsnebulalol** [comment]
Boot [SSHRD_Script](https://github.com/verygenericname/SSHRD_Script), run `mount_filesystems` in the ssh session, run `ls /mnt6`, then copy the name of the UUID (probably something like IU43YT873N78CN487CY38Y87UFIEIWUFIUE), then run `echo "THAT UUID" > /mnt6/active`. Reboot, then try to run palera1n again. No idea why some devices just don't have an active file

**Comment by Ixolaro** [comment]
sudo ./sshrd.sh ssh
Creating listening port 2222 for device port 22
kex_exchange_identification: Connection closed by remote host
Connection closed by 127.0.0.1 port 2222
[-] An error occurred
[-] uploading logs, if this fails, it's not a big deal.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--  100   464    0    83  100   381     93    429 --:--:-- --:--:-- --:--:--   523
[!] Done uploading logs, i'll be sure to look at them and fix the issue you are facing

**Comment by itsnebulalol** [comment]
:uhh: linux USB moment. type these commands in another terminal window, then try again:
```
sudo systemctl stop usbmuxd
killall iproxy
sudo killall iproxy
sudo usbmuxd -f -p
```

**Comment by Ixolaro** [comment]
same log :(

**Comment by Ixolaro** [comment]
maybe while verbose i run the script

**Comment by itsnebulalol** [comment]
wdym

**Comment by Ixolaro** [comment]
when palera1n boots, it does not rebbot after verbose, and if i run while verbose sshrd script could connect to device

**Comment by Ixolaro** [comment]
ok palera1n isn't booting in palera1n mode anymore even woith sudo ./palera1n clean

**Comment by Ixolaro** [comment]
nvm

**Comment by itsnebulalol** [comment]
What does usbmuxd in the other terminal say

**Comment by Ixolaro** [comment]
I dunno, i cannot answer im in school

**Comment by GeoffSI** [comment]
> sudo ./sshrd.sh ssh
> 
> Creating listening port 2222 for device port 22
> 
> kex_exchange_identification: Connection closed by remote host
> 
> Connection closed by 127.0.0.1 port 2222
> 
> [-] An error occurred
> 
> [-] uploading logs, if this fails, it's not a big deal.
> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> 
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--  100   464    0    83  100   381     93    429 --:--:-- --:--:-- --:--:--   523
> 
> [!] Done uploading logs, i'll be sure to look at them and fix the issue you are facing
> 
> 

I had this issue on macOS.

**Comment by GeoffSI** [comment]
> iPads have known issues, some just don't work with palera1n as of now. Have you futurerestored recently? You don't have an active file.

Question? If you did use FutureRestore recently would that be a bad thing?

**Comment by Ixolaro** [comment]
I did not futurestore.

**Comment by Ixolaro** [comment]
it booted in verbose again, but stuck again

**Comment by itsnebulalol** [comment]
> > iPads have known issues, some just don't work with palera1n as of now. Have you futurerestored recently? You don't have an active file.
> 
> Question? If you did use FutureRestore recently would that be a bad thing?

No

**Comment by Ixolaro** [comment]
i cannot find the problem

**Comment by Ixolaro** [comment]
> Boot [SSHRD_Script](https://github.com/verygenericname/SSHRD_Script), run `mount_filesystems` in the ssh session, run `ls /mnt6`, then copy the name of the UUID (probably something like IU43YT873N78CN487CY38Y87UFIEIWUFIUE), then run `echo "THAT UUID" > /mnt6/active`. Reboot, then try to run palera1n again. No idea why some devices just don't have an active file

i have TS installed, so i can install filza

**Comment by Ixolaro** [comment]
> > Boot [SSHRD_Script](https://github.com/verygenericname/SSHRD_Script), run `mount_filesystems` in the ssh session, run `ls /mnt6`, then copy the name of the UUID (probably something like IU43YT873N78CN487CY38Y87UFIEIWUFIUE), then run `echo "THAT UUID" > /mnt6/active`. Reboot, then try to run palera1n again. No idea why some devices just don't have an active file
> 
> i have TS installed, so i can install filza

will i be able to use filza instead to do it?

**Comment by itsnebulalol** [comment]
Yes

**Comment by Ixolaro** [comment]
ok i'll try

**Comment by Ixolaro** [comment]
stuck at No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.

**Comment by Ixolaro** [comment]
and it says running server on gthe ipad screen

**Comment by Ixolaro** [comment]
and it retrys forever

**Comment by Ixolaro** [comment]
ok i fixed it and IT WORKS

**Comment by Ixolaro** [comment]
Ok it did boot up but now tips is broken and when i use pogo installed with trollstore it says faild to prepare bootstrap

**Comment by itsnebulalol** [comment]
It’s not booted with palera1n then. If booted Tips will open fine

**Comment by Ixolaro** [comment]
I did boot it with palera1n

**Comment by Ixolaro** [comment]
I don't want to boot palera1n again for some time if thederd iOS 15.2

**Comment by Ixolaro** [comment]
Unless there is an option --tweaks

**Comment by itsnebulalol** [comment]
Main branch doesn’t have it

**Comment by Ixolaro** [comment]
Ok thx gonna try that this night

**Comment by Ixolaro** [comment]
main: Quitting...
none
none
[*] Patching and signing kernelcache
Reading work/kernelcache.release.ipad7...
[NOTE] Image4 payload data is LZFSE compressed, decompressing...
Extracted Image4 payload data to: work/kcache.raw
main: Starting...
main: Detected fat macho kernel
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-8019 inputted
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str loc at 0x9aaadc
get_amfi_out_of_my_way_patch: Found Internal Error: No cdhash found. str ref at 0x1159c84
get_amfi_out_of_my_way_patch: Patching AMFI at 0x11552d8
Kernel: Adding could_not_authenticate_personalized_root_hash patch...
get_could_not_authenticate_personalized_root_hash_patch: Entering ...
get_could_not_authenticate_personalized_root_hash_patch: Found "successfully validated on-disk root hash" str loc at 0xd0bd7b
get_could_not_authenticate_personalized_root_hash_patch: Found "successfully validated on-disk root hash" xref at 0x1ed87a8
get_could_not_authenticate_personalized_root_hash_patch: Found previous cbz at 0x1ed8784
get_could_not_authenticate_personalized_root_hash_patch: Found "could not authenticate personalized root hash!" str loc at 0xd0bb3c
get_could_not_authenticate_personalized_root_hash_patch: Found "could not authenticate personalized root hash!" xref at 0x1ed883c
get_could_not_authenticate_personalized_root_hash_patch: Found cbz target at 0x1ed8830
get_could_not_authenticate_personalized_root_hash_patch: Patching root hash check at 0x1ed8830
main: Writing out patched file to work/kcache.patched...
main: Quitting...
Reading work/kcache.patched...
Compressing payload using LZSS...
IM4P outputted to: work/krnlboot.im4p
Reading work/krnlboot.im4p...
Reading work/IM4M...
Creating Image4...
Image4 file outputted to: boot-iPad7,3/kernelcache.img4
[*] Signing DeviceTree
dtre
[*] Signing AOP
File does not exist, will create BuildManifest.plist
Invalid key path (indexing into null object)
Invalid key path (no object at key path)
[e] cannot open 'work/'
malo@Lenovo-Thinkpad-T440

**Comment by Ixolaro** [comment]
ok i recloned but now i get
 sudo ./palera1n.sh --dfu 15.2 --debug
palera1n | Version 1.0.0-d8540c6
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk
Archive:  gaster-Linux.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of gaster-Linux.zip or
        gaster-Linux.zip.zip, and cannot find gaster-Linux.zip.ZIP, period.
[-] An error occurred

**Comment by Ixolaro** [comment]
okay had to delete gaster.zip and lets see if it works...

**Comment by Ixolaro** [comment]
malo@Lenovo-Thinkpad-T440p:~/Desktop/palera1n$ sudo ./palera1n.sh  15.2 --debug
palera1n | Version 1.0.0-d8540c6
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

Hello, iPad7,3 on 15.2!
[*] Switching device into recovery mode...
Telling device with udid ec88a3763450affe69fed660b46c66627a60f4cb to enter recovery mode.
Device is successfully switching to recovery mode.
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Creating ramdisk
[*] Getting device info... this may take a second
stuck at getting device info

**Comment by Ixolaro** [comment]
malo@Lenovo-Thinkpad-T440p:~/Desktop/palera1n$ sudo ./palera1n.sh --dfu  15.2 --debug
palera1n | Version 1.0.0-d8540c6
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
ERROR: Unable to connect to device
ERROR: Unable to connect to device

**Comment by Ixolaro** [comment]
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9

**Comment by RavanGami** [comment]
![image](https://user-images.githubusercontent.com/114746710/195661367-b0d85cda-1ce7-40be-a4e7-14afddb7a9d2.png)

**Comment by RavanGami** [comment]
![image](https://user-images.githubusercontent.com/114746710/195667364-0ccd34b2-a2cb-4c55-9317-1348d951e641.png)



deb not install filza

**Comment by Ixolaro** [comment]
Cuz ur not booted with palera1n

**Comment by Ixolaro** [comment]
ok im recloning just in case

**Comment by MissThee** [comment]
> stuck at No connected device found, terminating. New connection for 2222->22, fd = 5 waiting for connection No connected device found, terminating. New connection for 2222->22, fd = 5 waiting for connection No connected device found, terminating.

I'm stuck here too . How to fix...plzzzz...
