### ISSUE TITLE
  Package mobilesubstrate is not installed.

### ISSUE THREAD

**Issue by Aibric** [palera1n/palera1n#440]
### Description

palera1n : v2.0.0-beta.9.2
system ：mac arm64
ios version: 16.3.1

When I install xxtouch app it says "Package mobilesubstrate not installed".

dpkg -i "/var/mobile/Downloads/xxt.deb" ;
(Reading database ... 6615 files and directories currently installed.)
Preparing to unpack /var/mobile/Downloads/xxt.deb ...
Unpacking com.1func.xxtouch.ios (1.2-10) over (1.2-10) ...
dpkg: dependency problems prevent configuration of com.1func.xxtouch.ios:
 com.1func.xxtouch.ios depends on mobilesubstrate (>= 0.9.5000); however:
  Package mobilesubstrate is not installed.

dpkg: error processing package com.1func.xxtouch.ios (--install):
 dependency problems - leaving unconfigured
Processing triggers for uikittools (2.1.6-1) ...
Processing triggers for org.coolstar.sileo (2.5) ...
Errors were encountered while processing:
 com.1func.xxtouch.ios

**Comment by Aibric** [comment]
> ### Description
> palera1n : v2.0.0-beta.9.2 system ：mac arm64
> 
> When I install xxtouch app it says "Package mobilesubstrate not installed".
> 
> dpkg -i "/var/mobile/Downloads/xxt.deb" ; (Reading database ... 6615 files and directories currently installed.) Preparing to unpack /var/mobile/Downloads/xxt.deb ... Unpacking com.1func.xxtouch.ios (1.2-10) over (1.2-10) ... dpkg: dependency problems prevent configuration of com.1func.xxtouch.ios: com.1func.xxtouch.ios depends on mobilesubstrate (>= 0.9.5000); however: Package mobilesubstrate is not installed.
> 
> dpkg: error processing package com.1func.xxtouch.ios (--install): dependency problems - leaving unconfigured Processing triggers for uikittools (2.1.6-1) ... Processing triggers for org.coolstar.sileo (2.5) ... Errors were encountered while processing: com.1func.xxtouch.ios

ios version 16.3.1

**Comment by khcrysalis** [comment]
@Aibric 
Your error shows that you don't have any tweak injection package installed, so please install ellekit from its repo in Sileo. If you're using Zebra then the repository is https://ellekit.space/

**Comment by Aibric** [comment]
> @Aibric Your error shows that you don't have any tweak injection package installed, so please install ellekit from its repo in Sileo. If you're using Zebra then the repository is https://ellekit.space/
I installed ellekit, but it still failed. Although the icon appeared, it cannot be used normally.
![1](https://github.com/palera1n/palera1n/assets/2859844/a61a4d0a-cc7e-4224-a33b-ae146bbad407)
![2](https://github.com/palera1n/palera1n/assets/2859844/908e8c1f-13a6-48cc-9985-8bf512dccec1)
![3](https://github.com/palera1n/palera1n/assets/2859844/e78718db-0895-4655-95f6-7b2aa4851fca)

**Comment by pig837** [comment]
Install mobilesubstrate.

If you are in rootless, it may not work. But it may be works in rootful. (AT YOUR OWN RISK, becasuse i didn't test it.)
https://apt.bingner.com/debs/1443.00/mobilesubstrate_0.9.7113_iphoneos-arm.deb

Note that all of tweaks can't be supported on rootless.
