### ISSUE TITLE
DFU

### ISSUE THREAD

**Issue by ShntLam** [palera1n/palera1n#441]
### Device

IPAD AIR 2

### Version

15.8.2

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

My device is not going to dfu mode. if i press the home and the power button, the only thing happened is appearing the logo and its not going thru process of jailbreaking

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by pig837** [comment]
1. Sometimes, the jailbreak process won't work well, I rebooted 20 times and I succeeded jailbreak (iPhone 8+, 16.7.8)
2. If you experienced wrong situation during jailbreak, restore firmware using iTunes, and retry to enter, do jailbreak.

**Comment by khcrysalis** [comment]
The only cases I've found where the user failed to enter DFU is when they used a usb-c cable (https://github.com/palera1n/palera1n?tab=readme-ov-file#computer-requirements) as described here, otherwise it may either be related to the port or you're doing the combination wrong.

**Comment by Foxtrod89** [comment]
> 1. Sometimes, the jailbreak process won't work well, I rebooted 20 times, connect/disconnect cable and I succeeded jailbreak (iPhone 8+, 16.7.8)
> 2. If you experienced wrong situation during jailbreak, restore firmware using iTunes, and retry to enter DFU, do jailbreak.
> 
> Recently, i'm encountered your situation.

mine is always stuck during 1st booting process with **-cf** options enabled, iPhone 8 mini
![IMG_8189 (1)](https://github.com/user-attachments/assets/c624fb90-8e61-41aa-816d-a6af1cf3f773)

**Comment by pig837** [comment]
> > 1. Sometimes, the jailbreak process won't work well, I rebooted 20 times, connect/disconnect cable and I succeeded jailbreak (iPhone 8+, 16.7.8)
> > 2. If you experienced wrong situation during jailbreak, restore firmware using iTunes, and retry to enter DFU, do jailbreak.
> > 
> > Recently, i'm encountered your situation.
> 
> mine is always stuck during 1st booting process with **-cf** options enabled, iPhone 8 mini ![IMG_8189 (1)](https://private-user-images.githubusercontent.com/19302114/350798334-c624fb90-8e61-41aa-816d-a6af1cf3f773.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTAxNTMsIm5iZiI6MTcyMTY0OTg1MywicGF0aCI6Ii8xOTMwMjExNC8zNTA3OTgzMzQtYzYyNGZiOTAtOGU2MS00MWFhLTgxNmQtYTZhZjFjZjNmNzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDEyMDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOWJlNmI1Mjg4YzhkNTZhNjk5ZDFjODNmM2VkNjNhZTU1OGJjMzc1ZWRjY2Y5MzYzZTFhMTRiNWVkMGNkMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iVHhS3MTvrQIzTfHCIwWZsk565JCga-sJlxgz3gGth8)

https://www.reddit.com/r/jailbreak/s/RfSt2bdEfa
