### ISSUE TITLE
Unable to fetch bootstraps 

### ISSUE THREAD

**Issue by House-Coulybaly** [palera1n/palera1n#443]
### Description

The latest update, the loader says unable to fetch bootstraps on iOS 16.7.8 iPhone 8 plus

**Comment by khcrysalis** [comment]
<img width="595" alt="image" src="https://github.com/user-attachments/assets/844ca703-3828-458a-a63f-c653b64642e5">

Was fixed a few seconds ago :) just wait for cloudflare to cache and it should work properly.
