### ISSUE TITLE
Palera1n Launcher 2.1

### ISSUE THREAD

**Issue by heyitzmomo2k** [palera1n/palera1n#444]
### Description

so i use the "hide environment" feature a lot when I need to use my bank apps in emergency cases and then re-jailbreak as normal . The new update has removed this and me being dumb I thought it was now restore system. However it now just un-jailbreaks completely so now I have lost all my sources, packages etc. Does anyone know why this was removed or if there is another method.

**Comment by khcrysalis** [comment]
"Hide Environment" didn't serve much use as there are a bunch of ways to detect palera1n even with the option used, (hide environment just deletes the `/var/jb` symlink).

Decided to remove it as it didn't serve much use, however we can add it back if the demand is ever high.

**Comment by heyitzmomo2k** [comment]
No worries. would be cool to have it back as it worked with using uk based bank apps.
