### ISSUE TITLE
Any help method or tutorial for could jb the appletv 4k 1st gen pls ''as it is supported]]

### ISSUE THREAD

**Issue by JosephFM96** [palera1n/palera1n#445]
### Device

AppleTV 4K 1st Gen

### Version

tvOS 17.5.1

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

can somebody pls tell how to do it or which steps to follow ... please

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
You can find a guide here: https://docs.palera.in/docs/intro/

Also for future reference I would recommend looking at our site for guides.
