### ISSUE TITLE
Iphone 14 iOS 17.6

### ISSUE THREAD

**Issue by nanotube164** [palera1n/palera1n#447]
### Device

Iphone14

### Version

Ios17.6

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

I jailbreak with paler1n but pop out "warning ignoring non arm64 device". Now how can I do?

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by TheMasterOfMike** [comment]
palera1n does not support (and never will, barring a miracle) the iPhone 14 (or any other arm64e (A12+) device)
