### ISSUE TITLE
palera1n iphone 8 ios 16.7.7

### ISSUE THREAD

**Issue by mekkoli** [palera1n/palera1n#450]
### Description

Ubuntu 22.04.4 LTS
palera1n: v2.0
iphone 8 ios 16.7.7

palera1n -l // jailbreak ok but script don't exit, stopped with ctrlC

install zebra sileo rep  // ok
from zebra or sileo install apps but canno't see the link to run the installed app.

palera1n -f // no jailbreak

**Comment by khcrysalis** [comment]
> palera1n -l // jailbreak ok but script don't exit, stopped with ctrlC

Common issue, though its not really something of priority as it still works

> from zebra or sileo install apps but canno't see the link to run the installed app.

This is super unclear, and I'm not sure what you mean.

> palera1n -f // no jailbreak

palera1n needs a fakefs before jailbreaking on iOS versions.

**Comment by khcrysalis** [comment]
I would recommend you read the [palera1n documentation](https://cdn.nickchan.lol/palera1n/c-rewrite/releases/v2.0/docs/palera1n.1.html#DESCRIPTION) to see how palera1n works.

**Comment by mekkoli** [comment]
great thanks khcrysalis
super unclear ? sorry, english is not my language, in this way is it clear ?
after install new app from zebra/sileo i cannot find the icon to tap for to run the installed app.
