### ISSUE TITLE
pls help ;(

### ISSUE THREAD

**Issue by caotrivi** [palera1n/palera1n#452]
### Device

ip x

### Version

16.7.8

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

<Error>: Device is not in normal mode: -21 (Invalid HostID)
I have reset my device to white and doesn't enabled passcode, but I can't jailbreak my phone with this issue

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by hg13bs** [comment]
enter recovery mode manually or use `idevicepair pair` command (add sudo on Linux, and after u click trust on your device, you might need to rerun the command again and it should work)

**Comment by khcrysalis** [comment]
@caotrivi ?
