### ISSUE TITLE
No Paleran app after installation / jailbreak 

### ISSUE THREAD

**Issue by raphaelthiel** [palera1n/palera1n#453]
### Device

iPhone X

### Version

iOS 16.7.9

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

There is no application installed. I have tried already to use command -f -c as well as shortcuts to find and open the app. But it is not installed.

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
From the documentation it says using `palera1n -f -c` is for setting up the fake filesystem, not jailbreaking and booting it.

To boot rootful jailbroken, you must use `palera1n -f` after setting up beforehand.

**Comment by khcrysalis** [comment]
Also one more thing, for when using an A11 device on iOS 16, you **must** reset your phone before using this tool. You cannot have a passcode at *all*.

**Comment by raphaelthiel** [comment]
Thank you, the full reset worked.

**Comment by dmatora** [comment]
my device has passcode disabled but still no palera1n app after booting with `palera1n-macos-x86_64 -l`
tried booting `palera1n-macos-x86_64 -l -T` but telnet returns Connection refused

**Comment by khcrysalis** [comment]
> my device has passcode disabled but still no palera1n app after booting with `palera1n-macos-x86_64 -l`
> tried booting `palera1n-macos-x86_64 -l -T` but telnet returns Connection refused

This is probably the same issue you're facing, on iOS 16 (iPhone X, iPhone 8(Plus)) you must reset your phone before using palera1n.

**Comment by dmatora** [comment]
I did reset device prior to using palera1n,
I read somewhere, that if you enable passcode once, even if you disable it afterwards, palera1n would not work anymore - is that true?

**Comment by dmatora** [comment]
ok I've reset device again and skipped iCloud setup, and now it worked
I was also able to solve Unable to open device: e00002c5 (error code: -status_open_device_error)
with replugging lighting cable
