### ISSUE TITLE
A palera1n general question of iPad device compatibility

### ISSUE THREAD

**Issue by zhengling** [palera1n/palera1n#456]
### Description

Since palera1n version 2.0, the supporting for iPadOS18+ was come into being. If it will be work well in all type of ipad? Or It must be installed in palera1n recommend device (Jailbreak for A8 through A11)?

**Comment by khcrysalis** [comment]
> If it will be work well in all type of ipad? 
Up to you to try.
> Or It must be installed in palera1n recommend device (Jailbreak for A8 through A11)?
It's up to you to install it, palera1n is a jailbreak, if you want jailbroken features, then sure you can use it.
