### ISSUE TITLE
Palera1n A1566

### ISSUE THREAD

**Issue by eliekh05** [palera1n/palera1n#457]
### Device

iPad Air 2

### Version

iOS 15.8.3

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

My device is not getting into palera1n with palera1n 2.0.1 on iPad Air 2 because it will show blackscreen when finished with booting kernel after that it will boot without palera1n like it does reboot device but latest beta it will work that has Get Started and old boot sequence 

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
Be more specific, show logs if anything. "It doesn't work" is not informative.

**Comment by eliekh05** [comment]
when the palera1n says booting it bring up black screen and bootup with palera1n latest version 2.0.1 but latest beta will boot with palera1n and next time make sure you add specific questions like logs with the steps and etc

**Comment by jim16127** [comment]
> when the palera1n says booting it bring up black screen and bootup with palera1n latest version 2.0.1 but latest beta will boot with palera1n and next time make sure you add specific questions like logs with the steps and etc

Are you attempting a rootful or rootless setup?

**Comment by eliekh05** [comment]
> > when the palera1n says booting it bring up black screen and bootup with palera1n latest version 2.0.1 but latest beta will boot with palera1n and next time make sure you add specific questions like logs with the steps and etc
> 
> Are you attempting a rootful or rootless setup?
> 
> Also, would you add this argument to your palera1n run -V If you were booting rootful it would be `palera1n -f -V` Assuming you've already created a fakefs.

i am using rootful with fakefs/partial fakefs

**Comment by jim16127** [comment]
> > > when the palera1n says booting it bring up black screen and bootup with palera1n latest version 2.0.1 but latest beta will boot with palera1n and next time make sure you add specific questions like logs with the steps and etc
> 
> > 
> 
> > Are you attempting a rootful or rootless setup?
> 
> > 
> 
> > Also, would you add this argument to your palera1n run -V If you were booting rootful it would be `palera1n -f -V` Assuming you've already created a fakefs.
> 
> 
> 
> i am using rootful with fakefs/partial fakefs

Would you run `palera1n -f -V` and report where your boot process hangs. Have your computer or something to write with handy. The lines are small with a handful of text.
