### ISSUE TITLE
Stuck on booting pongos TVos 16.6

### ISSUE THREAD

**Issue by yo97490** [palera1n/palera1n#458]
### Device

Apple TV A1625

### Version

tvOS 16.6

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

Jailbreak process start but stuck on booting pongos

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by yo97490** [comment]
Solution found and working : in terminal type control x, then enter, then type exit, then enter 
And repeat the process at the beginning

**Comment by khcrysalis** [comment]
Glad you were able to figure out your issue!
