### ISSUE TITLE
Tweaks dont show up

### ISSUE THREAD

**Issue by olejenek1000** [palera1n/palera1n#459]
### Device

iPhone X

### Version

16.7.10

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

Tweaks not showing in settings ios. Installed Crane and there is not icon in settings. I already have ellekit and prefernce loader.
Notice: I also installed gps manager and inside gps manager i can see crane.

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
Restart your device and try again, possibly reinstall.

Also, since this issue isn't really significant in getting the palera1n tool itself working properly I will close this.
