### ISSUE TITLE
T2 support?

### ISSUE THREAD

**Issue by ak99004242** [palera1n/palera1n#46]
Any chance to add T2 support?

**Comment by itsnebulalol** [comment]
This is meant for iOS. Just curious, what would be the point of this for T2?

**Comment by ak99004242** [comment]
Access the root system or we can ssh the device, can you please add support for it as non of the ramdisk methods work on it. I have tried different ramdisks on T2, one thing more if the ramdisk is larger than 110mb on T2 it doesn’t load at all.
