### ISSUE TITLE
Rootful Bind FS doesn't work

### ISSUE THREAD

**Issue by OckoBlox** [palera1n/palera1n#460]
### Device

iPhone 7

### Version

iOS 15.8.3

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

Rootful Bind FS gets created, device reboots into recovery, I run palera1n -f to boot and the device restarts after pongo os, then it boots into normal iOS and I try running palera1n -f again, it gets into pongo os, and it restarts into normal iOS again. Because of this I can't jailbreak rootful

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
>  it restarts into normal iOS again.

This isn't very specific, do you know if its actually booting to normal iOS? How do you even know if its jailbroken?

**Comment by OckoBlox** [comment]
i see no palera1n loader

**Comment by OckoBlox** [comment]
i already restored the device using itunes, and now im trying fakefs

**Comment by OckoBlox** [comment]
it seems, fakefs worked fine for some reason, its now jailbroken
