### ISSUE TITLE
Palera1n <Error>: Unable to perform softboot: e0004051

### ISSUE THREAD

**Issue by garpios12** [palera1n/palera1n#461]
### Device

iPad Pro 12.9

### Version

Ios 16.7.1Hellotrie d

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

Hello, I tried to jailbreaking iPad 12.9 iOS 16.7.1 using the following commands palera1n -c -f and palera1n -f,  but get the following  <Error>: Unable to perform softboot: e0004051. 
appreciate any support.

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by garpios12** [comment]
I tried again and it worked

**Comment by andmpel** [comment]
I just had this issue and rerunning it like 5 times worked. This was on palera1n 2.2
