### ISSUE TITLE
Stuck on "<Warning> Ignoring non-arm64 device..."

### ISSUE THREAD

**Issue by monkelmaoo** [palera1n/palera1n#463]
### Device

Iphone 13

### Version

iOS 1.17.6

### Passcode?

- [X] Passcode is enabled.

### Start going into detail..

its stuck on there and help commands not working...
![image](https://github.com/user-attachments/assets/48e9b4b1-f07e-43bc-92a7-dbe9219fe8f0)

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
<img width="681" alt="image" src="https://github.com/user-attachments/assets/0d9164bb-e134-4578-92d3-5b85744b6585">

Everywhere it says that anything higher than an iPhone X is not supported.
