### ISSUE TITLE
Can'r use some apps

### ISSUE THREAD

**Issue by BakaGzRay12456** [palera1n/palera1n#464]
### Device

iPhone X

### Version

iOS 16.7.8

### Passcode?

- [X] Passcode is enabled.

### Start going into detail..

I can't use some apps after jailbreak like taobao,
is works few seconds then crushed 

I tried rootful&rootless,but it still didn't work 
I can provide logs if you need
Thanks

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
This is a common issue when it comes to using jailbreaks in general, some apps will not let you use them because of it. 

And no, we won't fix that.

**Comment by BakaGzRay12456** [comment]
But when I use dopamine(16.5),these apps can use.

**Comment by khcrysalis** [comment]
Theres a difference between jailbreaks, palera1n is *marginally* different than Dopamine.

Some apps may work on other jailbreaks, some may not on others.
