### ISSUE TITLE
I can't ssh through lan network

### ISSUE THREAD

**Issue by oseack** [palera1n/palera1n#465]
### Device

iphone 8

### Version

iOS 16.7.10

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

* I lost jailbreak after I enabled passcode on this phone.
* I went through your site, try to reset the phone, failed to do this from the phone.
* I installed Apple Devices on Windows 11 pc and restored from there, it seems it's a clean reset, I have to go through a phone setup like a new phone.
* after that, I tried to use palera1n v2.0.1 to jailbreak. I used "palera1n -l" to jailbreak the phone. Rootful doesn't work at all.
* it works I can install sileo and install newterm 3 beta and openssh.
* I also changed root password to alpine.
* but ssh to this phone failed. It's always timeout.
* I logged in as root in newterm 3. When I do "ps ax | grep ssh", there is no such process running.
* I tried "ssh localhost", logged in with alpine, then do "ps ax | grep ssh", this time I can see the sshd process is running. When I do "launchctl list | grep ssh", see screenshot, I can see there is sshd process running.
* I am not sure how can I configure the ssh server to let ssh connection through lan. 
* Let me know if you need further informantion.
![2024-08-19 17_22_10-iCloud Photos — Mozilla Firefox](https://github.com/user-attachments/assets/2de6ee9d-59c8-4abd-a314-0851003cc03d)
 

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by oseack** [comment]
I used rootless to jailbreak the phone. rootful doesn't work at all.

**Comment by khcrysalis** [comment]
Which port are you using?

**Comment by oseack** [comment]
I didn't change the port. The problem is sshd is not started.
