### ISSUE TITLE
After full root jailbreak, the water drop palera1n icon does not appear

### ISSUE THREAD

**Issue by dinhthiet2702** [palera1n/palera1n#467]
### Description

Hello, I am using iPhone 6s - A9 chip - ios 15.8.2
Steps:
Step 1: Palera1n -B -f
Step 2: palera1n -f
After the device boots successfully, there is no Palera1n water drop icon
I use palera1n on macos sonoma 14.1.1 M1 pro chip
I tried jailbreaking using v2.0.0 beta 9 and the icon appeared
How to solve it, I want to use the latest version, can someone help me?

**Comment by CivilBreak63501** [comment]
have you tried using the open app command in shortcuts?

**Comment by dinhthiet2702** [comment]
> have you tried using the open app command in shortcuts?

There's actually no icon showing up, I searched for it in the search bar, but it's not there, can you give me that shortcut?

**Comment by dinhthiet2702** [comment]
sloved
