### ISSUE TITLE
JBINIT DIED! error on my Phone. And the CAQ does not state what to rm rf blobs

### ISSUE THREAD

**Issue by Apple4787Microbitter** [palera1n/palera1n#468]
### Description

I have iPhone 7 running iOS 15.8.3 also Im trying to rootfully jailbreak

**Comment by afastaudir8** [comment]
> What is "CAQ"? I'm not entirely sure what that is.

Pretty sure they mean FAQ.

What is the command you're running to jailbreak? Did you already create a fakefs for rootful?
