### ISSUE TITLE
Hello, iPhone10,1 on 15.7!

### ISSUE THREAD

**Issue by jeremyhill424** [palera1n/palera1n#47]
Hello, iPhone10,1 on 15.7!
[*] Switching device into recovery mode...
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Pwning device
[*] Booting device

Done!
The device should now boot to iOS
If you already have ran palera1n, click Do All in the tools section of Pogo
If not, Pogo should be installed to Tips

blank screen. I tried./palera1n.sh clean a few times after rebooting, multiple times, and every time it still does the same thing. any pointers on what I'm doing wrong?

**Comment by itsnebulalol** [comment]
show the output of `./palera1n.sh --debug` after doing `./palera1n.sh clean`

**Comment by jeremyhill424** [comment]
➜  palera1n git:(main) ./palera1n.sh --debug
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

ERROR: No device found!
ERROR: No device found!
ERROR: No device found!
Hello,  on !
[*] Switching device into recovery mode...
ERROR: No device found!
ERROR: No UDID specified
Usage: ideviceenterrecovery [OPTIONS] UDID

Makes a device with the supplied UDID enter recovery mode immediately.

OPTIONS:
  -d, --debug           enable communication debugging
  -h, --help            prints usage information
  -v, --version         prints version information

Homepage:    <https://libimobiledevice.org>
Bug Reports: <https://github.com/libimobiledevice/libimobiledevice/issues>

do I need to reboot and then try? also, I tried updating libmobiledevice, also cleaning it.... using homebrew on a Mac mini m1.

**Comment by jeremyhill424** [comment]
sorry for that last reply..... 
Hello, iPhone10,1 on 15.7!
[*] Switching device into recovery mode...
Telling device with udid b47f8239261025d8f2ffd520b8849ae92d936d5b to enter recovery mode.
Device is successfully switching to recovery mode.
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Pwning device
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:0009713018BB002E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:0009713018BB002E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SPRAY
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:0009713018BB002E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:0009713018BB002E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:0009713018BB002E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[*] Converting blob
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
Saved IM4M to work/IM4M
[*] Downloading BuildManifest
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: 
Error init failed
➜  palera1n git:(main)

**Comment by jeremyhill424** [comment]
Hello, iPhone10,2 on 15.7!
[*] Switching device into recovery mode...
Telling device with udid 06bd306c41ade679f135bad1635998c386bd9515 to enter recovery mode.
Device is successfully switching to recovery mode.
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Creating ramdisk
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:04 ECID:001674DC08D3002E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:04 ECID:001674DC08D3002E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SPRAY
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:04 ECID:001674DC08D3002E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:04 ECID:001674DC08D3002E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:04 ECID:001674DC08D3002E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
Saved IM4M to work/IM4M
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: null
Error init failed
[-] An error occurred


any ideas regarding this? Mac-Mini M1 . iPhone 8-plus, iOS 15.7.

**Comment by jeremyhill424** [comment]
99% [========================================================================== 99% [========================================================================== 99% [==========================================================================100% [===================================================================================================>]
download succeeded
[*] Patching and signing iBSS/iBEC
main: Starting...
iOS 15 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x180031bb0 : 000080d2
applying patch=0x180031c00 : 000080d2
applying patch=0x1800337c4 : 200080d2
main: Writing out patched file to iBSS.patched...
main: Quitting...
main: Starting...
iOS 15 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x180031bb0 : 000080d2
applying patch=0x180031c00 : 000080d2
applying patch=0x1800337c4 : 200080d2
main: Writing out patched file to iBEC.patched...
main: Quitting...
none
none
[*] Patching and signing kernelcache
[e] cannot read ''
[e] cannot apply patch
krnl

**Comment by jeremyhill424** [comment]
any ideas? looks to be at the end.... almost there.. do I need to add something for Mac mini m1?

**Comment by jeremyhill424** [comment]
for the ipswurl issue. If I'm on an iPhone 8 Plus using 15.7, what would be the correct label for the ipsw in ./palera1n.sh? example: ipswurl="https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-63876/B64A4CAA-7DD6-4C49-998B-FBCB6AF059F7/iPad_64bit_TouchID_ASTC_15.1_19B74_Restore.ipsw". but for iOS 15.7 iPhone 8 Plus or an iPhone 8, both are on 15.7

**Comment by jeremyhill424** [comment]
[*] Patching and signing trustcache
trst
none
[*] Booting device
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%

Done!
The device should now boot to iOS
If this is your first time jailbreaking, open Tips app and then press Install
Otherwise, open Tips app and press Do All in the Tools section
If you have any issues, please join the Discord server and ask for help: https://dsc.gg/palera1n
Enjoy!

trustcache by chance? ipswurl connection by chance? forgive my ignorance.

**Comment by jeremyhill424** [comment]
https://github.com/pwnd2e/palera1n/files/9842901/SUCCESS_18.28.37-2022-10-21-Darwin-21.5.0.log

does this help by chance?

**Comment by jeremyhill424** [comment]
I finally got it to work!!!! rootless for iOS 15.7 iPhone 8 Plus. 
[*] Device entered DFU!
[*] Pwning device
[*] Converting blob
[*] Downloading BuildManifest
[*] Downloading and decrypting iBSS
[*] Downloading and decrypting iBEC
[*] Downloading DeviceTree
[*] Downloading AOP
[*] Downloading trustcache
[*] Downloading kernelcache
[*] Patching and signing iBSS/iBEC
[*] Patching and signing kernelcache
[*] Signing DeviceTree
[*] Signing AOP
[*] Patching and signing trustcache
[*] Booting device
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%

Done!
The device should now boot to iOS
If you already have ran palera1n, click Do All in the tools section of Pogo
If not, Pogo should be installed to Tips

**Comment by jeremyhill424** [comment]
Sileo opens!

**Comment by tanghengvip** [comment]
ipad pro 10.5 （iOS 15.7）+MacBookPro
I got this problem too：
1.enter DFU
2.run Palera1n.sh.
3.boot smile logo
4.code runs on screen
5.failed to enter the recovery mode.  Palera1n.sh stopped here.
6.then device boot normally. and system-app "Tips" can't launch.

I tried many times and remains fail. it always can't enter recoverymode automatic.
Have I do anyhing wrong?
