### ISSUE TITLE
/var/run/usbmuxd not found on Raspberry Pi

### ISSUE THREAD

**Issue by v3rtual** [palera1n/palera1n#473]
### Device

iPhone 6s+

### Version

iOS 15.8.2

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

I'm attempting to run palera1n on a Raspberry Pi 3 B+ running Raspberry Pi OS Lite 64-bit, however, no matter what i do, every time I run the script in the terminal, it tells me that /var/run/usbmuxd was not found. I'm not sure how to fix this.

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by v3rtual** [comment]
> Could you please tell what command you’re running? Also, is your device in DFU mode when you run the command?

I'm running palera1n -l. The device is not in DFU mode.

**Comment by afastaudir8** [comment]
> > Could you please tell what command you’re running? Also, is your device in DFU mode when you run the command?
> 
> I'm running palera1n -l. The device is not in DFU mode.

-l isn't needed as rootless is selected by default. 

I'm pretty sure a precompiled version of usbmuxd exists for arm, but you can just put your device into DFU mode and palera1n will jailbreak it. usbmuxd is only used for normal mode detection.

**Comment by TheMasterOfMike** [comment]
> > > Could you please tell what command you’re running? Also, is your device in DFU mode when you run the command?
> > 
> > 
> > I'm running palera1n -l. The device is not in DFU mode.
> 
> -l isn't needed as rootless is selected by default.
> 
> I'm pretty sure a precompiled version of usbmuxd exists for arm, but you can just put your device into DFU mode and palera1n will jailbreak it. usbmuxd is only used for normal mode detection.

-l is required for rootless starting with palera1n 2.0

That being said, the other things you listed should work (though tbf I'm wondering what happens if you try palera1n without running the usbmuxd stuff on the Raspberry Pi).

**Comment by khcrysalis** [comment]
yeah usbmuxd is only used for normal mode, in theory just going into recovery mode or dfu should work right off the bat

**Comment by khcrysalis** [comment]
This issue is outdated and is easily fixable by including usbmuxd on your system, along with many other solutions that palera1n can solve by going to recovery manually. So I will be closing this.
