### ISSUE TITLE
Error in  iOS16.7.10

### ISSUE THREAD

**Issue by cnjsyyb** [palera1n/palera1n#474]
### Description

iphone8 ios16.7.10
palera1n -c -f
<img width="1013" alt="截屏2024-08-31 12 41 37" src="https://github.com/user-attachments/assets/b3bb7ba4-9784-4922-851c-f615319dc24d">

**Comment by afastaudir8** [comment]
So first of all, are you using an official Lightning to USB type A cable?
Second, are you using palen1x, Linux, or macOS?
Third, please use the "Create Issue" template next time.
