### ISSUE TITLE
Ignoring non-arm64 device... error

### ISSUE THREAD

**Issue by Ehsannx** [palera1n/palera1n#475]
### Device

iPhone 13 Pro

### Version

iOS 17.6

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

its not working on my device its giving me this error Ignoring non-arm64 device... can someone help me out pls.

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by ElliesSurviving** [comment]
anything above the iPhone X (A11 processor/arm64) is unsupported. you cannot jailbreak your iOS version

**Comment by Ehsannx** [comment]
so can u jailbreak iOS 17.6 or 18.0/18.1 on iPhone 13 pro or u can't jailbreak?

**Comment by ElliesSurviving** [comment]
you cant jailbreak any

**Comment by Ehsannx** [comment]
> you cant jailbreak any

so what have to do to jailbreak it any ways
