### ISSUE TITLE
issue with iphone 8 plus

### ISSUE THREAD

**Issue by TranMoiz259** [palera1n/palera1n#476]
### Device

iPhone 8 Plus

### Version

IOS 16.10

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

When booting kernel, my device reboot into normal state, i've tried using both rootful and rootless mode.

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!
- edit:iPhone is unactivated and has a icloud in it.

**Comment by khcrysalis** [comment]
You will not be able to boot due to either bad tweak, have had passcode enabled before, or you've had a corrupted iOS install.

If you've set a passcode before and not reset, you need to reset your device.

**Comment by TranMoiz259** [comment]
> You will not be able to boot due to either bad tweak, have had passcode enabled before, or you've had a corrupted iOS install.
> 
> If you've set a passcode before and not reset, you need to reset your device.
I haven't jailbreak it before so there's no tweak,my device have passcode once but i've already reset it.I downloaded the ios install on https://ipsw.me.

**Comment by Le-Khuong** [comment]
Is there any panic log? It’d help alot

**Comment by TranMoiz259** [comment]
> Is there any panic log? It’d help alot

where is it? i'm not familiar qith palera1n ;-;
