### ISSUE TITLE
Tweaks not showing on settings

### ISSUE THREAD

**Issue by Victorbmag** [palera1n/palera1n#479]
### Description

I currently have palera1n rootless on iphone 8 and I had my assistant to delete a few tweaks, but I guess he deleted couple more things and now I can't see any tweak like shadow, choicy etc on settings.
Already respringed, and did j.b again, nothing happens. anyone knows about it?

**Comment by khcrysalis** [comment]
You need preferenceloader and something that gives tweak injection, i.e. ElleKit. If both are installed already reinstall them. Closing this issue as it doesn't have any significance to the tool itself
