### ISSUE TITLE
The program exits with no output if iproxy is not already running on Linux

### ISSUE THREAD

**Issue by buzzcoding** [palera1n/palera1n#48]
In the _usb_fix function for Linux, palera1n tries to kill iproxy if it was already running. If it is not running, this returns a non-zero code, making the program exit due to the `set -e` at the beginning of the script. The temporary solution I used on my machine was to put `set +e` before on the line before, so on the new line 120, and `set -e` on the line before the line which starts usbmuxd, so on the new line 126.

**Comment by itsnebulalol** [comment]
Can you test if this was fixed in f85c88e

**Comment by buzzcoding** [comment]
Sure. One sec

**Comment by buzzcoding** [comment]
Yep. It works now. Thanks 👍

**Comment by itsnebulalol** [comment]
Thank you for testing

**Comment by buzzcoding** [comment]
You’re welcome
