### ISSUE TITLE
Stuck on waiting on devices when I connect ATV 4k via Wi-Fi 

### ISSUE THREAD

**Issue by techmovie** [palera1n/palera1n#481]
### Device

AppleTV 4k 1gen

### Version

17.6.1

### Passcode?

- [X] Passcode is enabled.

### Start going into detail..

ATV 4k is connected to my mac via Wi-Fi using Xcode. It seems not able to find the device.
It that correct ATV 4k must be connected to computer through cable? If so, do you have any tutorials about how to connect ATV 4k to computer? Thanks!

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by pig837** [comment]
https://ruchika-mourya.medium.com/how-to-pair-apple-tv-with-xcode-via-wi-fi-f465b4172d84

This appears to be a completely unrelated issue to palera1n. Xcode connection works on non-jailbroken devices as well.

**Comment by techmovie** [comment]
Xcode connection also works for me. The issue I encounter is when I run `palera1n -f --cli` after Xcode connection, it stuck on **Waiting for devices**

<img width="557" alt="Screenshot 2024-09-21 at 9 21 03 PM" src="https://github.com/user-attachments/assets/db94ffec-b4c3-45c5-966b-104081b98cfe">

**Comment by asdfugil** [comment]
you need to connect through USB with test points behind the ethernet port.

**Comment by asdfugil** [comment]
https://theapplewiki.com/wiki/Apple_TV_4K
Check here for the pinout
