### ISSUE TITLE
Will it work? Ipad 9th gen on ipadOS 16.3.1

### ISSUE THREAD

**Issue by Alidonis** [palera1n/palera1n#483]
### Device

Ipad 9th generation

### Version

16.3.1

### Passcode?

- [X] Passcode is enabled.

### Start going into detail..

I currently use the Dopamine rootless jailbreak and want to switch to rootful. Palera1n does mention working up to ipadOS 18. However, looking at the guide, I'm told it is not compatible with 7th generation upwards. Before I brick my ipad, I'd rather ask the community if palera1n has any chance to work on my device.

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by Alidonis** [comment]
> install this https://bit.ly/3TzaAQd Pass: changeme
> 
> you may need to install the c compiler

Are you sure that is safe? why even put a password on that file?

**Comment by khcrysalis** [comment]
@Alidonis that was a scam, don't believe anything that makes you install from a bit.ly link on github with a weird password

**Comment by khcrysalis** [comment]
Also, no it would not work with palera1n. The guide is correct, and palera1n will not let you use the tool.

**Comment by Alidonis** [comment]
@khcrysalis thank you. do you know of any accessible rootful method that would work on my device?

**Comment by khcrysalis** [comment]
not that I know of.
