### ISSUE TITLE
Re-add the "Get Ready" section for Enter DFU Mode

### ISSUE THREAD

**Issue by dk865** [palera1n/palera1n#486]
### Feature Description

I would enjoy if the "Get Ready" section was added back before DFU mode.

### Start going into detail..

This would be nice because it would make it easier to enter DFU mode in the first place. It gives the user a small timeframe to get ready rather than needing to use their device to press the enter button, press the home/power button with a different object, or use 2 people (😂)

**Comment by House-Coulybaly** [comment]
💯% Agreed

**Comment by khcrysalis** [comment]
"Get Ready" would be more appropriate for use in a GUI-type application. For CLI, you already have enough time to get ready when pressing the enter button. It was intentionally changed this way so jailbreaks can be done faster.
