### ISSUE TITLE
Jailbreak Hide for palera1n

### ISSUE THREAD

**Issue by SKYLINEGT81** [palera1n/palera1n#487]
### Description

Hi, I am looking for way to use official bank application ([BANK MUSCAT](https://apps.apple.com/bh/app/bank-muscat-mobile-banking/id763499293)) . I have to restart my iPhone X IOS16.1.1 every time I need to use the application. The problem I need to go home to reJB my iPhone every time. Are there anyway to temporary disable the Paler1n JB to use the application then enable it without the need to computer.

**Comment by khcrysalis** [comment]
Its hard to determine what it could actually be detecting, most you can do is try to enter safemode or not have tweak injection enabled. Or even try to use a bypass tweak to try and get around it.

Otherwise, we can't really help you.
