### ISSUE TITLE
/mnt6 mount is wrong or varies between devices?

### ISSUE THREAD

**Issue by buzzcoding** [palera1n/palera1n#49]
Either the partition with the 'active' file which contains the name of the directory which contains usr/standalone/firmware/sep-firmware.img4 varies between devices or it is entered wrong in the script. On my device (6th gen iPad, A10, iOS 15.1), I have found through SSH that this partititon is at /dev/disk0s1s5, but palera1n mounts /dev/disk0s1s6. Just to note, I have never messed with partitions on this device, and palera1n is the only jailbreak/"jailbreak" I have ever installed on this device.

**Comment by itsnebulalol** [comment]
Seems like iPads have different partitions. I think Nathan (the creator of the upstream ramdisk repo) took care of this in his `mount_filesystems` script. I’ll see if I can add it to the ramdisk.tar.gz and use that instead

**Comment by itsnebulalol** [comment]
Can you test the latest commit (7f67026)

**Comment by buzzcoding** [comment]
I’m not going to be able to test it until Friday. If anyone is reading this who has a 6th gen iPad, if you can test it before then, please do and see if it works. If no one has tested it by then, I’ll try it.

**Comment by GeoffSI** [comment]
> Can you test the latest commit ([7f67026](https://github.com/palera1n/palera1n/commit/7f670269507f801c6c91fc70edb751e4d6ac6969))

How long ago was this commit? I am currently building the boot but yes its been going for a while. Should 
I stop and do a pull and then try?=

**Comment by buzzcoding** [comment]
The commit was 13 minutes ago from right now

**Comment by GeoffSI** [comment]
Ok I'll clone the entire thing. Question. Is sudo necessary?

**Comment by buzzcoding** [comment]
Nope. I can confirm from testing it before that it works without sudo and adding sudo does not change anything.

**Comment by GeoffSI** [comment]
The script is going fasTer and actually looks like its loading

**Comment by GeoffSI** [comment]
Now it is stuck here. 
![image](https://user-images.githubusercontent.com/104477485/192915594-03c863b2-67f1-4c5f-9e9c-002153d9a9b6.jpeg)

Terminal shows completed.
![image](https://user-images.githubusercontent.com/104477485/192915662-f1ff842a-04c0-4fc1-841f-27741bb4c756.jpeg)

**Comment by buzzcoding** [comment]
So I guess at least the part this issue is for is fixed. What is in the screenshot looks like one of the things that would just be fixed by trying it again. In my experience, checkm8 (at least on 6th gen iPads) likes to be sketchy and randomly decide to not work correctly.

**Comment by GeoffSI** [comment]
It just keeps freezing. But its not freezing at the same spot?

**Comment by buzzcoding** [comment]
Where is it freezing? If it gets stuck at the beginning when putting it into pwned DFU mode, that happens to me too, and it should finish after a few minutes then start the rest.

**Comment by buzzcoding** [comment]
Mine also kernel panicked when I tested it before by changing the /mnt6 mount partition to disk0s1s5. I’m going to close this issue because it has been fixed, and there is already an issue open for that: #41. Upgrading to 15.7 is unlikely to make a difference, especially because someone in that issue already tried that.
