### ISSUE TITLE
libusb error on 2.0.2

### ISSUE THREAD

**Issue by Ab3loth** [palera1n/palera1n#491]
### Device

A10X iPad Pro

### Version

17.7

### Passcode?

- [X] Passcode is enabled.

### Start going into detail..

<Error>: libusb_open: LIBUSB_ERROR_IO

gets stuck after booting pongo

Tested, happens on 2.0.2. Does not happen on 2.0.0 (works fine)

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by migdal-or** [comment]
The same issue is happening with my
```
Mode: normal
ProductType: iPad7,4
Architecture: arm64
Version: 16.5.1
DisplayName: iPad Pro 10.5-inch (Cellular)
```
with passcode disabled, on Debian Linux 13, and gets resolved by downgrading to 2.0.0.
