### ISSUE TITLE
Error 16.7.10

### ISSUE THREAD

**Issue by pvs178** [palera1n/palera1n#492]
### Description

<img width="384" alt="image" src="https://github.com/user-attachments/assets/5ac110f8-12a5-418c-a919-5c98ff55969e">

Hi all.
I have a crash after Booting Kernel...
There are no errors.
The screen shows a message from palera1n, then the screen blinks and reboots, I don't see any changes.
MacOs/m1pro; mac mini intel core i5, iphone 8
I have USB A cable, but not original
Can you help me?

**Comment by khcrysalis** [comment]
From what I see its most likely related to you having a passcode, https://docs.palera.in/docs/troubleshoot/troubleshooting-steps/#device-boots-un-jailbroken

I would recommend you create a new issue and use the proper template.
