### ISSUE TITLE
Cant install Sileo on palera1n (Fatal Error)

### ISSUE THREAD

**Issue by kayaalpbilal** [palera1n/palera1n#493]
### Device

iPhone 8

### Version

iOS 14.4

After successfully installing palera1n on my computer, I jailbroke my iPhone 8 with palera1n -l. 
After finishing the Jailbreak in the palera1n app, I tried to install Sileo so that i can install frida.
Unfortunately, the installation of Sileo does not work. After attempting to install Sileo, I receive the error message: '[fatal] No matching bootstrap found. File: Download#Install.swift:38 Func: downloadFiles(file:basePath:)'. I even tried it in rootful mode but have a different kind of error message.

**Comment by khcrysalis** [comment]
Youre on iOS 14, iOS 14 is not supported.
