### ISSUE TITLE
Hide Jailbreak Option

### ISSUE THREAD

**Issue by dk865** [palera1n/palera1n#498]
### Feature Description

I want palera1n to add a “Hide Jailbreak” option, because it would be helpful for using no-jailbreak apps, and for hiding the jailbreak entirely.

### Start going into detail..

I think it should also include a button the the loader, because it is easier than just on the computer.

**Comment by khcrysalis** [comment]
We refused to add it since even removing a symlink to the "fakeroot" wont help that much when it comes to jailbreak detection

**Comment by khcrysalis** [comment]
You could also do it yourself, so thats an option

**Comment by dk865** [comment]
Okay, that's good to know. Thank you.
