### ISSUE TITLE
Lucas 

### ISSUE THREAD

**Issue by Lucas01-00** [palera1n/palera1n#499]
### Device

iPhone 7 Plus 

### Version

iOS 15.8.3

### Passcode?

- [X] Passcode is enabled.

### Start going into detail..

K

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by Leonsanchez988** [comment]
hi, can you help me? speak spanish?

**Comment by khcrysalis** [comment]
If you have a question, ask it, this issue is gonna be closed as you didnt explain any of your issues.
