### ISSUE TITLE
A10X, iPadOS15.7, Linux, stuck at Pwning device

### ISSUE THREAD

**Issue by runhuizhou** [palera1n/palera1n#50]
Device is iPad Pro 10.5" 2017, on iPadOS 15.7

What i did is:
0. Got dumped blob from previous execution of sudo ./palera1n.sh --dfu 15.7 --debug
1. sudo ./sshrd.sh 15.7 TrollStore Tips (Stuck at "Getting Device Info... This may take a second" always, and succeeded to continue execution after lots of trials. Just like this issue.)
2. sudo ./sshrd.sh boot (seems ok, as Tips app is not opening now)
3. sudo ./palera1n.sh clean
4. sudo ./palera1n.sh --dfu 15.7 --debug (stuck somewhere)

This is kind of a random issue, randomly successfully continues, but mostly it's just stuck at somewhere.

For example, this time it's stuck at "[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227":

> [root@relafnic palera1n]# sudo ./palera1n.sh --dfu 15.7 --debug
> palera1n | Version 1.0.0
> Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy
> 
> [*] Getting device info...
> [*] Pwning device
> usb_timeout: 5
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000D0D402006603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
> Found the USB handle.
> Stage: RESET
> ret: true
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000D0D402006603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
> Found the USB handle.
> Stage: SPRAY
> ret: true
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000D0D402006603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
> Found the USB handle.
> Stage: SETUP
> ret: true
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000D0D402006603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
> Found the USB handle.
> Stage: PATCH
> ret: true
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 

And then the device will boot into system normally, and I need to Ctrl + C to terminate it manually.

Or, it will be stuck at some other stage for a while and then stuck after PATCH stage returns true.

Saw similar issue here: [https://github.com/0x7ff/gaster/issues/1](url)
I don't know if it helps :>

**Comment by runhuizhou** [comment]
> Make sure to go into dfu from recovery, not normal mode

Hi Nebula! Now I go into DFU mode from Recovery, and then it gets stuck at here too:

> [root@relafnic palera1n]# sudo ./palera1n.sh --dfu 15.7 --debug
> palera1n | Version 1.0.0
> Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy
> 
> [*] Getting device info...
> [*] Pwning device
> usb_timeout: 5
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000D0D402006603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
> Found the USB handle.
> Stage: RESET
> ret: true
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000D0D402006603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
> Found the USB handle.
> Stage: SPRAY
> ret: true
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000D0D402006603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
> Found the USB handle.
> Stage: SETUP
> ret: true
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000D0D402006603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
> Found the USB handle.
> Stage: PATCH
> ret: true
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
>

**Comment by itsnebulalol** [comment]
Have you tried replugging there? Unplug your device and plug it back in.

**Comment by runhuizhou** [comment]
Now firstly I manually enter recovery mode, and then dfu mode, and then execute commands:

> [root@relafnic palera1n]# sudo ./palera1n.sh --dfu 15.7 --debug
> palera1n | Version 1.0.0
> Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy
> 
> [*] Getting device info...
> [*] Pwning device
> usb_timeout: 5
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000D0D402006603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
> Found the USB handle.
> Stage: RESET
> ret: true
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000D0D402006603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
> Found the USB handle.
> Stage: SPRAY
> ret: true
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000D0D402006603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
> Found the USB handle.
> Stage: SETUP
> ret: true
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8011 CPRV:10 CPFM:03 SCEP:01 BDID:04 ECID:000D0D402006603A IBFL:3C SRTG:[iBoot-3135.0.0.2.3]
> Found the USB handle.
> Stage: PATCH
> ret: true
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> ^C
> [root@relafnic palera1n]# sudo ./palera1n.sh --dfu 15.7 --debug
> palera1n | Version 1.0.0
> Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy
> 
> [*] Getting device info...
> [*] Booting device
> [==================================================] 100.0%
> ERROR: Unable to connect to device
> [root@relafnic palera1n]# 
> 

Then moment the device booted into iPadOS, terminal said "ERROR: Unable to connect to device" :<

**Comment by itsnebulalol** [comment]
What linux distro is this?

**Comment by runhuizhou** [comment]
> What linux distro is this?

Arch linux

**Comment by itsnebulalol** [comment]
Hey, what device is this? Is this A11 or an iPad? If so, you’ll have to go into recovery first, then DFU. I recommend having palera1n guide you through it

**Comment by runhuizhou** [comment]
> Hey, what device is this? Is this A11 or an iPad? If so, you’ll have to go into recovery first, then DFU. I recommend having palera1n guide you through it

Hey it's a10x ipad pro10.5, the same device as the original post. Yes now I've been always go to rec first and then dfu. Still no luck.

**Comment by neizvedaniydag** [comment]
IPhone 7+, ios 15.4.1.
[*] Cleaning up work directory
[*] Booting ramdisk
[*] Getting device info... this may take a second
[========================================] 100.0%
[========================================] 100.0%
ERROR: Unable to connect to device
[-] An error occured

**Comment by tanghengvip** [comment]
> > What linux distro is this?
> 
> Hey! I tested on a MacBook Air, with Big Sur 11.7, where the pwning device issue has gone. But still got "ERROR: Unable to connect to device" when booting the device, and the device just boots into normal system itself. Here's the log: [loooog.txt](https://github.com/palera1n/palera1n/files/9685129/loooog.txt)

My iPad got exactly same problems. Have you found the way to solve it?

**Comment by runhuizhou** [comment]
> > > What linux distro is this?
> > 
> > 
> > Hey! I tested on a MacBook Air, with Big Sur 11.7, where the pwning device issue has gone. But still got "ERROR: Unable to connect to device" when booting the device, and the device just boots into normal system itself. Here's the log: [loooog.txt](https://github.com/palera1n/palera1n/files/9685129/loooog.txt)
> 
> My iPad got exactly same problems. Have you found the way to solve it?

Nah. I'm dumb :(

**Comment by DinkaKami22** [comment]
Hello everyone.
I have an iPad 6 (2018) on 15.7.  

Should I try this?
