### ISSUE TITLE
jailbreak ios 16.7.10 iphone x

### ISSUE THREAD

**Issue by alisaeed47** [palera1n/palera1n#502]
### Device

iphone x

### Version

ios 16.7.10

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

> 

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
then jailbreak it

**Comment by khcrysalis** [comment]
If you need actual help, open a new issue.
