### ISSUE TITLE
Is rootful actually rootful for iOS 17.7?

### ISSUE THREAD

**Issue by gexgamingyt** [palera1n/palera1n#503]
### Device

iPad

### Version

iOS 17.7

### Passcode?

- [X] Passcode is enabled.

### Start going into detail..

I have rootful success on my iPad 6th gen 2018 Wi-Fi iOS 17.7
trying to figure out is if there’s some official way to get semi tethered tweak or something in the options of palen1x is it impossible to get it to boot up palera1n without losing Sileo from a full reboot. Makes me wish there was more permanence of that rootful without losing access making me go back to the pc again. Hopefully this is relevant here.
![IMG_0004](https://github.com/user-attachments/assets/d2d37812-4d92-4c01-a854-fc111a781cca)

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
> Is rootful actually rootful for iOS 17.7?

Yes, rootful will never mean the jailbreak is gonna be untethered. Palera1n is in-fact a semi-tethered jailbreak and will never change.
