### ISSUE TITLE
iOS support on A11

### ISSUE THREAD

**Issue by cann3v** [palera1n/palera1n#508]
### Device

iPhone X

### Version

-

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

Hello! I'm conducting research on mobile application security, and I use palera1n for working with iOS. Currently, I’m using an iPhone 6s with iOS 15.8.3, but I now need to purchase a few more devices.

My question is: since the latest supported device is the iPhone X, does it matter which iOS version is installed on it when performing a rootfull jailbreak with palera1n? Or am I required to look for a iPhone X with a specific iOS version?

Thanks in advance for the answer.

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by ElliesSurviving** [comment]
you can jailbreak iPhone X on any version as long as you dont have a passcode set on iOS 14 and above. checkra1n does iOS 12-14, palera1n does 15-16, and if you somehow find one on iOS 11 i think electra is your only option

**Comment by cann3v** [comment]
Thanks.
