### ISSUE TITLE
No loader, Instead I get Xcode previews app

### ISSUE THREAD

**Issue by joshbguy1** [palera1n/palera1n#512]
### Device

IPhone 6S

### Version

iOS 15.8.3

### Passcode?

- [ ] Passcode is Disabled.

### Start going into detail..

16GB iPhone 6s, jailbroken with sudo palera1n -f -B and then rebooted into recovery and typed sudo palera1n -f, instead of the loader app I get an Xcode Previews app. No passcode.

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
Have you read https://docs.palera.in/docs/troubleshoot/troubleshooting-steps/#loader-application-not-appearing ?
