### ISSUE TITLE
Trouble Jailbreaking Device Please Help

### ISSUE THREAD

**Issue by NappyBoiiNate** [palera1n/palera1n#517]
### Device

iPad Pro 12.9 First Gen

### Version

iPadOS 16.7.10

### Passcode?

- [X] Passcode is enabled.

### Start going into detail..

When I try to jailbreak my device through Winra1n2.1 using the Palera1n options, it doesn’t work. I try to use the Rootful option with Fakefs and UsbDk selected, it goes throught the loading part normally. Once it boots up the iPad, it goes through part of the command prompt and freezes completely everytime. I’ve tried multiple PCs and Laptops, all windows products. When I use the Rootless option, it finally goes through but I can’t download Cydia and that’s what I ultimately want. If there is a jailbreak that works on my device please guide me to where it is. If the device can’t be jailbroken or it’s not supported please let me know. Thank You!
![IMG_1717](https://github.com/user-attachments/assets/d30923b3-d649-4e2d-a4d3-1c75e6b4923d)

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by asdfugil** [comment]
WinRa1n is not an offical palera1n product.

**Comment by NappyBoiiNate** [comment]
Is my device supported and do I need a macbook to install the jailbreak?
