### ISSUE TITLE
stuck

### ISSUE THREAD

**Issue by ebzrvf** [palera1n/palera1n#52]
[*] Cleaning up work directory
                                                         [*] Booting ramdisk
   [*] Getting device info... this may take a second
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
                                                           [*] Device should now show text on screen
                           [*] Waiting for the ramdisk to finish booting

**Comment by ebzrvf** [comment]
stuck in this

**Comment by ebzrvf** [comment]
> stuck in this

i fixed it and.. SILEO WORKS!

**Comment by itsnebulalol** [comment]
What was the issue?

**Comment by ebzrvf** [comment]
> 

the ramdisk stuck i fixed it with:
run: sudo systemctl stop usbmuxd
then run: sudo usbmuxd -p -f

**Comment by GeoffSI** [comment]
So should I be using Linux and not macOS?

**Comment by ebzrvf** [comment]
> 

yeah, use ubuntu 22.04 lts

**Comment by itsnebulalol** [comment]
macOS… should work the best

**Comment by GeoffSI** [comment]
I’m having similar USB errors that the people on Linux are having

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by itsnebulalol** [comment]
Please compile and install usbmuxd2. No help will be provided with compiling it though.
