### ISSUE TITLE
Device not entering in dfu mode

### ISSUE THREAD

**Issue by Tarun5139** [palera1n/palera1n#522]
### Device

iphone 7 

### Version

15.8.3

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

I am not able enter in dfu mode 
@afastaudir8 @sinoru @osir @GeoSn0w @itsnebulalol 
Could you please help me to fix this issue 
<img width="1374" alt="Screenshot 2024-11-27 at 4 06 34 PM" src="https://github.com/user-attachments/assets/101451a0-ef8e-4c46-b687-3d7ce682b2bd">

Regards 
Tarun 

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by ElliesSurviving** [comment]
you did NOT just ping 3 people who aren't associated with palera1n whatsoever...

ANYWAYS...

let me guess you are using a usb C to lightning cable. those dont enter DFU. you need a usb A to lightning cable to be able to DFU
