### ISSUE TITLE
timed out

### ISSUE THREAD

**Issue by taranmultani4413** [palera1n/palera1n#524]
### Device

iphone 7

### Version

ios 15.8.3

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

My device couldn't jailbreak it says device is disconnected then timed out

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by taranmultani4413** [comment]
<img width="590" alt="Screen Shot 2024-12-02 at 2 04 16 PM" src="https://github.com/user-attachments/assets/902e72a4-3be8-4c65-9e4c-dab908e76bf5">
<img width="590" alt="Screen Shot 2024-12-02 at 2 04 16 PM" src="https://github.com/user-attachments/assets/c7cc0e92-00ba-40f9-9b8a-246838aab774">

**Comment by khcrysalis** [comment]
I assume this is related to ["Timed out waiting for download mode"](https://docs.palera.in/docs/troubleshoot/troubleshooting-steps/#timed-out-waiting-for-download-mode), I would recommend you troubleshoot on your own with your current setup to find out whats wrong.

I will be closing this issue as there's many duplicates regarding this which all usually can be solved with the same answer.

**Comment by taranmultani4413** [comment]
Thanks it was  just the simple trick just unplug the cable and reconnect it.
