### ISSUE TITLE
Phone shuts down and restarts during jailbreak process

### ISSUE THREAD

**Issue by XdenGT** [palera1n/palera1n#528]
### Device

iPhone 8

### Version

iOS 16.7.10

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

When running the palera1x tool and entering DFU mode, I proceed through the jailbreak steps. After entering download mode, the tool runs for 5-6 seconds while displaying code on a CMD-like screen. However, before the jailbreak completes, the phone shuts down and restarts.

Actual behavior: The phone shuts down and restarts before the process finishes.

Additional info:

Secure Boot has been disabled in BIOS settings.
Tried with multiple USB cables and ports.

Any help or guidance is appreciated. Thank you!

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by TheMasterOfMike** [comment]
Sounds like you had a previous passcode set.

If you've ever set a passcode with A11 devices on iOS 16, you have to erase all content and settings.

**Comment by XdenGT** [comment]
> Sounds like you had a previous passcode set.
> 
> If you've ever set a passcode with A11 devices on iOS 16, you have to erase all content and settings.

So, after resetting my phone, if I perform the jailbreak during the setup process without setting any passcode, will it work?

**Comment by TheMasterOfMike** [comment]
setup the device first (you can setup the device without setting a passcode)

you can never set a passcode at all however - setting a passcode at all will require you to erase all content and settings

**Comment by TheMasterOfMike** [comment]
> Once I successfully perform the jailbreak, will there be any issues with creating a passcode using the Fake Passcode Tweak?

You can do that fine, but that passcode won't persist in stock iOS
