### ISSUE TITLE
seputil: Gigalockerfilr (/mnt7/longstringofnumbers.gl) doesn't exist

### ISSUE THREAD

**Issue by k0mraid3** [palera1n/palera1n#53]
iPhone X - 15.4.1 - ran in debug and normal, tried a clean run too. Hangs after starting the ramdisk script. vlan0 busy, timing out.  Seems like its targeting the wrong partition?

**Comment by itsnebulalol** [comment]
Can you test the latest commit (7f67026)

**Comment by k0mraid3** [comment]
on it.

**Comment by k0mraid3** [comment]
looks like im still hanging when its waiting for the ramdisk to finish booting (on host) on device screen, it mentions connectionresult new session to port 62878 failed: 61 <<<----- thats happening just shortly after the ramdisk script. i can share some pics ive got of the output from device (since im blind asf and cant read it otherwise lmao) -- However the mount issue does seem to have been resolved.
