### ISSUE TITLE
M1 Pro The DFU mode cannot be entered

### ISSUE THREAD

**Issue by jobsgxx** [palera1n/palera1n#530]
### Description

iPhone X16.0.2 using '-cf' The DFU mode cannot be entered

**Comment by jobsgxx** [comment]
MAC OS 12.6.2 The message is damaged and cannot be opened

**Comment by asdfugil** [comment]
Don’t use a USB-C cable

**Comment by jobsgxx** [comment]
> Don’t use a USB-C cable, and you can use USB-A adapters.

I used this
![image](https://github.com/user-attachments/assets/1b0b0b16-b917-4d5f-ac04-727124e48196)

**Comment by jobsgxx** [comment]
> 尝试拔下电源插头然后重新插入

Tried, and consistently stayed on this page

![image](https://github.com/user-attachments/assets/f14f9d0e-1e84-4e9b-b4c0-c50901356e67)

**Comment by jobsgxx** [comment]
I tried that only the beta7 version of palera1n-macos-x86_64 2.0 can run on MAC 12.x system, the others will not run, indicating that the file is corrupt。

**Comment by sassa7777** [comment]
Replug, and press control+c, and re-run the same command

**Comment by jobsgxx** [comment]
> 重新插上电源，按下 Control+C，然后重新运行相同的命令

Tried. Didn't work

**Comment by khcrysalis** [comment]
I'm going to close this as a problem with going into DFU mode is not the tools or our responsibility
