### ISSUE TITLE
iPadOS 17.7.3 support

### ISSUE THREAD

**Issue by Unb0rn** [palera1n/palera1n#531]
### Device

iPad Pro (iPad 7,2)

### Version

iPadOS 17.7.3

### Passcode?

- [X] Passcode is enabled.

### Start going into detail..

Looks like 17.7.3 crashes while booting from PongoOS. It spews stacktrace and an error about vm_map_protect patch

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
already fixed on main branches

**Comment by Unb0rn** [comment]
Was this fix pushed to this repo? I can see only one active branch - main. I tried CLI tool from releases (built from 95c7d1c) - it fails. There were some chores and the feature to bypass the passcode check, but no actual fix, or am I wrong?
Which commit should I build against?
Thanks!)

**Comment by khcrysalis** [comment]
Theres separate repositories for other components in palera1n, such as pongoos and jbinit.

It being on a main branch does not mean theres been a new releases.

**Comment by mainpart** [comment]
so what should i do to install this? i have downloaded palera1in yesterday an ran into same issue

**Comment by Unb0rn** [comment]
> so what should i do to install this? i have downloaded palera1in yesterday an ran into same issue

I guess we have two options - either we build the new PongoOS image from the corresponding repo and override it in palera1n CLI or we wait...
I have no time to set up a build environment - so, just waiting patiently)
