### ISSUE TITLE
Palera1n X

### ISSUE THREAD

**Issue by ahmedbeso7070** [palera1n/palera1n#534]
### Device

iPhone x

### Version

iOS 16.7.10

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

i use ubuntu and i can't jailbreak 

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
recreate your issue with proper details and logs, "I can't jailbreak doesn't help anyone"
