### ISSUE TITLE
iPadOS 17.7.3 not jailbreak

### ISSUE THREAD

**Issue by choimobile** [palera1n/palera1n#535]
### Device

iPad

### Version

17.7.3

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

iPadOS 17.7.3 not jailbreak

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
recreate your issue with proper details and logs, "I can't jailbreak doesn't help anyone"
