### ISSUE TITLE
ipadOS 17.7.3 Palera1n app loader not found after successfull checkmate 

### ISSUE THREAD

**Issue by jensecjensec** [palera1n/palera1n#536]
### Device

ipad 6th generation

### Version

ipadOS 17.7.3

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

I was successfully using ipadOS 17.7.2 in jailbreak and I updated to ipadOS 17.7.3 and re-jailbroke with 2.0.2 (palera1nx if that matters) with successfull checkmate and logo appear as usual however after jailbreak no jailbreak loader apps found. i have tried reset factory etc as well. I don't have passcode. Help would be greatly appreciated.  

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by khcrysalis** [comment]
The loader app not appearing is a common issue that we cannot really control, use the steps here https://docs.palera.in/docs/troubleshoot/troubleshooting-steps/#loader-application-not-appearing and make sure you're actually jailbroken.
