### ISSUE TITLE
Unable to download Sileo or Zebra

### ISSUE THREAD

**Issue by Claymorder** [palera1n/palera1n#538]
### Device

Iphone 8

### Version

IOS 16.7.7

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

After successfully using Palera1n to jailbreak my phone (Rootless), Palera1n is unable to download any package manager. I have left an image of the error i recieve. The device was freshly reset before jailbreaking. i didn't setup a password or touch id. It seems to be a timeout error from your website. I do not have good download speeds as you can see at the bottom of the picture, which might be the problem. I downloaded the file manually and was unable to find a way to install from my computer.
![tempImage7sbUP0](https://github.com/user-attachments/assets/14c469c7-f60d-461c-94fd-2f042345ae05)

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by Claymorder** [comment]
Right after posting this, I turned off my Mac that it was still plugged into and unplugged it. Then my download speed went up to 3mb/s and I successfully downloaded and installed. I would like to recommend the removal of a timeout function if possible.

**Comment by khcrysalis** [comment]
Theres no timeout function, this is using native ios download api's for downloading.
