### ISSUE TITLE
stuck on HandleConnectResult new session to port failed : 61

### ISSUE THREAD

**Issue by kimihime96** [palera1n/palera1n#54]
stuck on HandleConnectResult new session to port failed : 61
after showing any text on verbose mode,
then it show stuck on "HandleConnectResult new session to port failed : 61"
how i resolve this ?

**Comment by k0mraid3** [comment]
Likewise, i am able top get past particular issue by doing this in a second shell: 
sudo systemctl stop usbmuxd
sudo usbmuxd -p -f
