### ISSUE TITLE
palera1n: v2.1-beta.1 not working on tvOS 18.2. 

### ISSUE THREAD

**Issue by lechium** [palera1n/palera1n#543]
### Device

AppleTV5,3

### Version

18.2

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

When I try to run ./palera1n-macos-x86_64 -f (twice because of the bug where it gets stuck in pongoOS initially) the AppleTV just continues to blink and never actually boots. 

### Familiarity with palera1n

- [X] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [X] I am familiar with the command-line!

**Comment by asdfugil** [comment]
you need to create fakefs
