### ISSUE TITLE
Stuck Recovery Mode In 9,3

### ISSUE THREAD

**Issue by iwishthedeveloper** [palera1n/palera1n#55]
i tryed different verisons of linux but when it try to get device to recovery mode terminal gives a eror

**Comment by iwishthedeveloper** [comment]
oh i understand i didnt download libimobiledevice

**Comment by itsnebulalol** [comment]
You can use `irecovery -n` to exit recovery

**Comment by iwishthedeveloper** [comment]
i tryed it but cannot make palera1n jailbreak
