### ISSUE TITLE
cannot add sources

### ISSUE THREAD

**Issue by ledjo07** [palera1n/palera1n#56]
I cannot add sources in Sileo.It shows a message no release files

**Comment by itsnebulalol** [comment]
Most repos won’t work since they aren’t updated for rootless, and there’s no tweak injection anyway

**Comment by ledjo07** [comment]
> Most repos won’t work since they aren’t updated for rootless, and there’s no tweak injection anyway

what repos are working for the moment?

**Comment by itsnebulalol** [comment]
Please read the readme
