### ISSUE TITLE
Error installing bootstrap 5

### ISSUE THREAD

**Issue by pwnd2e** [palera1n/palera1n#57]
![IMG_1231](https://user-images.githubusercontent.com/104146035/193021137-4e4ca89b-08da-4a88-b540-e3084c178a1d.jpeg)

**Comment by mineek** [comment]
Can u try to ```cd``` into the ramdisk directory and then run ```git checkout cfe0b0f63cd90ab43ba66c9bf44156f1ff766f9d```, and back in the palera1n folder removing the blobs folder, then running the script again?

**Comment by pwnd2e** [comment]
I fixed it with a simple reset of device ty for response

**Comment by PoomSmart** [comment]
Tap "Remove" to uninstall bootstrap, relaunch the app and tap "Install" again will work.
