### ISSUE TITLE
support?

### ISSUE THREAD

**Issue by coldstudio1337** [palera1n/palera1n#61]
support iphone 6s with 15.5 beta 4?

**Comment by itsnebulalol** [comment]
Yes, but you’ll have to manually replace the ipsw in the code. Both ipswurl= lines should be changed to `ipswurl=your ipsw url`

**Comment by ItsKING1313** [comment]
Support iPhone 11 Pro Max iOS 15.6.1?

**Comment by itsnebulalol** [comment]
No, never. And please don't hijack older issues
