### ISSUE TITLE
Closes After Getting Device In Recovery Mode!

### ISSUE THREAD

**Issue by iwishthedeveloper** [palera1n/palera1n#62]
umm any helps?
![324725F0-814D-4B49-B486-292823DC323D](https://user-images.githubusercontent.com/66250015/193237831-ef854312-42a0-4c1d-ac30-7588bea587ac.jpeg)

**Comment by iwishthedeveloper** [comment]
update: tryed in recovery mode with dfu mode stuck in creating ramdisk
![C1956251-A719-4BC3-9A21-8F4B358C8CF7](https://user-images.githubusercontent.com/66250015/193243879-ebb5d2fc-5ade-4df4-8302-1d685811f1be.jpeg)

**Comment by iwishthedeveloper** [comment]
should i install usbmuxd?

**Comment by Ixolaro** [comment]
Try running or installing usbmuxd in aother terminal as sudo and try running palera1n as sudo

**Comment by iwishthedeveloper** [comment]
> 

i dont have original cable i think it effect it

**Comment by iwishthedeveloper** [comment]
Update:
Dont Use The Fucking Kali Just Use Ubuntu
