### ISSUE TITLE
I Broke Pogo(Not Sure How)

### ISSUE THREAD

**Issue by Dark98** [palera1n/palera1n#65]
My Tips/Pogo App Is Completely Unusable.. I've tried deleting the app but it just reappears after a reboot

![image](https://user-images.githubusercontent.com/5911848/193386415-79a98efd-d553-4e1b-9e4f-98fd48f96ce9.png)

**Comment by itsnebulalol** [comment]
That’s… weird. Seems like you freshly erased. If you don’t care about your data you can restore/erase in settings. 

Otherwise, you can try and install TrollStore to another removable app using SSHRD_Script, then boot palera1n and install Pogo through TrollStore.
