### ISSUE TITLE
Can't Bypass iCloud activation lock.

### ISSUE THREAD

**Issue by THEJAILBRAKEMAN** [palera1n/palera1n#66]
iPhone 8(GSM) 10,4 15.0. 
Am trying to bypass activation lock on an iPhone 8. 
I jailbrake it twice and it did't work at all.
Can some tell me if am suppose to be using to bypass or should i follow. 

Thanks for the help <3

**Comment by itsnebulalol** [comment]
We aren’t giving support for icloud lock bypass.

**Comment by Anderew-ch** [comment]
😂😂😂😂😂😂😂😂😂
