### ISSUE TITLE
Disconnect Eror

### ISSUE THREAD

**Issue by iwishthedeveloper** [palera1n/palera1n#68]
Can Someone Help?![6A8A2FF9-FE85-4344-A9EE-0E43AC33A587](https://user-images.githubusercontent.com/66250015/193449289-d4b6af22-249b-484b-a3ba-9a2f831d8ea8.jpeg)

**Comment by iwishthedeveloper** [comment]
Usbmuxd Log
![image](https://user-images.githubusercontent.com/66250015/193450978-fbdd0127-9dde-4dd8-b57d-9289fe219318.jpg)

**Comment by iwishthedeveloper** [comment]
Ops i think i should update palera1n

**Comment by neizvedaniydag** [comment]
have you solved this problem?
