### ISSUE TITLE
Create ramdisk

### ISSUE THREAD

**Issue by iKrut0nardo** [palera1n/palera1n#69]
When start to create a Ramdisk not work and terminal finish jailbreak. iPhone X iOS 15.6 reboot.

**Comment by itsnebulalol** [comment]
Can I please have more context? What PC operating system (and version if applicable), screenshots of the error when running with `--debug`

**Comment by SuginGv30** [comment]
I have this same issue

**Comment by SuginGv30** [comment]
> Can I please have more context? What PC operating system (and version if applicable), screenshots of the error when running with `--debug`

Linux 22.04 

With -- debug

tried with -- debug and the result is 

download succeeded
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000E4DEC38B8402E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 14 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x180032bf0 : 000080d2
applying patch=0x180032c44 : 000080d2
applying patch=0x180034750 : 200080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 14 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1  ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x180032bf0 : 000080d2
applying patch=0x180032c44 : 000080d2
applying patch=0x18001f8a8 : 000080d2c0035fd6
applying patch=0x18001f8f8 : 000080d2c0035fd6
applying patch=0x18006be6c : 000080d2c0035fd6
applying patch=0x180034750 : 200080d2
applying patch=0x180035cac : 183e5430
applying patch=0x1800de46d : 72643d6d64302064656275673d30783230313465202d76207764743d2d31202000
applying patch=0x180039060 : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
 Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-7195 inputted
get_amfi_out_of_my_way_patch: Found entitlements too small str loc at 0x40c7ee
get_amfi_out_of_my_way_patch: Found entitlements too small str ref at 0x11ac270
get_amfi_out_of_my_way_patch: Patching AMFI at 0x11a86e8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
fwrite: No space left on device
error: WRITE
error: Invalid argument
[-] An error occurred
ubuntu@ubuntu:~/Downloads/palera1n$
