### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by GeoffSI** [palera1n/palera1n#71]
<img width="827" alt="Screen Shot 2022-10-02 at 11 52 15 PM" src="https://user-images.githubusercontent.com/104477485/193498663-4fecf064-2143-431c-a57f-5351f46d5d04.png">

Not sure if this is something bad.

**Comment by neizvedaniydag** [comment]
http://lifeonubuntu.com/tar-errors-ignoring-unknown-extended-header-keyword/

> <img alt="Screen Shot 2022-10-02 at 11 52 15 PM" width="827" src="https://user-images.githubusercontent.com/104477485/193498663-4fecf064-2143-431c-a57f-5351f46d5d04.png">
> 
> Not sure if this is something bad.

**Comment by GeoffSI** [comment]
I looked it up before falling asleep. Apparently is has something to do with how tar files are being handled. This can be marked closed. lol

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by itsnebulalol** [comment]
Yep that’s fine, it happens when extracting the ramdisk tar
