### ISSUE TITLE
how to fix it?

### ISSUE THREAD

**Issue by neizvedaniydag** [palera1n/palera1n#72]
<img width="682" alt="screen" src="https://user-images.githubusercontent.com/62785983/193569472-461b6bb1-893f-425e-aa0c-5af3a56bb726.png">

**Comment by neizvedaniydag** [comment]
ubuntu has the same mistake

**Comment by neizvedaniydag** [comment]
I used all possible attempts, but unfortunately nothing came out. I activated recovery mode, and only then in dfu

**Comment by kristenlc** [comment]
the device is exiting dfu mode too early, please follow the instructions in [this video](https://www.youtube.com/watch?v=LzTHH9tqVoo&t=1s). i think the instructions go for all a11 devices, iphone 8, 8+, and x.

**Comment by neizvedaniydag** [comment]
I have a10(

**Comment by neizvedaniydag** [comment]
Thanks, I'll try

**Comment by neizvedaniydag** [comment]
I have a new error now
<img width="682" alt="screen" src="https://user-images.githubusercontent.com/62785983/193592166-fc906597-60ba-46a5-b378-a5b8ca505ab6.png">

**Comment by GeoffSI** [comment]
> <img alt="screen" width="682" src="https://user-images.githubusercontent.com/62785983/193569472-461b6bb1-893f-425e-aa0c-5af3a56bb726.png">

that's because your pid is still using the port.
run `lsof -i | grep LISTEN` to see which pid is using the port. Then run `kill 1234` 123 being which ever PID is in use. it might show iProxy instead of 2222.

**Comment by neizvedaniydag** [comment]
is it possible to jailbreak via ipad in the troll store?
