### ISSUE TITLE
I tried to install pogo through the troll store, and such an error

### ISSUE THREAD

**Issue by neizvedaniydag** [palera1n/palera1n#74]
![IMG_0DFFE618932E-1](https://user-images.githubusercontent.com/62785983/193609153-89d21753-5426-4718-afe6-638abaf3fd63.jpeg)

**Comment by GeoffSI** [comment]
What iDevice, iOS/iPad version, and computer operating system are you using?

**Comment by neizvedaniydag** [comment]
> 

mac os 12.6 
IPhone 7+, ios 15.4.1

**Comment by neizvedaniydag** [comment]
> What iDevice, iOS/iPad version, and computer operating system are you using?
> 
> EDIT: You probably haven't successfully booted through palera1n. You should reboot and run again.
Is frozen
<img width="682" alt="" src="https://user-images.githubusercontent.com/62785983/193636634-9b5ecae5-cb94-49c9-ae31-005b268f2349.png">

**Comment by itsnebulalol** [comment]
please add `--debug` to the command so we can see the issue

**Comment by neizvedaniydag** [comment]
> please add `--debug` to the command so we can see the issue
[22:52:49-2022-10-04-Darwin-21.6.0.log](https://github.com/palera1n/palera1n/files/9710175/22.52.49-2022-10-04-Darwin-21.6.0.log)

**Comment by itsnebulalol** [comment]
Did the device verbose

**Comment by neizvedaniydag** [comment]
> Did the device verbose

Ios 15.4.1 Iphone 7+ Macos 12.6

**Comment by itsnebulalol** [comment]
What?
