### ISSUE TITLE
can't install on ios 15.6.1 iphone 7

### ISSUE THREAD

**Issue by tho493** [palera1n/palera1n#78]

**Comment by Beast9265** [comment]
how can we help if you don't tells us the error

**Comment by tho493** [comment]
![IMG_20221004_023730](https://user-images.githubusercontent.com/63458055/193663957-9c2574a7-3e4a-44e4-93da-4ec4af361a19.jpg)
Sorry 🤧

**Comment by itsnebulalol** [comment]
Please try again but use the `--debug` argument so we can see the issue

**Comment by tho493** [comment]
> Please try again but use the `--debug` argument so we can see the issue

[sudo] mật khẩu dành cho tho493: 
palera1n | Version 1.0.0-3571c3b
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

Hello, iPhone9,1 on 15.6.1!
[*] Switching device into recovery mode...
Telling device with udid 44571160bf032b369308b7e179addf4e7abb0968 to enter recovery mode.
Device is successfully switching to recovery mode.
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Creating ramdisk
[*] Getting device info... this may take a second
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
Saved IM4M to work/IM4M
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98010/39CE5096-991E-4C25-87BF-7FF9181C07CA/iPhone_4.7_P3_14.8_18H17_Restore.ipsw
init done
getting: BuildManifest.plist
  0% [                                                                          100% [==========================================================================  3% [==>                                                                         6% [=====>                                                                      9% [========>                                                                  13% [============>                                                              16% [===============>                                                           19% [==================>                                                        22% [=====================>                                                     25% [========================>                                                  29% [============================>                                              32% [===============================>                                           35% [==================================>                                        39% [======================================>                                    42% [=========================================>                                 45% [============================================>                              49% [================================================>                          52% [===================================================>                       55% [======================================================>                    59% [==========================================================>                62% [=============================================================>             65% [================================================================>          69% [====================================================================>      72% [=======================================================================>   75% [========================================================================== 78% [========================================================================== 82% [========================================================================== 85% [========================================================================== 88% [========================================================================== 92% [========================================================================== 95% [========================================================================== 98% [==========================================================================100% [===================================================================================================>]
download succeeded
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98010/39CE5096-991E-4C25-87BF-7FF9181C07CA/iPhone_4.7_P3_14.8_18H17_Restore.ipsw
init done
getting: Firmware/dfu/iBSS.d10.RELEASE.im4p
  0% [                                                                          100% [===================================================================================100% [===================================================================================================>]
download succeeded
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98010/39CE5096-991E-4C25-87BF-7FF9181C07CA/iPhone_4.7_P3_14.8_18H17_Restore.ipsw
init done
getting: Firmware/dfu/iBEC.d10.RELEASE.im4p
100% [===================================================================================================>]
download succeeded
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98010/39CE5096-991E-4C25-87BF-7FF9181C07CA/iPhone_4.7_P3_14.8_18H17_Restore.ipsw
init done
getting: Firmware/all_flash/DeviceTree.d10ap.im4p
100% [===================================================================================================>]
download succeeded
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98010/39CE5096-991E-4C25-87BF-7FF9181C07CA/iPhone_4.7_P3_14.8_18H17_Restore.ipsw
init done
getting: Firmware/018-61747-017.dmg.trustcache
100% [===================================================================================================>]
download succeeded
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98010/39CE5096-991E-4C25-87BF-7FF9181C07CA/iPhone_4.7_P3_14.8_18H17_Restore.ipsw
init done
getting: kernelcache.release.iphone9
100% [===================================================================================================>]
download succeeded
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-98010/39CE5096-991E-4C25-87BF-7FF9181C07CA/iPhone_4.7_P3_14.8_18H17_Restore.ipsw
init done
getting: 018-61747-017.dmg
100% [===================================================================================================>]
download succeeded
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:00092104242A0326 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:00092104242A0326 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 14 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c2d88 : 000080d2
applying patch=0x1800c2ddc : 000080d2
applying patch=0x1800c4758 : 200080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 14 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1  ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c2d88 : 000080d2
applying patch=0x1800c2ddc : 000080d2
applying patch=0x1800b38c8 : 000080d2c0035fd6
applying patch=0x1800b3918 : 000080d2c0035fd6
applying patch=0x1800f0d28 : 000080d2c0035fd6
applying patch=0x1800c4758 : 200080d2
applying patch=0x1800c5d38 : f9473430
applying patch=0x18012e635 : 72643d6d64302064656275673d30783230313465202d76207764743d2d31202000
applying patch=0x1800c8a14 : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
main: Detected fat macho kernel
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-7195 inputted
get_amfi_out_of_my_way_patch: Found entitlements too small str loc at 0x9015f7
get_amfi_out_of_my_way_patch: Found entitlements too small str ref at 0xfc6f30
get_amfi_out_of_my_way_patch: Patching AMFI at 0xfc1df8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
none
none

[*] Cleaning up work directory
[*] Booting ramdisk
[*] Getting device info... this may take a second
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Device should now show text on screen
[*] Waiting for the ramdisk to finish booting
Creating listening port 2222 for device port 22
waiting for connection
New connection for 2222->22, fd = 5
waiting for connection
Connecting to usbmuxd failed, terminating.
New connection for 2222->22, fd = 5
waiting for connection
Connecting to usbmuxd failed, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5 
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection
No connected device found, terminating.
New connection for 2222->22, fd = 5
waiting for connection

**Comment by iwishthedeveloper** [comment]
> 

i have same eror i think installig usbmuxd2 can solve it
