### ISSUE TITLE
iPad 12.9 1st Gen, img4tool: failed with exception.

### ISSUE THREAD

**Issue by fruitbow1** [palera1n/palera1n#80]
Running On MacBook Air 2014 Catalina, 
iPad 12.9 1st Gen 15.7

Debug Log - 
[*] Getting device info...
[*] Creating ramdisk
Archive:  gaster-Darwin.zip
  inflating: gaster                  
[*] Getting device info... this may take a second
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
img4tool: failed with exception:
[exception]:
what=Failed to read shshFile
code=19529736
line=298
file=main.cpp
commit count=197:
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f:
[-] An error occurred

Any Ideas?

**Comment by itsnebulalol** [comment]
Please reclone the repo and try again. May be a Catalina thing because i’ve never seen this happen

**Comment by fruitbow1** [comment]
Same issue on Linux and Monterrey; On both MacBook Pro 2017 and MacBook air 2014 - 

sudo bash ./palera1n.sh  --dfu 15.7 --debug
palera1n | Version 1.0.0-3571c3b
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk
[*] Getting device info... this may take a second
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
img4tool: failed with exception:
[exception]:
what=Failed to read shshFile
code=19529736
line=298
file=main.cpp
commit count=197
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f
[-] An error occurred

**Comment by itsnebulalol** [comment]
What branch is this? main or tweaks?

**Comment by fruitbow1** [comment]
Main buddy!

**Comment by CitricDolphin1** [comment]
Second this, exact same issue on Ubuntu 22.04 with an iPad Pro 12.9 1st Gen
