### ISSUE TITLE
Ramdisk logic crashes if Tips isn’t installed

### ISSUE THREAD

**Issue by kirb** [palera1n/palera1n#82]
I ran the script forgetting that I uninstalled Tips on my phone. The script failed with:

```
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
[-] An error occurred
```

Running the `find` command directly in ssh I confirmed it returns nothing. So perhaps there should be a check to ensure `[[ $tipsdir != "" ]]`, reboot the phone, and display a message to install Tips and try again.

**Comment by itsnebulalol** [comment]
Just added a warning to the readme, will fix this tomorrow. Thanks for pointing this out

(pinning so I don’t forget later)

**Comment by itsnebulalol** [comment]
Implemented

**Comment by buzzcoding** [comment]
@itsnebulalol In the if statement, the variable needs quotes or it will not work if it is not installed. If it is not installed, it says:
`bash: [: =: unary operator expected`

The line (368) needs to be:
`if [ "$tipsdir" = "" ]; then`
