### ISSUE TITLE
Sileo Not installing

### ISSUE THREAD

**Issue by SuperAviation001** [palera1n/palera1n#84]
Sileo isn’t installing on my iPad (iPad7,11) on iPadOS 15.5

**Comment by SuperAviation001** [comment]
More info, Sileo installs but when I check the home screen and app library it doesnt show up.

**Comment by zenos3000** [comment]
Silos is also not installing in my IPad 7th gen, even the tool option is also crashing. Tips stops working too if I restart my iPad.

**Comment by itsnebulalol** [comment]
You need to hit do all in pogo settings

**Comment by zenos3000** [comment]
How am I supposed to click do all if tool option is crashing and now the tips is also crashing after I restart my ipad
