### ISSUE TITLE
Listen port 2222 address already in use

### ISSUE THREAD

**Issue by jthorpe6** [palera1n/palera1n#85]
I've not been able to get the script to complete on iPhone9,3 iOS 15.7. Using the `--debug` flag I can see that port 2222 is already in use. However, searching for this in the process list shows that the only process running something on port 2222 is the ssh command itself.

```
[~/o/palera1n]% ps -Ao user,pid,command | grep 2222               
jthorpe           1441 ssh -o StrictHostKeyChecking=no -p2222 root@localhost echo connected
jthorpe           1440 /Users/jthorpe/opt/palera1n/binaries/Darwin/sshpass -p zzzzzz ssh -o StrictHostKeyChecking=no -p2222 root@localhost echo connec 
```

I tried changing the port to something like 6666, but this made no difference.

I've attached the full debug log. 

[palera1n.log](https://github.com/palera1n/palera1n/files/9706278/palera1n.log)

**Comment by itsnebulalol** [comment]
Usually if that error shows, but iproxy is actually running on it, it will still be fine. Did the script quit after that?

**Comment by jthorpe6** [comment]
I left if for 2 hours like that with no apparent change. So I cancelled it out. any suggestions ? I can provide serial output if that would help.

**Comment by jthorpe6** [comment]
I tried on a different computer, and got further. Going to put this down to a "me" problem.
