### ISSUE TITLE
iPad Pro 1st Gen + iOS 15.5

### ISSUE THREAD

**Issue by Shaneee** [palera1n/palera1n#88]
Running on macOS Ventura dev beta. Python and pip installed and up to date. 

palera1n % ./palera1n.sh --dfu 15.5 --debug
palera1n | Version 1.0.0-3571c3b
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk
[*] Getting device info... this may take a second
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
img4tool: failed with exception:
[exception]:
what=Failed to read shshFile
code=19529736
line=298
file=main.cpp
commit count=197:
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f:
[-] An error occurred

**Comment by Shaneee** [comment]
With a bit of tweaking got this,

Now you can boot untrusted images.
[*] Booting device
[*] Tweaks enabled, running postinstall.
[!] Please install OpenSSH, curl, and wget from Sileo (repo is mineek.github.io/repo). Then, press any key to continue

But device is sitting with a blank screen. If I press a key to continue I get this,

[*] Installing tweak support, please follow the instructions 100% or unexpected errors may occur
[!] If asked for a password, enter 'alpine'.
bind(): Address already in use
Error creating socket for listen port 2222: Address already in use
Creating listening port 2222 for device port 22
scp: Connection closed

**Comment by Shaneee** [comment]
Got a bit further now but the loader isn't found,

cp: /usr/local/bin/loader.app/*: No such file or directory

Tips app is indeed installed.

**Comment by Shaneee** [comment]
> You should be using the rootless branch since you're on 15.5

rootless branch doesn't work either,

palera1n % ./palera1n.sh --dfu 15.5 --debug
palera1n | Version 1.0.0-b7451f5
Written by Nebula and Mineek | Some code and ramdisk from Nathan | Loader app by Amy

[*] Getting device info...
[*] Creating ramdisk
[*] Getting device info... this may take a second
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f
Compiled with plist: YES
img4tool: failed with exception:
[exception]:
what=Failed to read shshFile
code=19529736
line=298
file=main.cpp
commit count=197:
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f:
[-] An error occurred

**Comment by MicalShow** [comment]
Manually rename your backup 15.xshsh2 to 0X8001.SHSH and put it in the palera1n/ramdisk/shsh directory, then continue, you should now find it working. @Shaneee
