### ISSUE TITLE
get all the way to boot then this

### ISSUE THREAD

**Issue by pwnd2e** [palera1n/palera1n#90]
[*] Disabling tweaks
[*] Getting device info...
[*] Pwning device
[*] Booting device
[==================================================] 100.0%
ERROR: Unable to connect to device

**Comment by itsnebulalol** [comment]
Compile and install usbmuxd2

**Comment by pwnd2e** [comment]
I'm on Mac m1 not linux

**Comment by itsnebulalol** [comment]
Make sure you're going to recovery then dfu
