### ISSUE TITLE
I am stuck at getting device info... ERROR: Unable to connect device

### ISSUE THREAD

**Issue by laimetal** [palera1n/palera1n#92]
jq: error (at <stdin>:1): Cannot index number with string "firmwares"
parse error: Invalid numeric literal at line 1, column 9

**Comment by VanillaDome** [comment]
I'm getting the same issue on iPhone X, iOS 15.0, on Ubuntu 20.04.

**Comment by itsnebulalol** [comment]
Add sudo in the beginning of the command

**Comment by RavanGami** [comment]
error unable to connect to device linux iphone boot
