### ISSUE TITLE
Deep sleep bug in tweaks branch?

### ISSUE THREAD

**Issue by mineLdiver** [palera1n/palera1n#93]
**Describe the bug**
When idling on home screen or in sleep mode, device panics

**Expected behavior**
No panics

**Screenshots**
Can't screenshot a kernel panic

**Info:**
- iDevice: iPhone 8, GSM
- iDevice's version: iOS 15.1
- Computer OS and version: Mint 21
- The command you ran: sudo ./palera1n.sh --tweaks 15.1 --debug

**Additional context**
For some weird reason, idling on home screen stopped giving panics after I rejailbroke the device from scratch, yet sleep mode still panics after a minute or two

**Debug log**
I wasn't sure if the log was needed at all since this was happening post the jailbreaking process, and I'm not sure if there's any sensitive info in the logs that I should edit out

**Comment by guacaplushy** [comment]
you're a11.

**Comment by mineLdiver** [comment]
> 

That shouldn't matter on the tweaks branch though. No one else with A11 experiences this, except for me for some weird reason.

**Comment by guacaplushy** [comment]
hmmmm

**Comment by KhaledCP** [comment]
> > 
> 
> That shouldn't matter on the tweaks branch though. No one else with A11 experiences this, except for me for some weird reason.

Actually I do have the same problem.

**Comment by mineLdiver** [comment]
> > @mineLdiver That shouldn't matter on the tweaks branch though. No one else with A11 experiences this, except for me for some weird reason.
> 
> Actually I do have the same problem.

Tweaks branch and A11?

**Comment by KhaledCP** [comment]
> > > @mineLdiver That shouldn't matter on the tweaks branch though. No one else with A11 experiences this, except for me for some weird reason.
> > 
> > 
> > Actually I do have the same problem.
> 
> Tweaks branch and A11?

Yep

**Comment by mineLdiver** [comment]
Found a workaround thanks to someone on palera1n's discord server.
iNoSleep tweak by pwnd2e seems to have fixed the panics for me.

Well, still, this is just a workaround, so I'm gonna leave the issue open.

**Comment by ismat-d** [comment]
How did You manage to install this iNoSleep tweak ?

**Comment by mineLdiver** [comment]
> How did You manage to install this iNoSleep tweak ?

Wdym? Just like any other tweak. The repo is packix.

**Comment by ismat-d** [comment]
I installed the tweak , nothing changed , still having the same problem , sudden sleep , phone gets hot , force reboot 😩
Thanks for your help anyway 🙏
