### ISSUE TITLE
Creating ramdisk

### ISSUE THREAD

**Issue by maxperry71** [palera1n/palera1n#94]
Device is successfully switching to recovery mode.
[*] Waiting for device to reconnect in recovery mode
[*] Getting device info...
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Creating ramdisk
[-] An error occurred

**Comment by itsnebulalol** [comment]
Please use --debug
