### ISSUE TITLE
palera1n stuck on verbose boot and booting ramdisk, iPad7,11 on iPadOS 15.5

### ISSUE THREAD

**Issue by SuperAviation001** [palera1n/palera1n#95]
It doesnt finish booting ramdisk and its stuck on verbose boot, OS: Ubuntu 22.04.1
Debug logs: 
download succeeded
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:1C ECID:001A50E01A8A8026 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:1C ECID:001A50E01A8A8026 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 14 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c64d8 : 000080d2
applying patch=0x1800c652c : 000080d2
applying patch=0x1800c7ea8 : 200080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 14 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1  ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c64d8 : 000080d2
applying patch=0x1800c652c : 000080d2
applying patch=0x1800b38a4 : 000080d2c0035fd6
applying patch=0x1800b38f4 : 000080d2c0035fd6
applying patch=0x1800f17fc : 000080d2c0035fd6
applying patch=0x1800c7ea8 : 200080d2
applying patch=0x1800c93d8 : b9b33230
applying patch=0x18012ea4d : 72643d6d64302064656275673d30783230313465202d76207764743d2d31202000
applying patch=0x1800cc0b0 : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
main: Detected fat macho kernel
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-7195 inputted
get_amfi_out_of_my_way_patch: Found entitlements too small str loc at 0x9015f7
get_amfi_out_of_my_way_patch: Found entitlements too small str ref at 0xfcef30
get_amfi_out_of_my_way_patch: Patching AMFI at 0xfc9df8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
none
none

[*] Cleaning up work directory
[*] Booting ramdisk
[*] Getting device info... this may take a second
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Device should now show text on screen
[*] Waiting for the ramdisk to finish booting
Creating listening port 2222 for device port 22
waiting for connection
New connection for 2222->22, fd = 5
waiting for connection
Connecting to usbmuxd failed, terminating.
New connection for 2222->22, fd = 5
waiting for connection
Connecting to usbmuxd failed, terminating.
New connection for 2222->22, fd = 5
waiting for connection
Connecting to usbmuxd failed, terminating.
New connection for 2222->22, fd = 5
waiting for connection

**Comment by SuperAviation001** [comment]
I will try use a different USB cable and I will notify if it works.

**Comment by SuperAviation001** [comment]
I fixed the issue by running opening a new terminal on desktop while the issue occured and running 2 commands:
sudo systemctl stop usbmuxd
and
sudo usbmuxd -p -f
then i minimized the terminal window, went back to palera1n and it worked!

**Comment by zenos3000** [comment]
U have ipad 7th gen right? Is sileo installing to u? And is ur Tips not crashing when u take a restart? Tools option is also crashing or not?

**Comment by SuperAviation001** [comment]
> U have ipad 7th gen right? Is sileo installing to u? And is ur Tips not crashing when u take a restart? Tools option is also crashing or not?

Before it jailbroke successfully but sileo didnt install, shortly after i closed this I got another error.

**Comment by SuperAviation001** [comment]
> U have ipad 7th gen right? Is sileo installing to u? And is ur Tips not crashing when u take a restart? Tools option is also crashing or not?

After reboot tips will crash cuz reboot unjailbreaks, and the app will stay hijacked but it wont allow it to run because it is modified, also I havent retried the tips option, I will tell, if tips work after I reset, restore and rejailbreak my iPad

**Comment by zenos3000** [comment]
Thanks man, I really appreciate it.
