### ISSUE TITLE
Error: file AssetData/boot/BuildManifest.plist does not exist, or is a directory. on iPad7,11 running iPadOS 15.5

### ISSUE THREAD

**Issue by SuperAviation001** [palera1n/palera1n#96]
This error keeps happening then the palera1n script stops randomly, i am on Ubuntu 22.04.1
Debug logs:
Requesting connecion to USB device handle 1 (serial: ramdisk tool Sep 18 2022 20:14:43[*] Waiting for device in normal mode
[*] Switching device into recovery mode...
Telling device with udid aa56429ee0a5433b09939f056d0c0533e14fa431 to enter recovery mode.
Device is successfully switching to recovery mode.
[*] Waiting for device to reconnect in recovery mode
[*] Press any key when ready for DFU mode
Get ready (0) 
Hold volume down + side button (0) 
Keep holding (0)
Release side button, but keep holding volume down (0)  
[*] Device entered DFU!
[*] Pwning device
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:1C ECID:001A50E01A8A8026 IBFL:3C SRTG:[iBoot-2696.0.0.1.33]
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:1C ECID:001A50E01A8A8026 IBFL:3C SRTG:[iBoot-2696.0.0.1.33]
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:1C ECID:001A50E01A8A8026 IBFL:3C SRTG:[iBoot-2696.0.0.1.33]
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:1C ECID:001A50E01A8A8026 IBFL:3C SRTG:[iBoot-2696.0.0.1.33]
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:1C ECID:001A50E01A8A8026 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[*] Converting blob
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
Saved IM4M to work/IM4M
[*] Downloading BuildManifest
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022SpringFCS/fullrestores/012-07335/374BF02E-913A-4690-9DD6-1110FFF5790C/iPad_10.2_15.5_19F77_Restore.ipsw
init done
Error: file AssetData/boot/BuildManifest.plist does not exist, or is a directory

**Comment by itsnebulalol** [comment]
Is this the tweaks or rootless branch

**Comment by SuperAviation001** [comment]
> Is this the tweaks or rootless branch

Rootless as i am on 15.5

**Comment by SuperAviation001** [comment]
Is there any solutions or fixes for this?

**Comment by itsnebulalol** [comment]
Should be fixed in latest commit

**Comment by SuperAviation001** [comment]
> Should be fixed in latest commit

Tysm i will try rejailbreaking on macbook
